export interface AppSettings {
  storeName: string;
  brandName?: string;
  phone?: string;
  address?: string;
  lowStockThreshold?: number;
  invoiceFooter?: string;
  invoiceQR?: string;
  taxNumber?: string;
  taxRate?: number;
  taxMode?: string;
  paperSize?: 'a4' | 'receipt' | string;
  invoiceNumberingScheme?: 'daily' | 'sequential' | string;
  managerPin?: string;
  hasManagerPin?: boolean;
  autoBackup?: 'on' | 'off' | string;
  accentColor?: string;
  logoData?: string;
  currentBranchId?: string;
  currentLocationId?: string;
  printShowDocumentType?: boolean;
  printShowLogo?: boolean;
  printShowPhone?: boolean;
  printShowAddress?: boolean;
  printShowTaxNumber?: boolean;
  printShowCustomer?: boolean;
  printShowDocumentNumber?: boolean;
  printShowOrderType?: boolean;
  printShowDeliveryCustomerDetails?: boolean;
  printShowCashier?: boolean;
  printShowBranch?: boolean;
  printShowLocation?: boolean;
  printShowTax?: boolean;
  printShowPaymentMethod?: boolean;
  printShowItemSummary?: boolean;
  printShowPaymentBreakdown?: boolean;
  printShowFooter?: boolean;
  printCompactReceipt?: boolean;
  posReceiptTheme?: 'boxed' | 'classic' | 'ultra-compact' | string;
  printNumberFormat?: 'arabic' | 'english' | string;
  manufacturingModuleEnabled?: boolean;
  importModuleEnabled?: boolean;
  comboModuleEnabled?: boolean;
  restaurantModuleEnabled?: boolean;
  posShowCartMeta?: boolean;
  printDeliveryRepOnReceipt?: boolean;
  clothingModuleEnabled?: boolean;
  enableMobileStoreFeatures?: boolean;
  enablePharmacyModule?: boolean;
  maintenanceProfile?: string;
  enableEnterpriseFeatures?: boolean;
  technicianCommissionRate?: number;
  defaultProductKind?: 'standard' | 'fashion' | string;
  defaultPosMode?: 'scanner' | 'touch' | string;
  deliveryFeeMode?: 'freelance_courier' | 'store_fleet' | string;
  storeFleetCommissionRate?: number;
  allowNegativeStockSales?: boolean;
  allowSellingBelowStock?: boolean;
  allowZeroPurchaseCost?: boolean;
  requireCashierShiftForSales?: boolean;
  posKitchenPrinterEnabled?: boolean;
  posKitchenPrinterAuto?: boolean;
  weightedBarcodeEnabled?: boolean;
  weightedBarcodePrefix?: string;
  weightedBarcodeProductCodeLength?: number;
  weightedBarcodeWeightDigits?: number;
  weightedBarcodeWeightDecimals?: number;
  theme?: string;
  uiLanguage?: 'ar' | 'en' | string;
  currency?: string;
  timezone?: string;
  dateFormat?: string;
  timeFormat?: '12h' | '24h' | string;
  defaultBranchIssueMode?: 'final_issue' | 'transfer_to_branch_stock';
  hrSalesCommissionType?: 'none' | 'percentage' | 'target_bonus' | string;
  hrSalesCommissionValue?: number;
  hrSalesCommissionTarget?: number;
  hrDelayPolicyEnabled?: boolean;
  hrDelayPenalty1st?: number;
  hrDelayPenalty2nd?: number;
  hrDelayPenalty3rd?: number;
  hrDelayPenalty4th?: number;
}
