export interface AppSettings {
  storeName: string;
  brandName?: string;
  phone?: string;
  address?: string;
  lowStockThreshold?: number;
  invoiceFooter?: string;
  invoiceQR?: string;
  taxNumber?: string;
  taxRate?: number;
  taxMode?: string;
  paperSize?: 'a4' | 'receipt' | string;
  managerPin?: string;
  hasManagerPin?: boolean;
  autoBackup?: 'on' | 'off' | string;
  accentColor?: string;
  logoData?: string;
  currentBranchId?: string;
  currentLocationId?: string;
  printShowLogo?: boolean;
  printShowPhone?: boolean;
  printShowAddress?: boolean;
  printShowTaxNumber?: boolean;
  printShowCustomer?: boolean;
  printShowCashier?: boolean;
  printShowBranch?: boolean;
  printShowLocation?: boolean;
  printShowTax?: boolean;
  printShowPaymentMethod?: boolean;
  printShowItemSummary?: boolean;
  printShowPaymentBreakdown?: boolean;
  printShowFooter?: boolean;
  printCompactReceipt?: boolean;
  printNumberFormat?: 'arabic' | 'english' | string;
  manufacturingModuleEnabled?: boolean;
  comboModuleEnabled?: boolean;
  clothingModuleEnabled?: boolean;
  defaultProductKind?: 'standard' | 'fashion' | string;
  defaultPosMode?: 'scanner' | 'touch' | string;
  allowNegativeStockSales?: boolean;
  allowSellingBelowStock?: boolean;
  allowZeroPurchaseCost?: boolean;
  requireCashierShiftForSales?: boolean;
  posKitchenPrinterEnabled?: boolean;
  posKitchenPrinterAuto?: boolean;
  weightedBarcodeEnabled?: boolean;
  weightedBarcodePrefix?: string;
  weightedBarcodeProductCodeLength?: number;
  weightedBarcodeWeightDigits?: number;
  weightedBarcodeWeightDecimals?: number;
  theme?: string;
  uiLanguage?: 'ar' | 'en' | string;
  currency?: string;
  timezone?: string;
  dateFormat?: string;
  timeFormat?: '12h' | '24h' | string;
  defaultBranchIssueMode?: 'final_issue' | 'transfer_to_branch_stock';
}
