export interface AppSettings {
  storeName: string;
  brandName?: string;
  phone?: string;
  address?: string;
  lowStockThreshold?: number;
  invoiceFooter?: string;
  invoiceQR?: string;
  taxNumber?: string;
  taxRate?: number;
  taxMode?: string;
  paperSize?: 'a4' | 'receipt' | string;
  managerPin?: string;
  hasManagerPin?: boolean;
  autoBackup?: 'on' | 'off' | string;
  accentColor?: string;
  logoData?: string;
  currentBranchId?: string;
  currentLocationId?: string;
  printShowLogo?: boolean;
  printShowPhone?: boolean;
  printShowAddress?: boolean;
  printShowTaxNumber?: boolean;
  printShowCustomer?: boolean;
  printShowCashier?: boolean;
  printShowBranch?: boolean;
  printShowLocation?: boolean;
  printShowTax?: boolean;
  printShowPaymentMethod?: boolean;
  printShowItemSummary?: boolean;
  printShowPaymentBreakdown?: boolean;
  printShowFooter?: boolean;
  printCompactReceipt?: boolean;
  clothingModuleEnabled?: boolean;
  defaultProductKind?: 'standard' | 'fashion' | string;
  theme?: string;
}
