export const queryKeys = {
  dashboardOverview: (from: string, to: string) => ['dashboard-overview', from, to] as const,
  products: ['products'] as const,
  posProducts: (locationId: string, mode: 'browse' | 'barcode' | 'search', term: string, limit: number) => ['products', 'pos', locationId || 'all', mode, term || '', String(limit)] as const,
  productsPage: (paramsKey: string) => ['products', 'page', paramsKey] as const,
  productsCategories: ['products', 'categories'] as const,
  productsSuppliers: ['products', 'suppliers'] as const,
  productsCustomers: ['products', 'customers'] as const,
  categories: ['categories'] as const,
  suppliers: ['suppliers'] as const,
  suppliersPage: (paramsKey: string) => ['suppliers', 'page', paramsKey] as const,
  customers: ['customers'] as const,
  customersPage: (paramsKey: string) => ['customers', 'page', paramsKey] as const,
  posCustomers: ['pos', 'customers'] as const,
  posBranches: ['pos', 'branches'] as const,
  posLocations: ['pos', 'locations'] as const,
  posSettings: ['pos', 'settings'] as const,
  posHeldDrafts: ['pos', 'held-drafts'] as const,
  sales: ['sales'] as const,
  salesPage: (paramsKey: string) => ['sales', 'page', paramsKey] as const,
  saleDetail: (saleId: string) => ['sale-detail', saleId] as const,
  purchases: ['purchases'] as const,
  purchasesPage: (paramsKey: string) => ['purchases', 'page', paramsKey] as const,
  purchaseDetail: (purchaseId: string) => ['purchase-detail', purchaseId] as const,
  settings: ['settings'] as const,
  settingsUsers: ['settings-users'] as const,
  settingsUsersPage: (paramsKey: string) => ['settings-users', 'page', paramsKey] as const,
  adminDiagnostics: ['admin-diagnostics'] as const,
  adminMaintenance: ['admin-maintenance'] as const,
  adminLaunch: ['admin-launch'] as const,
  adminUat: ['admin-uat'] as const,
  adminOperational: ['admin-operational'] as const,
  adminSupport: ['admin-support'] as const,
  backupSnapshots: ['backup-snapshots'] as const,
  branches: ['branches'] as const,
  locations: ['locations'] as const,
  settingsLocations: ['settings-locations'] as const,
  inventoryReport: ['inventory-report'] as const,
  reportInventoryPage: (paramsKey: string) => ['inventory-report', 'page', paramsKey] as const,
  stockTransfers: ['stock-transfers'] as const,
  stockTransfersPage: (paramsKey: string) => ['stock-transfers', 'page', paramsKey] as const,
  stockCountSessions: ['stock-count-sessions'] as const,
  stockCountSessionsPage: (paramsKey: string) => ['stock-count-sessions', 'page', paramsKey] as const,
  damagedStock: ['damaged-stock'] as const,
  damagedStockPage: (paramsKey: string) => ['damaged-stock', 'page', paramsKey] as const,
  stockMovements: ['stock-movements'] as const,
  stockMovementsPage: (paramsKey: string) => ['stock-movements', 'page', paramsKey] as const,
  customerBalances: ['customer-balances'] as const,
  customerBalancesPage: (paramsKey: string) => ['customer-balances', 'page', paramsKey] as const,
  supplierBalances: ['supplier-balances'] as const,
  supplierBalancesPage: (paramsKey: string) => ['supplier-balances', 'page', paramsKey] as const,
  reportsSummary: (from: string, to: string) => ['reports-summary', from, to] as const,
  customerLedger: (customerId: string) => ['customer-ledger', customerId] as const,
  customerLedgerPage: (customerId: string, paramsKey: string) => ['customer-ledger', customerId, 'page', paramsKey] as const,
  supplierLedger: (supplierId: string) => ['supplier-ledger', supplierId] as const,
  supplierLedgerPage: (supplierId: string, paramsKey: string) => ['supplier-ledger', supplierId, 'page', paramsKey] as const,
  returns: ['returns'] as const,
  returnsPage: (paramsKey: string) => ['returns', 'page', paramsKey] as const,
  treasury: ['treasury'] as const,
  treasuryPage: (paramsKey: string) => ['treasury', 'page', paramsKey] as const,
  expenses: ['expenses'] as const,
  expensesPage: (paramsKey: string) => ['expenses', 'page', paramsKey] as const,
  services: ['services'] as const,
  servicesPage: (paramsKey: string) => ['services', 'page', paramsKey] as const,
  auditLogs: ['audit-logs'] as const,
  auditLogsPage: (paramsKey: string) => ['audit-logs', 'page', paramsKey] as const,
  cashierShifts: ['cashier-shifts'] as const,
  cashierShiftsPage: (paramsKey: string) => ['cashier-shifts', 'page', paramsKey] as const,
  systemHealth: ['system', 'health'] as const,
  pricingRuns: ['pricing', 'runs'] as const,
  pricingRules: ['pricing', 'rules'] as const
};
