function buildAuthRouteContext(runtime, services) {
  return {
    app: runtime.app,
    db: services.db,
    config: runtime.config,
    authMiddleware: services.authMiddleware,
    adminOnly: services.adminOnly,
    requireAnyPermission: runtime.requireAnyPermission,
    superAdminOnly: services.superAdminOnly,
    requirePermission: runtime.requirePermission,
    loginRateLimit: runtime.rateLimiters.loginRateLimit,
    login: services.login,
    createSession: services.createSession,
    destroySession: services.destroySession,
    setNoStore: runtime.setNoStore,
    sessionCookieOptions: runtime.sessionCookieOptions,
    addAuditLog: services.supporting.addAuditLog,
    addSecurityAudit: services.supporting.addSecurityAudit,
    ensureDefaultUsers: services.bootstrapStateService.ensureDefaultUsers,
    getSetting: services.supporting.getSetting,
  };
}

function buildSystemRouteContext(runtime, services) {
  return {
    app: runtime.app,
    authMiddleware: services.authMiddleware,
    adminOnly: services.adminOnly,
    superAdminOnly: services.superAdminOnly,
    requirePermission: runtime.requirePermission,
    requireAnyPermission: runtime.requireAnyPermission,
    setNoStore: runtime.setNoStore,
    listSessions: services.listSessions,
    revokeSessionForUser: services.revokeSessionForUser,
    revokeOtherSessions: services.revokeOtherSessions,
    changePassword: services.changePassword,
    validatePasswordChangePayload: services.validatePasswordChangePayload,
    sessionCookieOptions: runtime.sessionCookieOptions,
    stateWithUsers: services.stateStoreService.stateWithUsers,
    saveState: services.stateStoreService.saveState,
    allowLegacyStateWrite: runtime.config.allowLegacyStateWrite,
    defaultUsersState: services.authDomain.defaultUsersState,
    createManagedUser: services.authDomain.createManagedUser,
    updateManagedUser: services.authDomain.updateManagedUser,
    deleteManagedUser: services.authDomain.deleteManagedUser,
    unlockManagedUser: services.authDomain.unlockManagedUser,
    validateUsersPayload: services.validateUsersPayload,
    syncUsers: services.authDomain.syncUsers,
    getSettings: services.settingsDomain.getSystemSettings,
    saveSettings: services.settingsDomain.saveSystemSettings,
    listBranches: services.relationalReadModels.relationalBranches,
    createBranch: services.settingsDomain.createBranchRecord,
    updateBranch: services.settingsDomain.updateBranchRecord,
    deleteBranch: services.settingsDomain.deleteBranchRecord,
    listLocations: services.relationalReadModels.relationalLocations,
    createLocation: services.settingsDomain.createLocationRecord,
    updateLocation: services.settingsDomain.updateLocationRecord,
    deleteLocation: services.settingsDomain.deleteLocationRecord,
    listServices: services.relationalReadModels.relationalServices,
    createService: services.settingsDomain.createServiceRecord,
    updateService: services.settingsDomain.updateServiceRecord,
    deleteService: services.settingsDomain.deleteServiceRecord,
    buildRelationalBackupPayload: services.backupPayloadService.buildRelationalBackupPayload,
    backupDownloadRateLimit: runtime.rateLimiters.backupDownloadRateLimit,
    backupVerifyRateLimit: runtime.rateLimiters.backupVerifyRateLimit,
    verifyBackupPayload: services.diagnostics.verifyBackupPayload,
    restoreRateLimit: runtime.rateLimiters.restoreRateLimit,
    backupRestoreService: services.backupRestoreService,
    addAuditLog: services.supporting.addAuditLog,
    addSecurityAudit: services.supporting.addSecurityAudit,
    config: runtime.config,
    db: services.db,
    normalizeIncomingProduct: services.domainNormalizers.normalizeIncomingProduct,
    normalizeCustomer: services.domainNormalizers.normalizeCustomer,
    normalizeSupplier: services.domainNormalizers.normalizeSupplier,
    replaceProductRelations: services.domainNormalizers.replaceProductRelations,
    relationalProducts: services.relationalReadModels.relationalProducts,
    relationalCustomers: services.relationalReadModels.relationalCustomers,
    relationalSuppliers: services.relationalReadModels.relationalSuppliers,
    relationalCategories: services.relationalReadModels.relationalCategories,
    relationalStockMovements: services.relationalReadModels.relationalStockMovements,
    persistRelationalState: services.supporting.persistRelationalState,
    backupSnapshotStore: services.backupSnapshotStore,
  };
}

module.exports = { buildAuthRouteContext, buildSystemRouteContext };
