function buildCatalogRouteContext(runtime, services) {
  return {
    app: runtime.app,
    db: services.db,
    authMiddleware: services.authMiddleware,
    requirePermission: runtime.requirePermission,
    normalizeCategory: services.domainNormalizers.normalizeCategory,
    normalizeSupplier: services.domainNormalizers.normalizeSupplier,
    normalizeCustomer: services.domainNormalizers.normalizeCustomer,
    normalizeIncomingProduct: services.domainNormalizers.normalizeIncomingProduct,
    relationalCategories: services.relationalReadModels.relationalCategories,
    relationalSuppliers: services.relationalReadModels.relationalSuppliers,
    relationalCustomers: services.relationalReadModels.relationalCustomers,
    relationalProducts: services.relationalReadModels.relationalProducts,
    relationalStockMovements: services.relationalReadModels.relationalStockMovements,
    relationalAuditLogs: services.relationalReadModels.relationalAuditLogs,
    replaceProductRelations: services.domainNormalizers.replaceProductRelations,
    persistRelationalState: services.supporting.persistRelationalState,
    inventoryAdjustmentRateLimit: runtime.rateLimiters.inventoryAdjustmentRateLimit,
    assertManagerPin: services.supporting.assertManagerPin,
    normalizeInventoryAdjustment: services.domainNormalizers.normalizeInventoryAdjustment,
    addAuditLog: services.supporting.addAuditLog,
    userHasPermission: runtime.userHasPermission,
  };
}

function buildInventoryRouteContext(runtime, services) {
  return {
    app: runtime.app,
    db: services.db,
    authMiddleware: services.authMiddleware,
    requirePermission: runtime.requirePermission,
    userHasPermission: runtime.userHasPermission,
    assertManagerPin: services.supporting.assertManagerPin,
    normalizeInventoryAdjustment: services.domainNormalizers.normalizeInventoryAdjustment,
    relationalStockTransfers: services.relationalReadModels.relationalStockTransfers,
    relationalStockMovements: services.relationalReadModels.relationalStockMovements,
    relationalStockCountSessions: services.relationalReadModels.relationalStockCountSessions,
    relationalDamagedStockRecords: services.relationalReadModels.relationalDamagedStockRecords,
    relationalProducts: services.relationalReadModels.relationalProducts,
    addAuditLog: services.supporting.addAuditLog,
    persistRelationalState: services.supporting.persistRelationalState,
    backupSnapshotStore: services.backupSnapshotStore,
    config: runtime.config,
  };
}

function buildTransactionRouteContext(runtime, services) {
  return {
    app: runtime.app,
    db: services.db,
    authMiddleware: services.authMiddleware,
    requirePermission: runtime.requirePermission,
    requireAnyPermission: runtime.requireAnyPermission,
    normalizeIncomingSale: services.domainNormalizers.normalizeIncomingSale,
    normalizeIncomingPurchase: services.domainNormalizers.normalizeIncomingPurchase,
    createSaleRecord: services.transactionService.createSaleRecord,
    cancelSaleRecord: services.transactionMutationService.cancelSaleRecord,
    updateSaleRecord: services.transactionMutationService.updateSaleRecord,
    createCustomerPayment: services.transactionService.createCustomerPayment,
    createPurchaseRecord: services.transactionService.createPurchaseRecord,
    cancelPurchaseRecord: services.transactionMutationService.cancelPurchaseRecord,
    updatePurchaseRecord: services.transactionMutationService.updatePurchaseRecord,
    createExpenseRecord: services.transactionService.createExpenseRecord,
    createSupplierPaymentRecord: services.transactionService.createSupplierPaymentRecord,
    createReturnRecord: services.transactionService.createReturnRecord,
    listHeldSaleDrafts: services.transactionService.listHeldSaleDrafts,
    saveHeldSaleDraft: services.transactionService.saveHeldSaleDraft,
    deleteHeldSaleDraft: services.transactionService.deleteHeldSaleDraft,
    clearHeldSaleDrafts: services.transactionService.clearHeldSaleDrafts,
    relationalSales: services.relationalReadModels.relationalSales,
    relationalProducts: services.relationalReadModels.relationalProducts,
    relationalCustomers: services.relationalReadModels.relationalCustomers,
    relationalTreasury: services.relationalReadModels.relationalTreasury,
    relationalPurchases: services.relationalReadModels.relationalPurchases,
    relationalSuppliers: services.relationalReadModels.relationalSuppliers,
    relationalCashierShifts: services.relationalReadModels.relationalCashierShifts,
    relationalExpenses: services.relationalReadModels.relationalExpenses,
    relationalSupplierPayments: services.relationalReadModels.relationalSupplierPayments,
    relationalReturns: services.relationalReadModels.relationalReturns,
    addAuditLog: services.supporting.addAuditLog,
    addTreasuryTransaction: services.supporting.addTreasuryTransaction,
    computeShiftExpectedCash: services.supporting.computeShiftExpectedCash,
    makeDocNo: services.supporting.makeDocNo,
    resolveBranchLocationScope: services.supporting.resolveBranchLocationScope,
    assertManagerPin: services.supporting.assertManagerPin,
  };
}

module.exports = { buildCatalogRouteContext, buildInventoryRouteContext, buildTransactionRouteContext };
