/**
 * Universal Smart BOQ PDF Parser Engine
 * ----------------------------------------------------
 * High-precision, zero-failure PDF ingestion engine designed for real-world
 * contracting & engineering bills of quantities (BOQ / SOV).
 *
 * Key Capabilities:
 * 1. Native In-Browser/In-System Extraction via pdfjs-dist (ESM & Worker-safe).
 * 2. Multi-Page Continuous Parsing (merges tables seamlessly across 100+ pages).
 * 3. Spatial Line Clustering (adaptive tolerance clustering by vertical coordinate).
 * 4. Bilingual Dynamic Column Header Detection (RTL Arabic & LTR English).
 * 5. Continuous Contiguous Column Boundary Slicing (zero gap between columns).
 * 6. Multi-Line Item Specification Stitching (merges wrapped description rows).
 * 7. Division / Section Heading Detection & Classification (CSI / Arabic).
 * 8. Grand Total & Summary Row Filtering (prevents totals skewing data).
 * 9. Eastern Arabic Numeral Normalization & Canonical Unit Translation.
 * 10. Tender Ready Zero-Blocker Model (supports unpriced items).
 */

import * as pdfjsLib from 'pdfjs-dist';
import {
  ColumnMapping,
  ParsedBoqItemResult,
  WorkbookParseResult,
  COLUMN_ALIASES,
  testCellMatches,
  extractBoqRows,
  normalizeArabicDigits,
  isSummaryOrTotalRow,
  isSectionHeaderRow,
} from './boqExcelParser';

// ----------------------------------------------------------------------
// 1. Worker Setup & Environment Guard
// ----------------------------------------------------------------------

let workerInitialized = false;

export function ensurePdfWorker(): void {
  if (workerInitialized || typeof window === 'undefined') return;

  try {
    if (!pdfjsLib.GlobalWorkerOptions.workerSrc) {
      // In Vite build/dev, resolve worker bundle URL
      pdfjsLib.GlobalWorkerOptions.workerSrc = new URL(
        'pdfjs-dist/build/pdf.worker.min.mjs',
        import.meta.url
      ).toString();
    }
  } catch {
    try {
      pdfjsLib.GlobalWorkerOptions.workerSrc = `https://unpkg.com/pdfjs-dist@${pdfjsLib.version}/build/pdf.worker.min.mjs`;
    } catch {
      // Allow main thread execution if worker cannot be instantiated
    }
  }
  workerInitialized = true;
}

// ----------------------------------------------------------------------
// 2. Types & Spatial Models
// ----------------------------------------------------------------------

export interface PdfTextItem {
  str: string;
  x: number; // left
  y: number; // top (from top of page)
  width: number;
  height: number;
  page: number;
}

export interface PdfLine {
  page: number;
  y: number;
  items: PdfTextItem[];
}

export interface DetectedColumnBoundary {
  field: keyof ColumnMapping;
  headerText: string;
  xCenter: number;
  minX: number;
  maxX: number;
}

export interface PdfParseResult extends WorkbookParseResult {
  rawMatrix: string[][];
}

// ----------------------------------------------------------------------
// 3. Arabic & Text Normalization Helpers
// ----------------------------------------------------------------------

/**
 * Normalizes unicode representation forms and corrects reversed visual Arabic
 * generated by legacy PDF engines (AutoCAD / Crystal Reports).
 */
export function fixVisualArabicIfNeeded(text: string): string {
  if (!text) return '';
  const normalized = normalizeArabicDigits(text.normalize('NFKC'));

  const words = normalized.trim().split(/\s+/);
  let reversedSignals = 0;
  let normalSignals = 0;

  for (const word of words) {
    if (word.length >= 2) {
      // Standard Arabic prefixes and suffixes
      if (word.startsWith('ال') || word.startsWith('وال') || word.startsWith('بال')) normalSignals++;
      if (word.endsWith('لا') || word.endsWith('لاو')) reversedSignals++;
      // Terminal letters appearing at the beginning indicates reverse order
      if (word.startsWith('ة') || word.startsWith('ى')) reversedSignals++;
      if (word.endsWith('ة') || word.endsWith('ى')) normalSignals++;
    }
  }

  // If reversed signals strongly dominate, reverse characters within Arabic words
  if (reversedSignals > 1 && reversedSignals > normalSignals) {
    return words
      .map((w) => (/[\u0600-\u06FF]/.test(w) ? w.split('').reverse().join('') : w))
      .reverse()
      .join(' ');
  }

  return normalized;
}

// ----------------------------------------------------------------------
// 4. Line Clustering per Page
// ----------------------------------------------------------------------

export function clusterItemsIntoLines(items: PdfTextItem[]): PdfLine[] {
  if (items.length === 0) return [];

  // Sort items by Y position ascending (top to bottom)
  const sorted = [...items].sort((a, b) => a.y - b.y);
  const lines: PdfLine[] = [];

  for (const item of sorted) {
    // Dynamic tolerance: items on the same line typically have delta Y <= 4-6px
    const tolerance = Math.max(4, (item.height || 10) * 0.45);
    let matchedLine = lines.find((l) => l.page === item.page && Math.abs(l.y - item.y) <= tolerance);

    if (!matchedLine) {
      matchedLine = {
        page: item.page,
        y: item.y,
        items: [],
      };
      lines.push(matchedLine);
    } else {
      // Update line Y with running average to prevent drift
      matchedLine.y = (matchedLine.y * matchedLine.items.length + item.y) / (matchedLine.items.length + 1);
    }

    matchedLine.items.push(item);
  }

  // Sort lines by page then Y ascending
  lines.sort((a, b) => (a.page !== b.page ? a.page - b.page : a.y - b.y));

  // Sort items within each line by X ascending (left to right)
  for (const line of lines) {
    line.items.sort((a, b) => a.x - b.x);
  }

  return lines;
}

// ----------------------------------------------------------------------
// 5. Column Header Detection & Boundary Slicing
// ----------------------------------------------------------------------

interface ScoredCandidateHeader {
  lineIndex: number;
  score: number;
  detectedColumns: { field: keyof ColumnMapping; item: PdfTextItem; headerText: string }[];
}

export function detectPdfTableHeaders(lines: PdfLine[]): {
  headerLineIdx: number;
  columnBoundaries: DetectedColumnBoundary[];
  mapping: ColumnMapping;
  headers: string[];
} {
  let bestCandidate: ScoredCandidateHeader | null = null;

  // Scan early lines (first 40 lines) to find the table header row
  const scanLimit = Math.min(lines.length, 40);

  for (let idx = 0; idx < scanLimit; idx++) {
    const line = lines[idx];
    if (line.items.length < 2) continue;

    let score = 0;
    const detected: { field: keyof ColumnMapping; item: PdfTextItem; headerText: string }[] = [];
    const usedFields = new Set<keyof ColumnMapping>();

    for (const it of line.items) {
      const clean = fixVisualArabicIfNeeded(it.str).trim();
      if (!clean) continue;

      // Match against aliases
      if (!usedFields.has('descriptionCol') && testCellMatches(clean, COLUMN_ALIASES.description)) {
        detected.push({ field: 'descriptionCol', item: it, headerText: clean });
        usedFields.add('descriptionCol');
        score += 6;
      } else if (!usedFields.has('qtyCol') && testCellMatches(clean, COLUMN_ALIASES.quantity)) {
        detected.push({ field: 'qtyCol', item: it, headerText: clean });
        usedFields.add('qtyCol');
        score += 5;
      } else if (
        !usedFields.has('unitPriceCol') &&
        testCellMatches(clean, COLUMN_ALIASES.unitPrice) &&
        !testCellMatches(clean, COLUMN_ALIASES.totalPrice)
      ) {
        detected.push({ field: 'unitPriceCol', item: it, headerText: clean });
        usedFields.add('unitPriceCol');
        score += 5;
      } else if (!usedFields.has('unitCol') && testCellMatches(clean, COLUMN_ALIASES.unit)) {
        detected.push({ field: 'unitCol', item: it, headerText: clean });
        usedFields.add('unitCol');
        score += 4;
      } else if (!usedFields.has('itemCodeCol') && testCellMatches(clean, COLUMN_ALIASES.itemCode)) {
        detected.push({ field: 'itemCodeCol', item: it, headerText: clean });
        usedFields.add('itemCodeCol');
        score += 3;
      } else if (!usedFields.has('totalPriceCol') && testCellMatches(clean, COLUMN_ALIASES.totalPrice)) {
        detected.push({ field: 'totalPriceCol', item: it, headerText: clean });
        usedFields.add('totalPriceCol');
        score += 3;
      } else if (!usedFields.has('estimatedCostCol') && testCellMatches(clean, COLUMN_ALIASES.estimatedCost)) {
        detected.push({ field: 'estimatedCostCol', item: it, headerText: clean });
        usedFields.add('estimatedCostCol');
        score += 2;
      } else if (!usedFields.has('categoryCol') && testCellMatches(clean, COLUMN_ALIASES.category)) {
        detected.push({ field: 'categoryCol', item: it, headerText: clean });
        usedFields.add('categoryCol');
        score += 2;
      } else if (!usedFields.has('notesCol') && testCellMatches(clean, COLUMN_ALIASES.notes)) {
        detected.push({ field: 'notesCol', item: it, headerText: clean });
        usedFields.add('notesCol');
        score += 1;
      }
    }

    if (score >= 8 && (!bestCandidate || score > bestCandidate.score)) {
      bestCandidate = { lineIndex: idx, score, detectedColumns: detected };
    }
  }

  // Fallback: If no standard header line found, construct reasonable default intervals
  if (!bestCandidate || bestCandidate.detectedColumns.length < 2) {
    const defaultHeaders = [
      'رقم البند (Item Code)',
      'بيان الأعمال والمواصفات (Description)',
      'الوحدة (Unit)',
      'الكمية (Qty)',
      'الفئة (Rate)',
      'الإجمالي (Total)',
    ];
    const defaultMapping: ColumnMapping = {
      itemCodeCol: 0,
      descriptionCol: 1,
      unitCol: 2,
      qtyCol: 3,
      unitPriceCol: 4,
      totalPriceCol: 5,
      categoryCol: -1,
      estimatedCostCol: -1,
      notesCol: -1,
    };
    return {
      headerLineIdx: -1,
      columnBoundaries: [],
      mapping: defaultMapping,
      headers: defaultHeaders,
    };
  }

  // Sort detected columns by their center X ascending (left to right)
  const sortedColumns = bestCandidate.detectedColumns
    .map((c) => ({
      field: c.field,
      headerText: c.headerText,
      x: c.item.x,
      width: c.item.width || 20,
      xCenter: c.item.x + (c.item.width || 20) / 2,
    }))
    .sort((a, b) => a.xCenter - b.xCenter);

  // Compute non-overlapping contiguous boundaries between adjacent columns
  // Description column is wide, so narrow columns (itemCode, unit, etc.) use their outer margins
  const descIdx = sortedColumns.findIndex((c) => c.field === 'descriptionCol');
  const columnBoundaries: DetectedColumnBoundary[] = [];

  for (let i = 0; i < sortedColumns.length; i++) {
    const cur = sortedColumns[i];
    let minX = 0;
    let maxX = 999999;

    if (descIdx !== -1) {
      if (i < descIdx) {
        minX = i === 0 ? 0 : (sortedColumns[i - 1].xCenter + cur.xCenter) / 2;
        if (i === descIdx - 1) {
          maxX = Math.max(cur.x + cur.width + 12, (cur.xCenter + sortedColumns[descIdx].xCenter) / 2);
        } else {
          maxX = (cur.xCenter + sortedColumns[i + 1].xCenter) / 2;
        }
      } else if (i === descIdx) {
        minX = i === 0 ? 0 : columnBoundaries[i - 1].maxX;
        if (i < sortedColumns.length - 1) {
          const next = sortedColumns[i + 1];
          // Protect wide description: right boundary extends close to the narrow column's left edge
          maxX = Math.max(cur.x + cur.width, next.x - 12);
        } else {
          maxX = 999999;
        }
      } else {
        // i > descIdx (e.g. itemCode on the right in RTL)
        minX = columnBoundaries[i - 1].maxX;
        maxX = i === sortedColumns.length - 1 ? 999999 : (cur.xCenter + sortedColumns[i + 1].xCenter) / 2;
      }
    } else {
      minX = i === 0 ? 0 : (sortedColumns[i - 1].xCenter + cur.xCenter) / 2;
      maxX = i === sortedColumns.length - 1 ? 999999 : (cur.xCenter + sortedColumns[i + 1].xCenter) / 2;
    }

    columnBoundaries.push({
      field: cur.field,
      headerText: cur.headerText,
      xCenter: cur.xCenter,
      minX,
      maxX,
    });
  }

  // Build column mapping indices based on left-to-right order in matrix
  const mapping: ColumnMapping = {
    itemCodeCol: -1,
    descriptionCol: -1,
    categoryCol: -1,
    unitCol: -1,
    qtyCol: -1,
    unitPriceCol: -1,
    estimatedCostCol: -1,
    notesCol: -1,
    totalPriceCol: -1,
  };

  const headers: string[] = [];
  for (let colIdx = 0; colIdx < columnBoundaries.length; colIdx++) {
    const col = columnBoundaries[colIdx];
    mapping[col.field] = colIdx;
    headers.push(col.headerText);
  }

  return {
    headerLineIdx: bestCandidate.lineIndex,
    columnBoundaries,
    mapping,
    headers,
  };
}

// ----------------------------------------------------------------------
// 6. Project Line Items into Columns & Multi-line Item Assembly
// ----------------------------------------------------------------------

interface AssembledPdfRow {
  itemCode: string;
  description: string;
  category: string;
  unit: string;
  quantity: string;
  unitPrice: string;
  estimatedCost: string;
  notes: string;
  totalPrice: string;
}

/**
 * Checks if a line is a repeated table header on later pages
 */
function isRepeatedHeaderLine(line: PdfLine, boundaries: DetectedColumnBoundary[]): boolean {
  if (boundaries.length < 2) return false;
  let matches = 0;
  for (const it of line.items) {
    const clean = fixVisualArabicIfNeeded(it.str).trim();
    if (
      boundaries.some((b) =>
        testCellMatches(
          clean,
          COLUMN_ALIASES[b.field.replace('Col', '') as keyof typeof COLUMN_ALIASES] || []
        )
      )
    ) {
      matches++;
    }
  }
  return matches >= Math.min(3, boundaries.length);
}

/**
 * Checks if a line is a page footer / page number (e.g. "Page 1 of 5" or "صفحة ١")
 */
function isPageFooterLine(line: PdfLine): boolean {
  const lineText = line.items.map((i) => i.str).join(' ').trim().toLowerCase();
  if (/^(page|صفحة)\s+[\d٠-٩]+(\s+(of|من|\/)\s+[\d٠-٩]+)?$/i.test(lineText)) return true;
  if (/^[\d٠-٩]+\s*\/\s*[\d٠-٩]+$/.test(lineText)) return true;
  return false;
}

export function assemblePdfBoqRows(
  lines: PdfLine[],
  headerLineIdx: number,
  boundaries: DetectedColumnBoundary[]
): AssembledPdfRow[] {
  const assembledRows: AssembledPdfRow[] = [];
  let currentRow: AssembledPdfRow | null = null;
  let activeSectionPrefix = '';

  const startIndex = headerLineIdx >= 0 ? headerLineIdx + 1 : 0;

  for (let i = startIndex; i < lines.length; i++) {
    const line = lines[i];
    if (!line.items || line.items.length === 0) continue;

    // Skip repeated headers and page footers
    if (isRepeatedHeaderLine(line, boundaries)) continue;
    if (isPageFooterLine(line)) continue;

    // Project each item in this line into its matching column boundary
    const lineCells: Record<string, string[]> = {};
    for (const boundary of boundaries) {
      lineCells[boundary.field] = [];
    }

    for (const item of line.items) {
      const text = fixVisualArabicIfNeeded(item.str).trim();
      if (!text) continue;

      const itemCenter = item.x + (item.width || 10) / 2;
      const matchedBoundary = boundaries.find(
        (b) => itemCenter >= b.minX && itemCenter < b.maxX
      );

      if (matchedBoundary) {
        lineCells[matchedBoundary.field].push(text);
      } else if (boundaries.length > 0) {
        // Fallback: put in the closest boundary
        let closest = boundaries[0];
        let minDist = Math.abs(itemCenter - closest.xCenter);
        for (let bIdx = 1; bIdx < boundaries.length; bIdx++) {
          const dist = Math.abs(itemCenter - boundaries[bIdx].xCenter);
          if (dist < minDist) {
            minDist = dist;
            closest = boundaries[bIdx];
          }
        }
        lineCells[closest.field].push(text);
      }
    }

    const itemCode = (lineCells['itemCodeCol'] || []).join(' ').trim();
    let description = (lineCells['descriptionCol'] || []).join(' ').trim();
    const unit = (lineCells['unitCol'] || []).join(' ').trim();
    const qty = (lineCells['qtyCol'] || []).join(' ').trim();
    const unitPrice = (lineCells['unitPriceCol'] || []).join(' ').trim();
    const totalPrice = (lineCells['totalPriceCol'] || []).join(' ').trim();
    const category = (lineCells['categoryCol'] || []).join(' ').trim();
    const notes = (lineCells['notesCol'] || []).join(' ').trim();
    const estimatedCost = (lineCells['estimatedCostCol'] || []).join(' ').trim();

    // Check if this line has any meaningful content
    const hasAnyContent = Boolean(
      itemCode || description || unit || qty || unitPrice || totalPrice || notes
    );
    if (!hasAnyContent) continue;

    // If line matches a summary or total row, conclude previous item and skip summary row
    if (isSummaryOrTotalRow(description) || isSummaryOrTotalRow(itemCode)) {
      if (currentRow) {
        assembledRows.push(currentRow);
        currentRow = null;
      }
      continue;
    }

    // Decision: Does this line begin a NEW BOQ item or is it a CONTINUATION of the previous item?
    const isSection = isSectionHeaderRow(description, 0, 0, unit);
    const hasNewItemCode = Boolean(itemCode);
    const hasQuantity = Boolean(qty && /[\d٠-٩]/.test(qty));
    const hasPrice = Boolean(unitPrice && /[\d٠-٩]/.test(unitPrice));
    const hasUnit = Boolean(unit && unit.length <= 15);

    // If there is no current row, start a new one
    if (!currentRow) {
      if (isSection || (!hasQuantity && !hasPrice && hasNewItemCode && !hasUnit)) {
        activeSectionPrefix = description;
      }
      currentRow = {
        itemCode,
        description,
        category,
        unit,
        quantity: qty,
        unitPrice,
        estimatedCost,
        notes,
        totalPrice,
      };
      continue;
    }

    // Check if currentRow is an unpriced header / preamble (no qty, no price)
    const currentRowIsUnpricedHeader =
      !currentRow.quantity &&
      !currentRow.unitPrice &&
      !currentRow.totalPrice;

    // A row is considered a new item if it has an itemCode, or has both qty & unit, or has a distinct numeric price, or is a section header
    const isNewItem = hasNewItemCode || (hasQuantity && hasUnit) || (hasPrice && hasQuantity) || isSection;

    if (isNewItem) {
      if (isSection) {
        activeSectionPrefix = description;
      }

      // If previous row was an unpriced section heading (no qty and no price) and current row has a price/qty or sub-code:
      if (currentRowIsUnpricedHeader && (hasQuantity || hasPrice || (hasNewItemCode && itemCode.includes('-')))) {
        // Use previous header as section prefix without creating an empty orphan row
        activeSectionPrefix = currentRow.description;
        if (activeSectionPrefix && !description.includes(activeSectionPrefix)) {
          description = `${activeSectionPrefix} - ${description}`;
        }
        currentRow = {
          itemCode,
          description,
          category,
          unit,
          quantity: qty,
          unitPrice,
          estimatedCost,
          notes,
          totalPrice,
        };
      } else {
        // Push previous valid row
        assembledRows.push(currentRow);

        if (activeSectionPrefix && !isSection && !description.includes(activeSectionPrefix) && (hasQuantity || hasPrice)) {
          description = `${activeSectionPrefix} - ${description}`;
        }

        currentRow = {
          itemCode,
          description,
          category,
          unit,
          quantity: qty,
          unitPrice,
          estimatedCost,
          notes,
          totalPrice,
        };
      }
    } else {
      // Continuation line: Append text to active item's description / notes
      if (description) {
        currentRow.description = currentRow.description
          ? `${currentRow.description} ${description}`
          : description;
      }
      if (notes) {
        currentRow.notes = currentRow.notes
          ? `${currentRow.notes} ${notes}`
          : notes;
      }
      if (unit && !currentRow.unit) {
        currentRow.unit = unit;
      }
      if (qty && !currentRow.quantity) {
        currentRow.quantity = qty;
      }
      if (unitPrice && !currentRow.unitPrice) {
        currentRow.unitPrice = unitPrice;
      }
      if (totalPrice && !currentRow.totalPrice) {
        currentRow.totalPrice = totalPrice;
      }
    }
  }

  // Push final active item
  if (currentRow) {
    assembledRows.push(currentRow);
  }

  return assembledRows;
}

// ----------------------------------------------------------------------
// 7. Convert Assembled Rows to 2D Matrix for Unified Business Processing
// ----------------------------------------------------------------------

export function buildMatrixFromAssembledRows(
  assembledRows: AssembledPdfRow[],
  _columnBoundaries: DetectedColumnBoundary[],
  mapping: ColumnMapping,
  headerTexts: string[]
): string[][] {
  const matrix: string[][] = [];

  // Header row at index 0
  matrix.push(headerTexts);

  // Field keys ordered by column index
  const numCols =
    Math.max(
      headerTexts.length,
      ...Object.values(mapping).filter((idx) => typeof idx === 'number' && idx >= 0)
    ) + 1;

  for (const row of assembledRows) {
    const rowCells = new Array(numCols).fill('');

    if (mapping.itemCodeCol >= 0) rowCells[mapping.itemCodeCol] = row.itemCode;
    if (mapping.descriptionCol >= 0) rowCells[mapping.descriptionCol] = row.description;
    if (mapping.categoryCol >= 0) rowCells[mapping.categoryCol] = row.category;
    if (mapping.unitCol >= 0) rowCells[mapping.unitCol] = row.unit;
    if (mapping.qtyCol >= 0) rowCells[mapping.qtyCol] = row.quantity;
    if (mapping.unitPriceCol >= 0) rowCells[mapping.unitPriceCol] = row.unitPrice;
    if (mapping.estimatedCostCol >= 0) rowCells[mapping.estimatedCostCol] = row.estimatedCost;
    if (mapping.notesCol >= 0) rowCells[mapping.notesCol] = row.notes;
    if (mapping.totalPriceCol >= 0) rowCells[mapping.totalPriceCol] = row.totalPrice;

    matrix.push(rowCells);
  }

  return matrix;
}

// ----------------------------------------------------------------------
// 8. Main Entrypoint: parseBoqPdf
// ----------------------------------------------------------------------

export async function parseBoqPdf(
  fileOrBuffer: File | ArrayBuffer | Uint8Array,
  customMapping?: ColumnMapping
): Promise<PdfParseResult> {
  ensurePdfWorker();

  let data: Uint8Array;
  if (fileOrBuffer instanceof Uint8Array) {
    data = fileOrBuffer;
  } else if (fileOrBuffer instanceof ArrayBuffer) {
    data = new Uint8Array(fileOrBuffer);
  } else {
    const buf = await fileOrBuffer.arrayBuffer();
    data = new Uint8Array(buf);
  }

  // Load PDF document
  const loadingTask = pdfjsLib.getDocument({
    data,
    disableFontFace: false,
  });

  const pdfDoc = await loadingTask.promise;
  const numPages = pdfDoc.numPages;

  if (numPages === 0) {
    throw new Error('ملف الـ PDF لا يحتوي على أي صفحات.');
  }

  // Harvest all text items with viewport coordinates
  const allItems: PdfTextItem[] = [];

  for (let pageNum = 1; pageNum <= numPages; pageNum++) {
    const page = await pdfDoc.getPage(pageNum);
    const viewport = page.getViewport({ scale: 1.0 });
    const textContent = await page.getTextContent();

    for (const rawItem of textContent.items) {
      if (!('str' in rawItem)) continue;
      const str = rawItem.str.trim();
      if (!str) continue;

      // Convert coordinates to screen viewport point (top-left origin)
      const [vx, vy] = viewport.convertToViewportPoint(
        rawItem.transform[4],
        rawItem.transform[5]
      );

      allItems.push({
        str,
        x: vx,
        y: vy,
        width: rawItem.width || 0,
        height: rawItem.height || 0,
        page: pageNum,
      });
    }
  }

  if (allItems.length === 0) {
    throw new Error(
      'لم يتم العثور على نصوص مقروءة في ملف الـ PDF. تأكد أن الملف ليس صورة ممسوحة ضوئياً (Scanned Image) بدون طبقة نصوص رقمية.'
    );
  }

  // Cluster items into lines
  const lines = clusterItemsIntoLines(allItems);

  // Detect table headers and column boundaries
  const { headerLineIdx, columnBoundaries, mapping: detectedMapping, headers } =
    detectPdfTableHeaders(lines);

  const effectiveMapping = customMapping || detectedMapping;

  // Assemble multi-line BOQ rows
  const assembledRows = assemblePdfBoqRows(lines, headerLineIdx, columnBoundaries);

  if (assembledRows.length === 0) {
    throw new Error('تعذر العثور على بنود كميات ومقايسة في جدول الـ PDF.');
  }

  // Build 2D string matrix
  const matrix = buildMatrixFromAssembledRows(
    assembledRows,
    columnBoundaries,
    effectiveMapping,
    headers
  );

  // Extract BOQ items using standard enterprise extractor
  const rows = extractBoqRows(matrix, 0, effectiveMapping);

  const validRows = rows.filter((r) => r.isValid);
  const unpricedCount = rows.filter((r) => r.status === 'unpriced' && !r.isSectionHeader).length;
  const zeroQtyCount = rows.filter((r) => r.status === 'zero_qty').length;
  const sectionHeaderCount = rows.filter((r) => r.isSectionHeader).length;
  const invalidCount = rows.filter((r) => !r.isValid && !r.isSectionHeader).length;

  const totalContractValue = validRows.reduce((sum, r) => sum + r.contractQty * r.unitPrice, 0);
  const totalEstimatedCost = validRows.reduce((sum, r) => sum + r.contractQty * r.estimatedUnitCost, 0);

  return {
    sheetNames: ['جدول الكميات (PDF BOQ)'],
    selectedSheet: 'جدول الكميات (PDF BOQ)',
    headerRowIndex: 0,
    headers,
    columnMapping: effectiveMapping,
    rows,
    validCount: validRows.length,
    unpricedCount,
    zeroQtyCount,
    sectionHeaderCount,
    invalidCount,
    totalContractValue,
    totalEstimatedCost,
    rawMatrix: matrix,
  };
}

// ----------------------------------------------------------------------
// 9. Re-extraction with Custom Mapping
// ----------------------------------------------------------------------

export function reExtractBoqPdfWithCustomMapping(
  rawMatrix: string[][],
  customMapping: ColumnMapping
): {
  rows: ParsedBoqItemResult[];
  validCount: number;
  unpricedCount: number;
  zeroQtyCount: number;
  sectionHeaderCount: number;
  invalidCount: number;
  totalContractValue: number;
  totalEstimatedCost: number;
} {
  const rows = extractBoqRows(rawMatrix, 0, customMapping);

  const validRows = rows.filter((r) => r.isValid);
  const unpricedCount = rows.filter((r) => r.status === 'unpriced' && !r.isSectionHeader).length;
  const zeroQtyCount = rows.filter((r) => r.status === 'zero_qty').length;
  const sectionHeaderCount = rows.filter((r) => r.isSectionHeader).length;
  const invalidCount = rows.filter((r) => !r.isValid && !r.isSectionHeader).length;

  const totalContractValue = validRows.reduce((sum, r) => sum + r.contractQty * r.unitPrice, 0);
  const totalEstimatedCost = validRows.reduce((sum, r) => sum + r.contractQty * r.estimatedUnitCost, 0);

  return {
    rows,
    validCount: validRows.length,
    unpricedCount,
    zeroQtyCount,
    sectionHeaderCount,
    invalidCount,
    totalContractValue,
    totalEstimatedCost,
  };
}
