"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.migration = void 0;
const kysely_1 = require("kysely");
exports.migration = {
    async up(db) {
        await (0, kysely_1.sql) `CREATE TABLE IF NOT EXISTS partner_contacts (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      tenant_id TEXT NOT NULL DEFAULT '',
      account_id TEXT NOT NULL DEFAULT '',
      partner_type TEXT NOT NULL,
      partner_id BIGINT NOT NULL,
      name TEXT NOT NULL,
      phone TEXT NOT NULL DEFAULT '',
      email TEXT NOT NULL DEFAULT '',
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )`.execute(db);
        await (0, kysely_1.sql) `CREATE TABLE IF NOT EXISTS partner_addresses (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      tenant_id TEXT NOT NULL DEFAULT '',
      account_id TEXT NOT NULL DEFAULT '',
      partner_type TEXT NOT NULL,
      partner_id BIGINT NOT NULL,
      label TEXT NOT NULL,
      city TEXT NOT NULL DEFAULT '',
      address_line TEXT NOT NULL DEFAULT '',
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )`.execute(db);
        await (0, kysely_1.sql) `CREATE TABLE IF NOT EXISTS cost_centers (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      tenant_id TEXT NOT NULL DEFAULT '',
      account_id TEXT NOT NULL DEFAULT '',
      code TEXT NOT NULL,
      name TEXT NOT NULL,
      is_active BOOLEAN NOT NULL DEFAULT TRUE,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      UNIQUE (tenant_id, code)
    )`.execute(db);
        await (0, kysely_1.sql) `CREATE TABLE IF NOT EXISTS projects (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      tenant_id TEXT NOT NULL DEFAULT '',
      account_id TEXT NOT NULL DEFAULT '',
      code TEXT NOT NULL,
      name TEXT NOT NULL,
      is_active BOOLEAN NOT NULL DEFAULT TRUE,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      UNIQUE (tenant_id, code)
    )`.execute(db);
        await (0, kysely_1.sql) `ALTER TABLE purchases ADD COLUMN IF NOT EXISTS required_date TIMESTAMPTZ NULL`.execute(db);
        await (0, kysely_1.sql) `ALTER TABLE purchases ADD COLUMN IF NOT EXISTS currency TEXT NOT NULL DEFAULT 'EGP'`.execute(db);
        await (0, kysely_1.sql) `ALTER TABLE purchases ADD COLUMN IF NOT EXISTS company_name TEXT NOT NULL DEFAULT ''`.execute(db);
        await (0, kysely_1.sql) `ALTER TABLE purchases ADD COLUMN IF NOT EXISTS contact_id BIGINT NULL REFERENCES partner_contacts(id) ON DELETE SET NULL`.execute(db);
        await (0, kysely_1.sql) `ALTER TABLE purchases ADD COLUMN IF NOT EXISTS shipping_address_id BIGINT NULL REFERENCES partner_addresses(id) ON DELETE SET NULL`.execute(db);
        await (0, kysely_1.sql) `ALTER TABLE purchases ADD COLUMN IF NOT EXISTS cost_center_id BIGINT NULL REFERENCES cost_centers(id) ON DELETE SET NULL`.execute(db);
        await (0, kysely_1.sql) `ALTER TABLE purchases ADD COLUMN IF NOT EXISTS project_id BIGINT NULL REFERENCES projects(id) ON DELETE SET NULL`.execute(db);
        await (0, kysely_1.sql) `ALTER TABLE purchases ADD COLUMN IF NOT EXISTS terms_template TEXT NOT NULL DEFAULT ''`.execute(db);
    },
    async down(db) {
        await (0, kysely_1.sql) `ALTER TABLE purchases DROP COLUMN IF EXISTS required_date`.execute(db);
        await (0, kysely_1.sql) `ALTER TABLE purchases DROP COLUMN IF EXISTS currency`.execute(db);
        await (0, kysely_1.sql) `ALTER TABLE purchases DROP COLUMN IF EXISTS company_name`.execute(db);
        await (0, kysely_1.sql) `ALTER TABLE purchases DROP COLUMN IF EXISTS contact_id`.execute(db);
        await (0, kysely_1.sql) `ALTER TABLE purchases DROP COLUMN IF EXISTS shipping_address_id`.execute(db);
        await (0, kysely_1.sql) `ALTER TABLE purchases DROP COLUMN IF EXISTS cost_center_id`.execute(db);
        await (0, kysely_1.sql) `ALTER TABLE purchases DROP COLUMN IF EXISTS project_id`.execute(db);
        await (0, kysely_1.sql) `ALTER TABLE purchases DROP COLUMN IF EXISTS terms_template`.execute(db);
        await (0, kysely_1.sql) `DROP TABLE IF EXISTS projects`.execute(db);
        await (0, kysely_1.sql) `DROP TABLE IF EXISTS cost_centers`.execute(db);
        await (0, kysely_1.sql) `DROP TABLE IF EXISTS partner_addresses`.execute(db);
        await (0, kysely_1.sql) `DROP TABLE IF EXISTS partner_contacts`.execute(db);
    }
};
//# sourceMappingURL=20260603000200_purchase_auxiliary_tables.js.map