import type { Dispatch, SetStateAction } from 'react';
import type { PaymentType, PaymentChannel, HeldPosDraft } from '@/features/pos/hooks/usePosWorkspace';
import type { PosItem, PosPriceType } from '@/features/pos/types/pos.types';
import type { Customer, Product, Sale, AppSettings } from '@/types/domain';
import type { CreatePosSaleInput } from '@/features/pos/contracts';
import { createPosWorkspaceAsyncActions } from '@/features/pos/hooks/pos-workspace-actions/createPosWorkspaceAsyncActions';
import { createPosWorkspaceBaseActions } from '@/features/pos/hooks/pos-workspace-actions/createPosWorkspaceBaseActions';
import { createPosWorkspaceReceiptActions } from '@/features/pos/hooks/pos-workspace-actions/createPosWorkspaceReceiptActions';

export interface PosWorkspaceActionParams {
  cart: PosItem[];
  setCart: Dispatch<SetStateAction<PosItem[]>>;
  customerId: string;
  setCustomerId: Dispatch<SetStateAction<string>>;
  discount: number;
  setDiscount: Dispatch<SetStateAction<number>>;
  cashAmount: number;
  setCashAmount: Dispatch<SetStateAction<number>>;
  cardAmount: number;
  setCardAmount: Dispatch<SetStateAction<number>>;
  paymentType: PaymentType;
  setPaymentType: Dispatch<SetStateAction<PaymentType>>;
  paymentChannel: PaymentChannel;
  setPaymentChannel: Dispatch<SetStateAction<PaymentChannel>>;
  note: string;
  setNote: Dispatch<SetStateAction<string>>;
  search: string;
  setSearch: Dispatch<SetStateAction<string>>;
  priceType: PosPriceType;
  setPriceType: Dispatch<SetStateAction<PosPriceType>>;
  branchId: string;
  setBranchId: Dispatch<SetStateAction<string>>;
  locationId: string;
  setLocationId: Dispatch<SetStateAction<string>>;
  quickAddCode: string;
  setQuickAddCode: Dispatch<SetStateAction<string>>;
  quickCustomerName: string;
  setQuickCustomerName: Dispatch<SetStateAction<string>>;
  quickCustomerPhone: string;
  setQuickCustomerPhone: Dispatch<SetStateAction<string>>;
  scannerMessage: string;
  setScannerMessage: Dispatch<SetStateAction<string>>;
  setSubmitMessage: Dispatch<SetStateAction<string>>;
  setLastAddedLineKey: Dispatch<SetStateAction<string>>;
  setRecentProductIds: Dispatch<SetStateAction<string[]>>;
  setLastSale: Dispatch<SetStateAction<Sale | null>>;
  lastSale: Sale | null;
  products: Product[];
  branches: Array<{ id: string | number }>;
  locations: Array<{ id: string | number }>;
  currentBranch: { id: string | number } | null;
  currentLocation: { id: string | number } | null;
  settings?: Partial<AppSettings> | null;
  totals: { discountValue: number; taxRate: number; pricesIncludeTax: boolean; total: number };
  paidAmount: number;
  hasOperationalSetup: boolean;
  hasCatalogReady: boolean;
  requiresCashierShift: boolean;
  ownOpenShift: { id: string | number } | null;
  hasCreditWithoutCustomer: boolean;
  hasZeroPriceLine: boolean;
  hasUnderpaidSale: boolean;
  heldDrafts: HeldPosDraft[];
  quickCustomerMutation: { mutateAsync: (payload: { name: string; phone: string; address: string; balance: number; type: Customer['type']; creditLimit: number }) => Promise<unknown> };
  createSale: { mutateAsync: (payload: CreatePosSaleInput) => Promise<unknown>; isError?: boolean; isPending?: boolean };
  saveHeldDraftMutation: { mutateAsync: (payload: unknown) => Promise<unknown> };
  deleteHeldDraftMutation: { mutateAsync: (draftId: string) => Promise<unknown> };
  clearHeldDraftsMutation: { mutateAsync: () => Promise<unknown> };
}

export { createPosWorkspaceBaseActions, createPosWorkspaceAsyncActions, createPosWorkspaceReceiptActions };
