import { Kysely, sql } from 'kysely';
import { Database } from '../database.types';

const upStatements = [
  `ALTER TABLE hr_employees ADD COLUMN IF NOT EXISTS compensation_type VARCHAR(24) NOT NULL DEFAULT 'monthly'`,
  `ALTER TABLE hr_employees ADD COLUMN IF NOT EXISTS hourly_rate NUMERIC(12,2) NULL`,
  `ALTER TABLE hr_employees ADD COLUMN IF NOT EXISTS expected_daily_hours NUMERIC(6,2) NULL`,
  `ALTER TABLE hr_employees ADD COLUMN IF NOT EXISTS scheduled_check_in_time VARCHAR(5) NULL`,
  `ALTER TABLE hr_employees ADD COLUMN IF NOT EXISTS scheduled_check_out_time VARCHAR(5) NULL`,
  `ALTER TABLE hr_employees ADD COLUMN IF NOT EXISTS grace_minutes INTEGER NOT NULL DEFAULT 0`,
  `ALTER TABLE hr_employees ADD COLUMN IF NOT EXISTS overtime_policy VARCHAR(24) NOT NULL DEFAULT 'review_only'`,
  `ALTER TABLE hr_employees
    ADD CONSTRAINT hr_employees_compensation_type_valid
    CHECK (compensation_type IN ('monthly','hourly'))`,
  `ALTER TABLE hr_employees
    ADD CONSTRAINT hr_employees_overtime_policy_valid
    CHECK (overtime_policy IN ('review_only','disabled','auto_approved'))`,
  `ALTER TABLE hr_employees
    ADD CONSTRAINT hr_employees_grace_minutes_non_negative
    CHECK (grace_minutes >= 0)`,
  `CREATE TABLE IF NOT EXISTS hr_attendance_exceptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES hr_employees(id) ON DELETE CASCADE,
    attendance_record_id BIGINT NULL REFERENCES hr_attendance_records(id) ON DELETE CASCADE,
    work_date DATE NOT NULL,
    exception_type VARCHAR(40) NOT NULL,
    scheduled_time VARCHAR(5) NULL,
    actual_time VARCHAR(5) NULL,
    duration_minutes INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(24) NOT NULL DEFAULT 'pending',
    approved_duration_minutes INTEGER NULL,
    note TEXT NULL,
    created_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    updated_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT hr_attendance_exceptions_type_valid
      CHECK (exception_type IN ('early_check_in','late_check_in','early_check_out','late_check_out','missing_check_in','missing_check_out')),
    CONSTRAINT hr_attendance_exceptions_status_valid
      CHECK (status IN ('pending','approved','skipped','auto_calculated','needs_review')),
    CONSTRAINT hr_attendance_exceptions_duration_non_negative
      CHECK (duration_minutes >= 0)
  )`,
  'CREATE UNIQUE INDEX IF NOT EXISTS idx_hr_attendance_exceptions_unique_row ON hr_attendance_exceptions(employee_id, work_date, exception_type)',
  'CREATE INDEX IF NOT EXISTS idx_hr_attendance_exceptions_employee ON hr_attendance_exceptions(employee_id)',
  'CREATE INDEX IF NOT EXISTS idx_hr_attendance_exceptions_work_date ON hr_attendance_exceptions(work_date)',
  'CREATE INDEX IF NOT EXISTS idx_hr_attendance_exceptions_status ON hr_attendance_exceptions(status)',
];

const downStatements = [
  'DROP TABLE IF EXISTS hr_attendance_exceptions',
  'ALTER TABLE hr_employees DROP CONSTRAINT IF EXISTS hr_employees_grace_minutes_non_negative',
  'ALTER TABLE hr_employees DROP CONSTRAINT IF EXISTS hr_employees_overtime_policy_valid',
  'ALTER TABLE hr_employees DROP CONSTRAINT IF EXISTS hr_employees_compensation_type_valid',
  'ALTER TABLE hr_employees DROP COLUMN IF EXISTS overtime_policy',
  'ALTER TABLE hr_employees DROP COLUMN IF EXISTS grace_minutes',
  'ALTER TABLE hr_employees DROP COLUMN IF EXISTS scheduled_check_out_time',
  'ALTER TABLE hr_employees DROP COLUMN IF EXISTS scheduled_check_in_time',
  'ALTER TABLE hr_employees DROP COLUMN IF EXISTS expected_daily_hours',
  'ALTER TABLE hr_employees DROP COLUMN IF EXISTS hourly_rate',
  'ALTER TABLE hr_employees DROP COLUMN IF EXISTS compensation_type',
];

export const migration = {
  up: async (db: Kysely<Database>): Promise<void> => {
    for (const statement of upStatements) {
      await sql.raw(statement).execute(db);
    }
  },
  down: async (db: Kysely<Database>): Promise<void> => {
    for (const statement of downStatements) {
      await sql.raw(statement).execute(db);
    }
  },
};
