import { Kysely, sql } from 'kysely';
import { Database } from '../database.types';

export const migration = {
  up: async (db: Kysely<Database>): Promise<void> => {
    await sql`
      CREATE TABLE IF NOT EXISTS product_location_stock (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
        branch_id BIGINT NULL REFERENCES branches(id) ON DELETE SET NULL,
        location_id BIGINT NULL REFERENCES stock_locations(id) ON DELETE CASCADE,
        qty NUMERIC(14,3) NOT NULL DEFAULT 0,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT chk_product_location_stock_qty_non_negative CHECK (qty >= 0)
      )
    `.execute(db);

    await sql`CREATE UNIQUE INDEX IF NOT EXISTS uq_product_location_stock_product_location ON product_location_stock(product_id, location_id) WHERE location_id IS NOT NULL`.execute(db);
    await sql`CREATE UNIQUE INDEX IF NOT EXISTS uq_product_location_stock_product_unassigned ON product_location_stock(product_id) WHERE location_id IS NULL`.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_product_location_stock_location ON product_location_stock(location_id, product_id)`.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_product_location_stock_branch ON product_location_stock(branch_id, product_id)`.execute(db);

    await sql`
      INSERT INTO product_location_stock (product_id, branch_id, location_id, qty)
      SELECT p.id, NULL, NULL, p.stock_qty
      FROM products p
      WHERE ABS(COALESCE(p.stock_qty, 0)) > 0
        AND NOT EXISTS (
          SELECT 1
          FROM product_location_stock pls
          WHERE pls.product_id = p.id
            AND pls.location_id IS NULL
        )
    `.execute(db);
  },
  down: async (db: Kysely<Database>): Promise<void> => {
    await sql`DROP INDEX IF EXISTS idx_product_location_stock_branch`.execute(db);
    await sql`DROP INDEX IF EXISTS idx_product_location_stock_location`.execute(db);
    await sql`DROP INDEX IF EXISTS uq_product_location_stock_product_unassigned`.execute(db);
    await sql`DROP INDEX IF EXISTS uq_product_location_stock_product_location`.execute(db);
    await sql`DROP TABLE IF EXISTS product_location_stock`.execute(db);
  },
};
