import { Kysely, sql } from 'kysely';
import { Database } from '../database.types';

export const migration = {
  up: async (db: Kysely<Database>): Promise<void> => {
    await sql`
      CREATE TABLE IF NOT EXISTS user_branches (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        branch_id BIGINT NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_user_branches UNIQUE (user_id, branch_id)
      )
    `.execute(db);

    await sql`
      INSERT INTO user_branches (user_id, branch_id)
      SELECT DISTINCT u.id, (entry.value)::bigint
      FROM users u,
      LATERAL jsonb_array_elements_text(COALESCE(u.branch_ids_json, '[]'::jsonb)) AS entry(value)
      WHERE jsonb_typeof(COALESCE(u.branch_ids_json, '[]'::jsonb)) = 'array'
        AND entry.value ~ '^[0-9]+$'
      ON CONFLICT (user_id, branch_id) DO NOTHING
    `.execute(db);

    await sql`
      INSERT INTO user_branches (user_id, branch_id)
      SELECT id, default_branch_id
      FROM users
      WHERE default_branch_id IS NOT NULL
      ON CONFLICT (user_id, branch_id) DO NOTHING
    `.execute(db);

    await sql`ALTER TABLE users DROP COLUMN IF EXISTS branch_ids_json`.execute(db);
  },
  down: async (db: Kysely<Database>): Promise<void> => {
    await sql`ALTER TABLE users ADD COLUMN IF NOT EXISTS branch_ids_json JSONB NOT NULL DEFAULT '[]'::jsonb`.execute(db);
    await sql`
      UPDATE users u
      SET branch_ids_json = COALESCE(src.branch_ids_json, '[]'::jsonb)
      FROM (
        SELECT user_id, jsonb_agg(branch_id ORDER BY branch_id) AS branch_ids_json
        FROM user_branches
        GROUP BY user_id
      ) AS src
      WHERE src.user_id = u.id
    `.execute(db);
    await sql`DROP TABLE IF EXISTS user_branches`.execute(db);
  },
};
