import { Kysely, sql } from 'kysely';
import { Database } from '../database.types';

const upStatements = [
  `CREATE TABLE IF NOT EXISTS hr_employee_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES hr_employees(id) ON DELETE CASCADE,
    asset_type VARCHAR(80) NOT NULL,
    asset_name VARCHAR(160) NOT NULL,
    asset_code VARCHAR(80) NULL,
    serial_no VARCHAR(120) NULL,
    assigned_at DATE NOT NULL,
    returned_at DATE NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'assigned',
    notes TEXT NULL,
    return_notes TEXT NULL,
    created_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    updated_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT hr_employee_assets_asset_type_not_empty CHECK (LENGTH(TRIM(asset_type)) > 0),
    CONSTRAINT hr_employee_assets_asset_name_not_empty CHECK (LENGTH(TRIM(asset_name)) > 0),
    CONSTRAINT hr_employee_assets_status_valid CHECK (status IN ('assigned','returned','lost','damaged','cancelled'))
  )`,
  'CREATE INDEX IF NOT EXISTS idx_hr_employee_assets_employee_id ON hr_employee_assets(employee_id)',
  'CREATE INDEX IF NOT EXISTS idx_hr_employee_assets_asset_type ON hr_employee_assets(asset_type)',
  'CREATE INDEX IF NOT EXISTS idx_hr_employee_assets_asset_code ON hr_employee_assets(asset_code)',
  'CREATE INDEX IF NOT EXISTS idx_hr_employee_assets_serial_no ON hr_employee_assets(serial_no)',
  'CREATE INDEX IF NOT EXISTS idx_hr_employee_assets_status ON hr_employee_assets(status)',
  'CREATE INDEX IF NOT EXISTS idx_hr_employee_assets_assigned_at ON hr_employee_assets(assigned_at)',
  'CREATE INDEX IF NOT EXISTS idx_hr_employee_assets_returned_at ON hr_employee_assets(returned_at)',
];

const downStatements = [
  'DROP TABLE IF EXISTS hr_employee_assets',
];

export const migration = {
  up: async (db: Kysely<Database>): Promise<void> => {
    for (const statement of upStatements) {
      await sql.raw(statement).execute(db);
    }
  },
  down: async (db: Kysely<Database>): Promise<void> => {
    for (const statement of downStatements) {
      await sql.raw(statement).execute(db);
    }
  },
};
