import { Kysely, sql } from 'kysely';
import { Database } from '../database.types';

export const migration = {
  up: async (db: Kysely<Database>): Promise<void> => {
    await sql`
      CREATE TABLE IF NOT EXISTS return_documents (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        doc_no TEXT NULL,
        return_type TEXT NOT NULL,
        invoice_id BIGINT NULL,
        settlement_mode TEXT NOT NULL DEFAULT 'refund',
        refund_method TEXT NOT NULL DEFAULT '',
        exchange_sale_id BIGINT NULL REFERENCES sales(id) ON DELETE SET NULL,
        total NUMERIC(14,2) NOT NULL DEFAULT 0,
        note TEXT NOT NULL DEFAULT '',
        branch_id BIGINT NULL REFERENCES branches(id) ON DELETE SET NULL,
        location_id BIGINT NULL REFERENCES stock_locations(id) ON DELETE SET NULL,
        created_by BIGINT NULL REFERENCES users(id),
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT return_documents_type_valid CHECK (return_type IN ('sale','purchase'))
      )
    `.execute(db);

    await sql`
      CREATE TABLE IF NOT EXISTS return_items (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        return_document_id BIGINT NOT NULL REFERENCES return_documents(id) ON DELETE CASCADE,
        product_id BIGINT NULL REFERENCES products(id) ON DELETE SET NULL,
        product_name TEXT NOT NULL,
        qty NUMERIC(14,3) NOT NULL DEFAULT 0,
        unit_total NUMERIC(14,2) NOT NULL DEFAULT 0,
        line_total NUMERIC(14,2) NOT NULL DEFAULT 0,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `.execute(db);

    await sql`ALTER TABLE treasury_transactions ADD COLUMN IF NOT EXISTS return_document_id BIGINT NULL REFERENCES return_documents(id) ON DELETE SET NULL`.execute(db);
    await sql`ALTER TABLE customer_ledger ADD COLUMN IF NOT EXISTS return_document_id BIGINT NULL REFERENCES return_documents(id) ON DELETE SET NULL`.execute(db);
    await sql`ALTER TABLE supplier_ledger ADD COLUMN IF NOT EXISTS return_document_id BIGINT NULL REFERENCES return_documents(id) ON DELETE SET NULL`.execute(db);

    await sql`
      INSERT INTO return_documents
      (id, doc_no, return_type, invoice_id, settlement_mode, refund_method, exchange_sale_id, total, note, branch_id, location_id, created_by, created_at)
      SELECT id, doc_no, return_type, invoice_id, settlement_mode, refund_method, exchange_sale_id, total, note, branch_id, location_id, created_by, created_at
      FROM "returns"
      ON CONFLICT (id) DO NOTHING
    `.execute(db);

    await sql`
      INSERT INTO return_items
      (return_document_id, product_id, product_name, qty, unit_total, line_total, created_at)
      SELECT id, product_id, product_name, qty,
        CASE WHEN COALESCE(qty, 0) = 0 THEN 0 ELSE ROUND((total / NULLIF(qty, 0))::numeric, 2) END,
        total,
        created_at
      FROM "returns"
    `.execute(db);

    await sql`
      UPDATE treasury_transactions tt
      SET return_document_id = tt.reference_id
      WHERE tt.reference_type = 'return'
        AND tt.reference_id IS NOT NULL
        AND EXISTS (SELECT 1 FROM return_documents rd WHERE rd.id = tt.reference_id)
    `.execute(db);
    await sql`
      UPDATE customer_ledger cl
      SET return_document_id = cl.reference_id
      WHERE cl.reference_type = 'return'
        AND cl.reference_id IS NOT NULL
        AND EXISTS (SELECT 1 FROM return_documents rd WHERE rd.id = cl.reference_id)
    `.execute(db);
    await sql`
      UPDATE supplier_ledger sl
      SET return_document_id = sl.reference_id
      WHERE sl.reference_type = 'return'
        AND sl.reference_id IS NOT NULL
        AND EXISTS (SELECT 1 FROM return_documents rd WHERE rd.id = sl.reference_id)
    `.execute(db);

    await sql`DROP TABLE IF EXISTS "returns"`.execute(db);

    await sql`CREATE INDEX IF NOT EXISTS idx_return_documents_created_at ON return_documents(created_at)`.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_return_documents_invoice_id ON return_documents(invoice_id)`.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_return_items_return_document_id ON return_items(return_document_id)`.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_return_items_product_id ON return_items(product_id)`.execute(db);
  },
  down: async (db: Kysely<Database>): Promise<void> => {
    await sql`
      CREATE TABLE IF NOT EXISTS "returns" (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        doc_no TEXT NULL,
        return_type TEXT NOT NULL,
        invoice_id BIGINT NULL,
        product_id BIGINT NULL REFERENCES products(id) ON DELETE SET NULL,
        product_name TEXT NOT NULL,
        qty NUMERIC(14,3) NOT NULL DEFAULT 0,
        total NUMERIC(14,2) NOT NULL DEFAULT 0,
        settlement_mode TEXT NOT NULL DEFAULT 'refund',
        refund_method TEXT NOT NULL DEFAULT '',
        exchange_sale_id BIGINT NULL REFERENCES sales(id) ON DELETE SET NULL,
        note TEXT NOT NULL DEFAULT '',
        branch_id BIGINT NULL REFERENCES branches(id) ON DELETE SET NULL,
        location_id BIGINT NULL REFERENCES stock_locations(id) ON DELETE SET NULL,
        created_by BIGINT NULL REFERENCES users(id),
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT returns_type_valid CHECK (return_type IN ('sale','purchase'))
      )
    `.execute(db);

    await sql`
      INSERT INTO "returns"
      (id, doc_no, return_type, invoice_id, product_id, product_name, qty, total, settlement_mode, refund_method, exchange_sale_id, note, branch_id, location_id, created_by, created_at)
      SELECT rd.id, rd.doc_no, rd.return_type, rd.invoice_id, ri.product_id, ri.product_name, ri.qty, ri.line_total, rd.settlement_mode, rd.refund_method, rd.exchange_sale_id, rd.note, rd.branch_id, rd.location_id, rd.created_by, rd.created_at
      FROM return_documents rd
      INNER JOIN return_items ri ON ri.return_document_id = rd.id
    `.execute(db);

    await sql`ALTER TABLE treasury_transactions DROP COLUMN IF EXISTS return_document_id`.execute(db);
    await sql`ALTER TABLE customer_ledger DROP COLUMN IF EXISTS return_document_id`.execute(db);
    await sql`ALTER TABLE supplier_ledger DROP COLUMN IF EXISTS return_document_id`.execute(db);
    await sql`DROP TABLE IF EXISTS return_items`.execute(db);
    await sql`DROP TABLE IF EXISTS return_documents`.execute(db);
  },
};
