import { Kysely, sql } from 'kysely';

const ddlStatements = [
  `CREATE TABLE IF NOT EXISTS manufacturing_boms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    quantity NUMERIC(14,3) NOT NULL DEFAULT 1,
    expected_cost NUMERIC(14,2) NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    tenant_id TEXT NOT NULL DEFAULT '',
    account_id TEXT NOT NULL DEFAULT ''
  )`,
  `CREATE TABLE IF NOT EXISTS manufacturing_bom_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bom_id BIGINT NOT NULL REFERENCES manufacturing_boms(id) ON DELETE CASCADE,
    component_product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    quantity NUMERIC(14,3) NOT NULL DEFAULT 1,
    unit_name TEXT NOT NULL DEFAULT 'قطعة',
    unit_multiplier NUMERIC(14,6) NOT NULL DEFAULT 1,
    expected_cost NUMERIC(14,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,
  `CREATE TABLE IF NOT EXISTS manufacturing_work_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_no TEXT NULL,
    bom_id BIGINT NOT NULL REFERENCES manufacturing_boms(id) ON DELETE RESTRICT,
    status TEXT NOT NULL DEFAULT 'draft',
    quantity_to_produce NUMERIC(14,3) NOT NULL DEFAULT 1,
    produced_quantity NUMERIC(14,3) NOT NULL DEFAULT 0,
    source_location_id BIGINT NULL REFERENCES stock_locations(id) ON DELETE SET NULL,
    destination_location_id BIGINT NULL REFERENCES stock_locations(id) ON DELETE SET NULL,
    start_date TIMESTAMPTZ NULL,
    end_date TIMESTAMPTZ NULL,
    total_cost NUMERIC(14,2) NOT NULL DEFAULT 0,
    note TEXT NOT NULL DEFAULT '',
    created_by BIGINT NULL REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    tenant_id TEXT NOT NULL DEFAULT '',
    account_id TEXT NOT NULL DEFAULT '',
    CONSTRAINT manufacturing_wo_status_valid CHECK (status IN ('draft', 'in_progress', 'done', 'cancelled'))
  )`,
  `CREATE TABLE IF NOT EXISTS manufacturing_wo_consumptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id BIGINT NOT NULL REFERENCES manufacturing_work_orders(id) ON DELETE CASCADE,
    component_product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    quantity_consumed NUMERIC(14,3) NOT NULL DEFAULT 0,
    unit_cost NUMERIC(14,2) NOT NULL DEFAULT 0,
    line_total NUMERIC(14,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,
  `CREATE INDEX IF NOT EXISTS idx_mfg_boms_product_id ON manufacturing_boms(product_id)`,
  `CREATE INDEX IF NOT EXISTS idx_mfg_bom_lines_bom_id ON manufacturing_bom_lines(bom_id)`,
  `CREATE INDEX IF NOT EXISTS idx_mfg_work_orders_bom_id ON manufacturing_work_orders(bom_id)`,
  `CREATE INDEX IF NOT EXISTS idx_mfg_work_orders_status ON manufacturing_work_orders(status)`,
  `CREATE INDEX IF NOT EXISTS idx_mfg_wo_consumptions_wo_id ON manufacturing_wo_consumptions(work_order_id)`
];

const dropStatements = [
  'DROP TABLE IF EXISTS manufacturing_wo_consumptions',
  'DROP TABLE IF EXISTS manufacturing_work_orders',
  'DROP TABLE IF EXISTS manufacturing_bom_lines',
  'DROP TABLE IF EXISTS manufacturing_boms',
];

export const migration = {
  up: async (db: Kysely<unknown>): Promise<void> => {
    for (let i = 0; i < ddlStatements.length; i += 1) {
      const statement = ddlStatements[i];
      try {
        await sql.raw(statement).execute(db);
      } catch (error) {
        console.error('FAILED DDL INDEX:', i);
        console.error('FAILED DDL STATEMENT:\n', statement);
        throw error;
      }
    }
  },
  down: async (db: Kysely<unknown>): Promise<void> => {
    for (let i = 0; i < dropStatements.length; i += 1) {
      const statement = dropStatements[i];
      try {
        await sql.raw(statement).execute(db);
      } catch (error) {
        console.error('FAILED DROP INDEX:', i);
        console.error('FAILED DROP STATEMENT:\n', statement);
        throw error;
      }
    }
  },
};
