import { Kysely, sql } from 'kysely';
import { Database } from '../database.types';

const ddlStatements = [
  `CREATE TABLE IF NOT EXISTS addons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR NOT NULL,
    account_id VARCHAR NOT NULL,
    name VARCHAR NOT NULL,
    price NUMERIC(14,2) NOT NULL DEFAULT 0,
    cost_price NUMERIC(14,2) NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,
  `CREATE INDEX IF NOT EXISTS idx_addons_tenant_id ON addons(tenant_id)`
];

const dropStatements = [
  'DROP TABLE IF EXISTS addons'
];

export const migration = {
  up: async (db: Kysely<Database>): Promise<void> => {
    for (let i = 0; i < ddlStatements.length; i += 1) {
      const statement = ddlStatements[i];
      try {
        await sql.raw(statement).execute(db);
      } catch (error) {
        console.error('FAILED DDL INDEX:', i);
        console.error('FAILED DDL STATEMENT:\n', statement);
        throw error;
      }
    }
  },
  down: async (db: Kysely<Database>): Promise<void> => {
    for (let i = 0; i < dropStatements.length; i += 1) {
      const statement = dropStatements[i];
      try {
        await sql.raw(statement).execute(db);
      } catch (error) {
        console.error('FAILED DROP INDEX:', i);
        console.error('FAILED DROP STATEMENT:\n', statement);
        throw error;
      }
    }
  },
};
