import { sql, type Kysely } from 'kysely';

export const migration = {
  async up(db: Kysely<unknown>): Promise<void> {
    // 1. Maritime Client Inquiries Table (Customer Freight Requests)
    await sql`
      CREATE TABLE IF NOT EXISTS maritime_inquiries (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        inquiry_number TEXT NOT NULL,
        customer_id BIGINT NULL,
        customer_name TEXT NOT NULL,
        customer_phone TEXT NULL,
        customer_email TEXT NULL,
        direction TEXT NOT NULL DEFAULT 'import',
        pol_id BIGINT NULL REFERENCES shipping_ports(id) ON DELETE SET NULL,
        pol_code TEXT NOT NULL,
        pol_name TEXT NOT NULL,
        pod_id BIGINT NULL REFERENCES shipping_ports(id) ON DELETE SET NULL,
        pod_code TEXT NOT NULL,
        pod_name TEXT NOT NULL,
        incoterm TEXT NOT NULL DEFAULT 'FOB',
        cargo_mode TEXT NOT NULL DEFAULT 'FCL',
        container_type TEXT NOT NULL DEFAULT '40HC',
        container_count INTEGER NOT NULL DEFAULT 1,
        commodity_description TEXT NOT NULL DEFAULT '',
        cargo_nature TEXT NOT NULL DEFAULT 'general',
        gross_weight_kg NUMERIC(12, 2) NOT NULL DEFAULT 0,
        cbm NUMERIC(10, 2) NOT NULL DEFAULT 0,
        cargo_ready_date DATE NULL,
        target_delivery_date DATE NULL,
        target_free_days INTEGER NOT NULL DEFAULT 14,
        payment_term TEXT NOT NULL DEFAULT 'prepaid',
        status TEXT NOT NULL DEFAULT 'received',
        rfq_id BIGINT NULL REFERENCES maritime_rfqs(id) ON DELETE SET NULL,
        quotation_id BIGINT NULL REFERENCES maritime_quotations(id) ON DELETE SET NULL,
        job_id BIGINT NULL REFERENCES maritime_jobs(id) ON DELETE SET NULL,
        notes TEXT NULL,
        created_by BIGINT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_maritime_inquiries_tenant_num UNIQUE (tenant_id, inquiry_number)
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_maritime_inquiries_tenant_status 
      ON maritime_inquiries (tenant_id, status);
    `.execute(db);

    // 2. Add customer fields & inquiry linking to maritime_rfqs
    await sql`
      ALTER TABLE maritime_rfqs
      ADD COLUMN IF NOT EXISTS inquiry_id BIGINT NULL REFERENCES maritime_inquiries(id) ON DELETE SET NULL,
      ADD COLUMN IF NOT EXISTS customer_id BIGINT NULL,
      ADD COLUMN IF NOT EXISTS customer_name TEXT NULL,
      ADD COLUMN IF NOT EXISTS customer_phone TEXT NULL,
      ADD COLUMN IF NOT EXISTS customer_email TEXT NULL;
    `.execute(db);

    // 3. Add inquiry linking to maritime_quotations
    await sql`
      ALTER TABLE maritime_quotations
      ADD COLUMN IF NOT EXISTS inquiry_id BIGINT NULL REFERENCES maritime_inquiries(id) ON DELETE SET NULL;
    `.execute(db);

    // 4. Add inquiry linking and delivery milestones to maritime_jobs
    await sql`
      ALTER TABLE maritime_jobs
      ADD COLUMN IF NOT EXISTS inquiry_id BIGINT NULL REFERENCES maritime_inquiries(id) ON DELETE SET NULL,
      ADD COLUMN IF NOT EXISTS delivered_to_client_at TIMESTAMPTZ NULL,
      ADD COLUMN IF NOT EXISTS delivery_address TEXT NULL;
    `.execute(db);
  },

  async down(db: Kysely<unknown>): Promise<void> {
    await sql`ALTER TABLE maritime_jobs DROP COLUMN IF EXISTS delivery_address;`.execute(db);
    await sql`ALTER TABLE maritime_jobs DROP COLUMN IF EXISTS delivered_to_client_at;`.execute(db);
    await sql`ALTER TABLE maritime_jobs DROP COLUMN IF EXISTS inquiry_id;`.execute(db);
    await sql`ALTER TABLE maritime_quotations DROP COLUMN IF EXISTS inquiry_id;`.execute(db);
    await sql`ALTER TABLE maritime_rfqs DROP COLUMN IF EXISTS customer_email;`.execute(db);
    await sql`ALTER TABLE maritime_rfqs DROP COLUMN IF EXISTS customer_phone;`.execute(db);
    await sql`ALTER TABLE maritime_rfqs DROP COLUMN IF EXISTS customer_name;`.execute(db);
    await sql`ALTER TABLE maritime_rfqs DROP COLUMN IF EXISTS customer_id;`.execute(db);
    await sql`ALTER TABLE maritime_rfqs DROP COLUMN IF EXISTS inquiry_id;`.execute(db);
    await sql`DROP TABLE IF EXISTS maritime_inquiries;`.execute(db);
  },
};
