import { sql, type Kysely } from 'kysely';

export const migration = {
  async up(db: Kysely<unknown>): Promise<void> {
    // 1. Contracting Projects Table
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_projects (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        code TEXT NOT NULL,
        name TEXT NOT NULL,
        client_id BIGINT NULL REFERENCES customers(id) ON DELETE SET NULL,
        client_name TEXT NOT NULL DEFAULT '',
        status TEXT NOT NULL DEFAULT 'planning',
        contract_value NUMERIC(15, 3) NOT NULL DEFAULT 0,
        revised_contract_value NUMERIC(15, 3) NOT NULL DEFAULT 0,
        down_payment_amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        down_payment_recovered NUMERIC(15, 3) NOT NULL DEFAULT 0,
        retention_percent NUMERIC(5, 2) NOT NULL DEFAULT 5.00,
        retention_total_held NUMERIC(15, 3) NOT NULL DEFAULT 0,
        retention_released NUMERIC(15, 3) NOT NULL DEFAULT 0,
        start_date DATE NULL,
        expected_end_date DATE NULL,
        actual_end_date DATE NULL,
        site_location_id BIGINT NULL,
        cost_center_id BIGINT NULL REFERENCES cost_centers(id) ON DELETE SET NULL,
        project_manager TEXT NULL,
        location_address TEXT NULL,
        notes TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_contracting_projects_tenant_code UNIQUE (tenant_id, code)
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_projects_tenant_status 
      ON contracting_projects (tenant_id, status);
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_projects_client 
      ON contracting_projects (tenant_id, client_id);
    `.execute(db);

    // 2. BOQ Items Table (Schedule of Values - SOV / بنود المقايسة)
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_boq_items (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        project_id BIGINT NOT NULL REFERENCES contracting_projects(id) ON DELETE CASCADE,
        item_code TEXT NOT NULL,
        description TEXT NOT NULL,
        category TEXT NOT NULL DEFAULT 'general',
        unit TEXT NOT NULL DEFAULT 'm3',
        contract_qty NUMERIC(15, 3) NOT NULL DEFAULT 0,
        revised_qty NUMERIC(15, 3) NOT NULL DEFAULT 0,
        unit_price NUMERIC(15, 3) NOT NULL DEFAULT 0,
        total_price NUMERIC(15, 3) NOT NULL DEFAULT 0,
        estimated_unit_cost NUMERIC(15, 3) NOT NULL DEFAULT 0,
        executed_qty NUMERIC(15, 3) NOT NULL DEFAULT 0,
        notes TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_contracting_boq_tenant_proj_code UNIQUE (tenant_id, project_id, item_code)
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_boq_project 
      ON contracting_boq_items (tenant_id, project_id);
    `.execute(db);

    // 3. Change Orders Table (أوامر التغيير والملحقات التعاقدية)
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_change_orders (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        project_id BIGINT NOT NULL REFERENCES contracting_projects(id) ON DELETE CASCADE,
        change_order_number TEXT NOT NULL,
        title TEXT NOT NULL,
        reason TEXT NOT NULL DEFAULT 'client_request',
        impact_type TEXT NOT NULL DEFAULT 'cost_and_time',
        cost_impact NUMERIC(15, 3) NOT NULL DEFAULT 0,
        time_impact_days INTEGER NOT NULL DEFAULT 0,
        status TEXT NOT NULL DEFAULT 'draft',
        approved_by TEXT NULL,
        approved_at TIMESTAMPTZ NULL,
        notes TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_contracting_change_orders_tenant_num UNIQUE (tenant_id, change_order_number)
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_change_orders_proj 
      ON contracting_change_orders (tenant_id, project_id, status);
    `.execute(db);

    // 4. Contracting Invoices / IPCs (المستخلصات التراكمية AIA G702)
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_invoices (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        project_id BIGINT NOT NULL REFERENCES contracting_projects(id) ON DELETE CASCADE,
        ipc_number TEXT NOT NULL,
        ipc_type TEXT NOT NULL DEFAULT 'client',
        subcontractor_id BIGINT NULL REFERENCES suppliers(id) ON DELETE SET NULL,
        subcontractor_name TEXT NOT NULL DEFAULT '',
        sequence_order INTEGER NOT NULL DEFAULT 1,
        period_start DATE NULL,
        period_end DATE NULL,
        previous_amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        current_amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        stored_materials_amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        cumulative_amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        advance_recovery_amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        retention_held_amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        other_deductions NUMERIC(15, 3) NOT NULL DEFAULT 0,
        net_payable NUMERIC(15, 3) NOT NULL DEFAULT 0,
        status TEXT NOT NULL DEFAULT 'draft',
        journal_entry_id BIGINT NULL REFERENCES journal_entries(id) ON DELETE SET NULL,
        notes TEXT NULL,
        approved_by TEXT NULL,
        approved_at TIMESTAMPTZ NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_contracting_invoices_tenant_ipc UNIQUE (tenant_id, ipc_number)
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_invoices_project_status 
      ON contracting_invoices (tenant_id, project_id, status);
    `.execute(db);

    // 5. Contracting Invoice Items Table (AIA G703 Continuation Sheet)
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_invoice_items (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        invoice_id BIGINT NOT NULL REFERENCES contracting_invoices(id) ON DELETE CASCADE,
        boq_item_id BIGINT NULL REFERENCES contracting_boq_items(id) ON DELETE SET NULL,
        description TEXT NOT NULL DEFAULT '',
        unit TEXT NOT NULL DEFAULT 'm3',
        unit_price NUMERIC(15, 3) NOT NULL DEFAULT 0,
        previous_qty NUMERIC(15, 3) NOT NULL DEFAULT 0,
        current_qty NUMERIC(15, 3) NOT NULL DEFAULT 0,
        stored_materials_qty NUMERIC(15, 3) NOT NULL DEFAULT 0,
        cumulative_qty NUMERIC(15, 3) NOT NULL DEFAULT 0,
        completion_percent NUMERIC(6, 2) NOT NULL DEFAULT 0,
        current_total NUMERIC(15, 3) NOT NULL DEFAULT 0,
        cumulative_total NUMERIC(15, 3) NOT NULL DEFAULT 0,
        notes TEXT NULL
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_invoice_items_inv 
      ON contracting_invoice_items (tenant_id, invoice_id);
    `.execute(db);

    // 6. Contracting Subcontracts Table (Commitments - عقود مقاولي الباطن)
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_subcontracts (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        project_id BIGINT NOT NULL REFERENCES contracting_projects(id) ON DELETE CASCADE,
        subcontractor_id BIGINT NOT NULL REFERENCES suppliers(id) ON DELETE CASCADE,
        contract_number TEXT NOT NULL,
        scope_of_work TEXT NOT NULL,
        total_amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        retention_percent NUMERIC(5, 2) NOT NULL DEFAULT 5.00,
        start_date DATE NULL,
        end_date DATE NULL,
        status TEXT NOT NULL DEFAULT 'active',
        notes TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_contracting_subcontracts_tenant_code UNIQUE (tenant_id, contract_number)
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_subcontracts_proj 
      ON contracting_subcontracts (tenant_id, project_id);
    `.execute(db);

    // 7. Contracting Site Daily Logs Table (اليومية الميدانية وتقارير الموقع)
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_site_daily_logs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        project_id BIGINT NOT NULL REFERENCES contracting_projects(id) ON DELETE CASCADE,
        log_date DATE NOT NULL DEFAULT CURRENT_DATE,
        weather_conditions TEXT NULL,
        labor_count INTEGER NOT NULL DEFAULT 0,
        subcontractor_labor_count INTEGER NOT NULL DEFAULT 0,
        equipment_on_site TEXT NULL,
        work_performed TEXT NOT NULL,
        delays_or_obstacles TEXT NULL,
        materials_received TEXT NULL,
        logged_by TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_daily_logs_proj_date 
      ON contracting_site_daily_logs (tenant_id, project_id, log_date);
    `.execute(db);

    // 8. Contracting RFIs Table (استفسارات المكتب الفني والاستشاري)
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_rfis (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        project_id BIGINT NOT NULL REFERENCES contracting_projects(id) ON DELETE CASCADE,
        rfi_number TEXT NOT NULL,
        subject TEXT NOT NULL,
        question TEXT NOT NULL,
        assigned_to TEXT NULL,
        status TEXT NOT NULL DEFAULT 'open',
        answer TEXT NULL,
        answered_by TEXT NULL,
        answered_at TIMESTAMPTZ NULL,
        date_requested DATE NOT NULL DEFAULT CURRENT_DATE,
        date_required DATE NULL,
        notes TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_contracting_rfis_tenant_num UNIQUE (tenant_id, rfi_number)
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_rfis_proj_status 
      ON contracting_rfis (tenant_id, project_id, status);
    `.execute(db);

    // 9. Contracting Schedule Tasks Table (مخطط جانت والمسار الحرج WBS & CPM)
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_schedule_tasks (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        project_id BIGINT NOT NULL REFERENCES contracting_projects(id) ON DELETE CASCADE,
        task_code TEXT NOT NULL,
        task_name TEXT NOT NULL,
        wbs_code TEXT NOT NULL DEFAULT '1.0',
        start_date DATE NOT NULL,
        end_date DATE NOT NULL,
        duration_days INTEGER NOT NULL DEFAULT 1,
        progress_percent NUMERIC(5, 2) NOT NULL DEFAULT 0.00,
        predecessor_id BIGINT NULL REFERENCES contracting_schedule_tasks(id) ON DELETE SET NULL,
        is_critical_path BOOLEAN NOT NULL DEFAULT false,
        status TEXT NOT NULL DEFAULT 'not_started',
        boq_item_id BIGINT NULL REFERENCES contracting_boq_items(id) ON DELETE SET NULL,
        assigned_team TEXT NULL,
        notes TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_tasks_proj_dates 
      ON contracting_schedule_tasks (tenant_id, project_id, start_date, end_date);
    `.execute(db);

    // 10. Contracting Material Requisitions Table (أذون صرف الخامات المباشرة على بنود المقايسة)
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_material_requisitions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        project_id BIGINT NOT NULL REFERENCES contracting_projects(id) ON DELETE CASCADE,
        requisition_number TEXT NOT NULL,
        boq_item_id BIGINT NULL REFERENCES contracting_boq_items(id) ON DELETE SET NULL,
        warehouse_id BIGINT NULL REFERENCES stock_locations(id) ON DELETE SET NULL,
        product_id BIGINT NULL REFERENCES products(id) ON DELETE SET NULL,
        item_name TEXT NOT NULL,
        unit TEXT NOT NULL DEFAULT 'unit',
        quantity NUMERIC(15, 3) NOT NULL DEFAULT 0,
        unit_cost NUMERIC(15, 3) NOT NULL DEFAULT 0,
        total_cost NUMERIC(15, 3) NOT NULL DEFAULT 0,
        issue_date DATE NOT NULL DEFAULT CURRENT_DATE,
        recipient_name TEXT NULL,
        status TEXT NOT NULL DEFAULT 'issued',
        notes TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_contracting_reqs_tenant_num UNIQUE (tenant_id, requisition_number)
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_reqs_proj_date 
      ON contracting_material_requisitions (tenant_id, project_id, issue_date);
    `.execute(db);
  },

  async down(db: Kysely<unknown>): Promise<void> {
    await sql`DROP TABLE IF EXISTS contracting_material_requisitions CASCADE;`.execute(db);
    await sql`DROP TABLE IF EXISTS contracting_schedule_tasks CASCADE;`.execute(db);
    await sql`DROP TABLE IF EXISTS contracting_rfis CASCADE;`.execute(db);
    await sql`DROP TABLE IF EXISTS contracting_site_daily_logs CASCADE;`.execute(db);
    await sql`DROP TABLE IF EXISTS contracting_subcontracts CASCADE;`.execute(db);
    await sql`DROP TABLE IF EXISTS contracting_invoice_items CASCADE;`.execute(db);
    await sql`DROP TABLE IF EXISTS contracting_invoices CASCADE;`.execute(db);
    await sql`DROP TABLE IF EXISTS contracting_change_orders CASCADE;`.execute(db);
    await sql`DROP TABLE IF EXISTS contracting_boq_items CASCADE;`.execute(db);
    await sql`DROP TABLE IF EXISTS contracting_projects CASCADE;`.execute(db);
  },
};
