import { Kysely, sql } from 'kysely';

export const migration = {
  up: async (db: Kysely<any>): Promise<void> => {
    // 1. Create goods_receipt_notes (GRN Header)
    await sql`
      CREATE TABLE IF NOT EXISTS goods_receipt_notes (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL,
        account_id TEXT NOT NULL,
        doc_no TEXT NOT NULL,
        purchase_order_id BIGINT NULL,
        supplier_id BIGINT NOT NULL,
        location_id BIGINT NOT NULL,
        received_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        received_by BIGINT NULL,
        inspected_by BIGINT NULL,
        supplier_delivery_note_ref TEXT NULL,
        status TEXT NOT NULL DEFAULT 'draft',
        grni_journal_entry_id BIGINT NULL,
        notes TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_grn_tenant_doc UNIQUE (tenant_id, doc_no),
        CONSTRAINT uq_grn_tenant_id UNIQUE (tenant_id, id),
        CONSTRAINT chk_grn_status CHECK (status IN ('draft', 'inspected', 'accepted', 'partially_rejected', 'posted', 'cancelled'))
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_grn_tenant_po ON goods_receipt_notes (tenant_id, purchase_order_id);
      CREATE INDEX IF NOT EXISTS idx_grn_tenant_supplier ON goods_receipt_notes (tenant_id, supplier_id);
      CREATE INDEX IF NOT EXISTS idx_grn_tenant_status ON goods_receipt_notes (tenant_id, status);
      CREATE INDEX IF NOT EXISTS idx_grn_tenant_date ON goods_receipt_notes (tenant_id, received_at DESC);
    `.execute(db);

    // 2. Create goods_receipt_lines (GRN Items)
    await sql`
      CREATE TABLE IF NOT EXISTS goods_receipt_lines (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL,
        grn_id BIGINT NOT NULL,
        purchase_order_item_id BIGINT NULL,
        product_id BIGINT NOT NULL,
        ordered_qty NUMERIC(15, 4) NOT NULL DEFAULT 0,
        received_qty NUMERIC(15, 4) NOT NULL DEFAULT 0,
        accepted_qty NUMERIC(15, 4) NOT NULL DEFAULT 0,
        rejected_qty NUMERIC(15, 4) NOT NULL DEFAULT 0,
        rejection_reason TEXT NULL,
        batch_number TEXT NULL,
        expiry_date DATE NULL,
        manufacturing_date DATE NULL,
        unit_cost NUMERIC(15, 4) NOT NULL DEFAULT 0,
        quarantine_location_id BIGINT NULL,
        coa_document_id BIGINT NULL,
        notes TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT fk_grn_lines_grn FOREIGN KEY (tenant_id, grn_id)
          REFERENCES goods_receipt_notes(tenant_id, id) ON DELETE CASCADE,
        CONSTRAINT chk_grn_line_qty CHECK (
          received_qty >= 0 AND accepted_qty >= 0 AND rejected_qty >= 0
          AND accepted_qty + rejected_qty = received_qty
        )
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_grn_lines_tenant_grn ON goods_receipt_lines (tenant_id, grn_id);
      CREATE INDEX IF NOT EXISTS idx_grn_lines_tenant_product ON goods_receipt_lines (tenant_id, product_id);
      CREATE INDEX IF NOT EXISTS idx_grn_lines_tenant_po_item ON goods_receipt_lines (tenant_id, purchase_order_item_id);
    `.execute(db);

    // 3. Create purchase_three_way_matches (3-Way Match Audit & Reconciliation Ledger)
    await sql`
      CREATE TABLE IF NOT EXISTS purchase_three_way_matches (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL,
        purchase_id BIGINT NOT NULL,
        purchase_order_id BIGINT NULL,
        grn_id BIGINT NULL,
        match_status TEXT NOT NULL DEFAULT 'unmatched',
        price_variance_amount NUMERIC(15, 4) NOT NULL DEFAULT 0,
        qty_variance_amount NUMERIC(15, 4) NOT NULL DEFAULT 0,
        tolerance_percentage NUMERIC(5, 2) NOT NULL DEFAULT 0,
        is_service_item BOOLEAN NOT NULL DEFAULT FALSE,
        service_completion_ref TEXT NULL,
        override_approved_by BIGINT NULL,
        override_reason TEXT NULL,
        ppv_journal_entry_id BIGINT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_three_way_match_purchase UNIQUE (tenant_id, purchase_id),
        CONSTRAINT chk_three_way_match_status CHECK (
          match_status IN ('matched', 'quantity_mismatch', 'price_mismatch', 'tolerance_exceeded', 'unmatched_grn', 'service_approved', 'override_approved')
        )
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_three_way_match_po ON purchase_three_way_matches (tenant_id, purchase_order_id);
      CREATE INDEX IF NOT EXISTS idx_three_way_match_grn ON purchase_three_way_matches (tenant_id, grn_id);
      CREATE INDEX IF NOT EXISTS idx_three_way_match_status ON purchase_three_way_matches (tenant_id, match_status);
    `.execute(db);

    // 4. Alter purchases & purchase_items
    await sql`
      ALTER TABLE purchases
      ADD COLUMN IF NOT EXISTS grn_id BIGINT NULL,
      ADD COLUMN IF NOT EXISTS three_way_match_status TEXT NOT NULL DEFAULT 'unmatched';

      ALTER TABLE purchase_items
      ADD COLUMN IF NOT EXISTS grn_line_id BIGINT NULL,
      ADD COLUMN IF NOT EXISTS price_variance NUMERIC(15, 4) NOT NULL DEFAULT 0;
    `.execute(db);

    // 5. Seed standard accounts: GRNI (2125) and PPV (5190) in accounting_accounts if not present
    await sql`
      INSERT INTO accounting_accounts (tenant_id, account_id, code, name_ar, name_en, account_type, normal_balance, is_active, created_at, updated_at)
      SELECT 
        t.id as tenant_id,
        t.id as account_id,
        '2125' as code,
        'بضاعة مستلمة غير مفوترة (GRNI)' as name_ar,
        'Goods Received Not Invoiced (GRNI)' as name_en,
        'liability' as account_type,
        'credit' as normal_balance,
        true as is_active,
        NOW() as created_at,
        NOW() as updated_at
      FROM tenants t
      WHERE NOT EXISTS (
        SELECT 1 FROM accounting_accounts aa 
        WHERE aa.tenant_id = t.id AND aa.code = '2125'
      );

      INSERT INTO accounting_accounts (tenant_id, account_id, code, name_ar, name_en, account_type, normal_balance, is_active, created_at, updated_at)
      SELECT 
        t.id as tenant_id,
        t.id as account_id,
        '5190' as code,
        'فروق أسعار الشراء (PPV)' as name_ar,
        'Purchase Price Variance (PPV)' as name_en,
        'expense' as account_type,
        'debit' as normal_balance,
        true as is_active,
        NOW() as created_at,
        NOW() as updated_at
      FROM tenants t
      WHERE NOT EXISTS (
        SELECT 1 FROM accounting_accounts aa 
        WHERE aa.tenant_id = t.id AND aa.code = '5190'
      );
    `.execute(db);
  },

  down: async (db: Kysely<any>): Promise<void> => {
    await sql`ALTER TABLE purchase_items DROP COLUMN IF EXISTS price_variance;`.execute(db);
    await sql`ALTER TABLE purchase_items DROP COLUMN IF EXISTS grn_line_id;`.execute(db);
    await sql`ALTER TABLE purchases DROP COLUMN IF EXISTS three_way_match_status;`.execute(db);
    await sql`ALTER TABLE purchases DROP COLUMN IF EXISTS grn_id;`.execute(db);
    await sql`DROP TABLE IF EXISTS purchase_three_way_matches;`.execute(db);
    await sql`DROP TABLE IF EXISTS goods_receipt_lines;`.execute(db);
    await sql`DROP TABLE IF EXISTS goods_receipt_notes;`.execute(db);
  },
};
