import { sql, type Kysely } from 'kysely';

export const migration = {
  async up(db: Kysely<unknown>): Promise<void> {
    // 1. Create cost_center_allocations table
    await sql`
      CREATE TABLE IF NOT EXISTS cost_center_allocations (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        code TEXT NOT NULL,
        name TEXT NOT NULL,
        description TEXT NULL,
        is_active BOOLEAN NOT NULL DEFAULT TRUE,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_cc_allocations_tenant_code UNIQUE (tenant_id, code)
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_cc_allocations_tenant 
      ON cost_center_allocations (tenant_id);
    `.execute(db);

    // 2. Create cost_center_allocation_splits table
    await sql`
      CREATE TABLE IF NOT EXISTS cost_center_allocation_splits (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        allocation_id BIGINT NOT NULL REFERENCES cost_center_allocations(id) ON DELETE CASCADE,
        cost_center_id BIGINT NOT NULL REFERENCES cost_centers(id) ON DELETE CASCADE,
        percentage NUMERIC(6, 2) NOT NULL,
        notes TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_cc_splits_allocation 
      ON cost_center_allocation_splits (tenant_id, allocation_id);
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_cc_splits_cost_center 
      ON cost_center_allocation_splits (tenant_id, cost_center_id);
    `.execute(db);

    // 3. Add cost_center_allocation_id to expenses table
    await sql`
      ALTER TABLE expenses 
      ADD COLUMN IF NOT EXISTS cost_center_allocation_id BIGINT NULL REFERENCES cost_center_allocations(id) ON DELETE SET NULL;
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_expenses_cc_allocation 
      ON expenses (tenant_id, cost_center_allocation_id) 
      WHERE cost_center_allocation_id IS NOT NULL;
    `.execute(db);
  },

  async down(db: Kysely<unknown>): Promise<void> {
    await sql`ALTER TABLE expenses DROP COLUMN IF EXISTS cost_center_allocation_id;`.execute(db);
    await sql`DROP TABLE IF EXISTS cost_center_allocation_splits CASCADE;`.execute(db);
    await sql`DROP TABLE IF EXISTS cost_center_allocations CASCADE;`.execute(db);
  },
};
