import { sql, type Kysely } from 'kysely';

export const migration = {
  async up(db: Kysely<unknown>): Promise<void> {
    // 1. Dedicated Subcontractors Registry (دليل وسجل مقاولي الباطن)
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_subcontractors (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        account_id TEXT NULL,
        name TEXT NOT NULL,
        trade_specialty TEXT NULL DEFAULT 'مقاولات عامة',
        phone TEXT NULL,
        mobile TEXT NULL,
        email TEXT NULL,
        address TEXT NULL,
        tax_number TEXT NULL,
        commercial_reg TEXT NULL,
        national_id TEXT NULL,
        bank_name TEXT NULL,
        bank_iban TEXT NULL,
        contact_person TEXT NULL,
        rating NUMERIC(3, 1) NOT NULL DEFAULT 5.0,
        status TEXT NOT NULL DEFAULT 'active',
        notes TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_subcontractors_tenant_status
      ON contracting_subcontractors (tenant_id, status);
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_subcontractors_specialty
      ON contracting_subcontractors (tenant_id, trade_specialty);
    `.execute(db);

    // 2. Subcontractor Disbursements & Payments (سندات صرف ودفعات مقاولي الباطن)
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_subcontractor_payments (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        project_id BIGINT NULL REFERENCES contracting_projects(id) ON DELETE SET NULL,
        subcontractor_id BIGINT NOT NULL REFERENCES contracting_subcontractors(id) ON DELETE CASCADE,
        subcontract_id BIGINT NULL REFERENCES contracting_subcontracts(id) ON DELETE SET NULL,
        invoice_id BIGINT NULL REFERENCES contracting_invoices(id) ON DELETE SET NULL,
        payment_number TEXT NOT NULL,
        payment_date DATE NOT NULL DEFAULT CURRENT_DATE,
        amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        payment_method TEXT NOT NULL DEFAULT 'bank_transfer',
        reference_number TEXT NULL,
        notes TEXT NULL,
        created_by BIGINT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_contracting_sub_payment_tenant_num UNIQUE (tenant_id, payment_number)
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_sub_payments_sub_date
      ON contracting_subcontractor_payments (tenant_id, subcontractor_id, payment_date);
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_sub_payments_proj
      ON contracting_subcontractor_payments (tenant_id, project_id);
    `.execute(db);

    // 3. Safe historical backfill from suppliers referenced in subcontracts
    await sql`
      INSERT INTO contracting_subcontractors (id, tenant_id, name, phone, address, notes, trade_specialty, created_at, updated_at)
      SELECT s.id, COALESCE(s.tenant_id, ''), s.name, s.phone, s.address, s.notes, 'مقاولات عامة', COALESCE(s.created_at, NOW()), COALESCE(s.updated_at, NOW())
      FROM suppliers s
      WHERE EXISTS (
        SELECT 1 FROM contracting_subcontracts cs WHERE cs.subcontractor_id = s.id
      )
      ON CONFLICT (id) DO NOTHING;
    `.execute(db);

    await sql`
      SELECT setval(
        pg_get_serial_sequence('contracting_subcontractors', 'id'),
        COALESCE((SELECT MAX(id) FROM contracting_subcontractors), 1)
      );
    `.execute(db);
  },

  async down(db: Kysely<unknown>): Promise<void> {
    await sql`DROP TABLE IF EXISTS contracting_subcontractor_payments CASCADE;`.execute(db);
    await sql`DROP TABLE IF EXISTS contracting_subcontractors CASCADE;`.execute(db);
  },
};
