import { sql, type Kysely } from 'kysely';

// O45: `maritime_cargo_insurances.job_id` and `maritime_warehouse_receipts.job_id` referenced
// `maritime_jobs(id)` alone, so the database would happily accept a child row whose tenant_id does
// not match its job's. The service checks this today (assertJobBelongsToTenant), which is exactly
// the "correct logic that is not wired to the data" pattern: one new write path and the guarantee is
// gone. A composite (tenant_id, job_id) → (tenant_id, id) key makes the mismatch impossible.
//
// Nothing is deleted: if any existing row already mismatches, the migration logs it and leaves the
// old key in place, because reassigning someone's shipment is not a migration's decision.

const CHILDREN = [
  { table: 'maritime_cargo_insurances', constraint: 'fk_cargo_ins_job_tenant' },
  { table: 'maritime_warehouse_receipts', constraint: 'fk_wh_receipt_job_tenant' },
];

async function tableExists(db: Kysely<unknown>, table: string): Promise<boolean> {
  const result = await sql<{ exists: boolean }>`
    select exists (
      select 1 from information_schema.tables
      where table_schema = 'public' and table_name = ${table}
    ) as exists
  `.execute(db);
  return Boolean(result.rows[0]?.exists);
}

export const migration = {
  async up(db: Kysely<unknown>): Promise<void> {
    if (!(await tableExists(db, 'maritime_jobs'))) return;

    // The target of a composite foreign key must be unique.
    await sql`
      CREATE UNIQUE INDEX IF NOT EXISTS uq_maritime_jobs_tenant_id
      ON maritime_jobs (tenant_id, id)
    `.execute(db);

    for (const child of CHILDREN) {
      if (!(await tableExists(db, child.table))) continue;

      const mismatched = await sql<{ count: string }>`
        SELECT COUNT(*)::text AS count
        FROM ${sql.table(child.table)} c
        JOIN maritime_jobs j ON j.id = c.job_id
        WHERE j.tenant_id IS DISTINCT FROM c.tenant_id
      `.execute(db);

      if (Number(mismatched.rows[0]?.count || 0) > 0) {
        console.warn(
          `[migration 140] ${child.table} holds ${mismatched.rows[0]?.count} row(s) whose tenant_id differs from their job's; the composite foreign key was not added. Reconcile them and re-run.`,
        );
        continue;
      }

      // Drop whatever single-column key exists on job_id (its name was generated by Postgres).
      const existing = await sql<{ conname: string }>`
        SELECT con.conname
        FROM pg_constraint con
        JOIN pg_class rel ON rel.oid = con.conrelid
        JOIN pg_attribute att ON att.attrelid = rel.oid AND att.attnum = ANY (con.conkey)
        WHERE con.contype = 'f'
          AND rel.relname = ${child.table}
          AND att.attname = 'job_id'
          AND array_length(con.conkey, 1) = 1
      `.execute(db);

      for (const row of existing.rows) {
        await sql`ALTER TABLE ${sql.table(child.table)} DROP CONSTRAINT ${sql.ref(row.conname)}`.execute(db);
      }

      const alreadyComposite = await sql<{ exists: boolean }>`
        select exists (
          select 1 from pg_constraint where conname = ${child.constraint}
        ) as exists
      `.execute(db);
      if (alreadyComposite.rows[0]?.exists) continue;

      await sql`
        ALTER TABLE ${sql.table(child.table)}
        ADD CONSTRAINT ${sql.ref(child.constraint)}
        FOREIGN KEY (tenant_id, job_id) REFERENCES maritime_jobs (tenant_id, id) ON DELETE CASCADE
      `.execute(db);
    }
  },

  async down(db: Kysely<unknown>): Promise<void> {
    for (const child of CHILDREN) {
      if (!(await tableExists(db, child.table))) continue;
      await sql`ALTER TABLE ${sql.table(child.table)} DROP CONSTRAINT IF EXISTS ${sql.ref(child.constraint)}`.execute(db);
      await sql`
        ALTER TABLE ${sql.table(child.table)}
        ADD CONSTRAINT ${sql.ref(`${child.constraint}_legacy`)}
        FOREIGN KEY (job_id) REFERENCES maritime_jobs (id) ON DELETE CASCADE
      `.execute(db);
    }
    await sql`DROP INDEX IF EXISTS uq_maritime_jobs_tenant_id`.execute(db);
  },
};
