import { Kysely, sql } from 'kysely';

export const migration = {
  async up(db: Kysely<unknown>): Promise<void> {
    // 1. Create manufacturing_work_centers table
    await sql`
      CREATE TABLE IF NOT EXISTS manufacturing_work_centers (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL,
        account_id TEXT NOT NULL,
        code VARCHAR(50) NOT NULL,
        name VARCHAR(150) NOT NULL,
        cost_per_hour NUMERIC(14, 2) NOT NULL DEFAULT 0,
        capacity NUMERIC(14, 2) NOT NULL DEFAULT 1,
        time_efficiency NUMERIC(5, 2) NOT NULL DEFAULT 100,
        status VARCHAR(50) NOT NULL DEFAULT 'active',
        notes TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_mfg_wc_tenant ON manufacturing_work_centers(tenant_id);
    `.execute(db);

    // 2. Create manufacturing_wo_operations table (Operations & Routing)
    await sql`
      CREATE TABLE IF NOT EXISTS manufacturing_wo_operations (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL,
        account_id TEXT NOT NULL,
        work_order_id BIGINT NOT NULL REFERENCES manufacturing_work_orders(id) ON DELETE CASCADE,
        work_center_id BIGINT NOT NULL REFERENCES manufacturing_work_centers(id) ON DELETE RESTRICT,
        operation_name VARCHAR(150) NOT NULL,
        sequence INT NOT NULL DEFAULT 1,
        duration_hours NUMERIC(8, 2) NOT NULL DEFAULT 1,
        hourly_cost NUMERIC(14, 2) NOT NULL DEFAULT 0,
        total_cost NUMERIC(14, 2) NOT NULL DEFAULT 0,
        status VARCHAR(50) NOT NULL DEFAULT 'completed',
        notes TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_mfg_wo_ops_wo_id ON manufacturing_wo_operations(work_order_id);
    `.execute(db);
  },

  async down(db: Kysely<unknown>): Promise<void> {
    await sql`DROP TABLE IF EXISTS manufacturing_wo_operations;`.execute(db);
    await sql`DROP TABLE IF EXISTS manufacturing_work_centers;`.execute(db);
  },
};
