import { sql, type Kysely } from 'kysely';

export const migration = {
  async up(db: Kysely<unknown>): Promise<void> {
    // 1. Material & Shop Drawing Submittals (اعتمادات المواد والمخططات التنفيذية MAR/MAS)
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_submittals (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        project_id BIGINT NOT NULL REFERENCES contracting_projects(id) ON DELETE CASCADE,
        submittal_number TEXT NOT NULL,
        submittal_type TEXT NOT NULL DEFAULT 'material',
        title TEXT NOT NULL,
        specification_section TEXT NULL,
        supplier_manufacturer TEXT NULL,
        boq_item_id BIGINT NULL REFERENCES contracting_boq_items(id) ON DELETE SET NULL,
        subcontract_id BIGINT NULL REFERENCES contracting_subcontracts(id) ON DELETE SET NULL,
        submission_date DATE NOT NULL DEFAULT CURRENT_DATE,
        review_due_date DATE NULL,
        consultant_review_date DATE NULL,
        status TEXT NOT NULL DEFAULT 'submitted',
        consultant_name TEXT NULL,
        consultant_comments TEXT NULL,
        attachments TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_contracting_submittal_tenant_num UNIQUE (tenant_id, submittal_number)
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_submittals_proj_status 
      ON contracting_submittals (tenant_id, project_id, status);
    `.execute(db);

    // 2. Material Price Escalation Claims (حاسبة ومطالبات فروق أسعار الخامات والتعويضات)
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_material_escalations (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        project_id BIGINT NOT NULL REFERENCES contracting_projects(id) ON DELETE CASCADE,
        claim_number TEXT NOT NULL,
        material_type TEXT NOT NULL DEFAULT 'rebar_steel',
        material_name TEXT NOT NULL DEFAULT '',
        base_price_contract NUMERIC(15, 3) NOT NULL DEFAULT 0,
        current_market_price NUMERIC(15, 3) NOT NULL DEFAULT 0,
        price_difference NUMERIC(15, 3) NOT NULL DEFAULT 0,
        executed_quantity NUMERIC(15, 3) NOT NULL DEFAULT 0,
        unit TEXT NOT NULL DEFAULT 'ton',
        total_compensation_amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        bulletin_source_reference TEXT NULL,
        status TEXT NOT NULL DEFAULT 'draft',
        ipc_invoice_id BIGINT NULL REFERENCES contracting_invoices(id) ON DELETE SET NULL,
        notes TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_contracting_escalation_tenant_num UNIQUE (tenant_id, claim_number)
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_escalation_proj 
      ON contracting_material_escalations (tenant_id, project_id, status);
    `.execute(db);

    // 3. Subcontractor Back-Charges (سندات الخصومات المحملة على مقاولي الباطن)
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_subcontractor_backcharges (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        project_id BIGINT NOT NULL REFERENCES contracting_projects(id) ON DELETE CASCADE,
        voucher_number TEXT NOT NULL,
        subcontract_id BIGINT NOT NULL REFERENCES contracting_subcontracts(id) ON DELETE CASCADE,
        beneficiary_subcontract_id BIGINT NULL REFERENCES contracting_subcontracts(id) ON DELETE SET NULL,
        backcharge_category TEXT NOT NULL DEFAULT 'damage_rework',
        amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        description TEXT NOT NULL,
        occurrence_date DATE NOT NULL DEFAULT CURRENT_DATE,
        status TEXT NOT NULL DEFAULT 'pending_approval',
        applied_ipc_invoice_id BIGINT NULL REFERENCES contracting_invoices(id) ON DELETE SET NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_contracting_backcharge_tenant_num UNIQUE (tenant_id, voucher_number)
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_backcharges_sub 
      ON contracting_subcontractor_backcharges (tenant_id, subcontract_id, status);
    `.execute(db);

    // 4. Equipment Fuel & Meter Operating Logs (سجل عدادات المعدات واستهلاك السولار)
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_equipment_fuel_logs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        project_id BIGINT NOT NULL REFERENCES contracting_projects(id) ON DELETE CASCADE,
        equipment_id BIGINT NULL REFERENCES contracting_equipment_assets(id) ON DELETE SET NULL,
        equipment_name TEXT NOT NULL DEFAULT '',
        log_date DATE NOT NULL DEFAULT CURRENT_DATE,
        start_meter_hours NUMERIC(10, 2) NOT NULL DEFAULT 0,
        end_meter_hours NUMERIC(10, 2) NOT NULL DEFAULT 0,
        operating_hours NUMERIC(10, 2) NOT NULL DEFAULT 0,
        fuel_liters_added NUMERIC(10, 2) NOT NULL DEFAULT 0,
        fuel_cost_total NUMERIC(15, 3) NOT NULL DEFAULT 0,
        driver_operator_name TEXT NULL,
        boq_item_id BIGINT NULL REFERENCES contracting_boq_items(id) ON DELETE SET NULL,
        notes TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_fuel_logs_proj 
      ON contracting_equipment_fuel_logs (tenant_id, project_id, log_date);
    `.execute(db);
  },

  async down(db: Kysely<unknown>): Promise<void> {
    await sql`DROP TABLE IF EXISTS contracting_equipment_fuel_logs CASCADE`.execute(db);
    await sql`DROP TABLE IF EXISTS contracting_subcontractor_backcharges CASCADE`.execute(db);
    await sql`DROP TABLE IF EXISTS contracting_material_escalations CASCADE`.execute(db);
    await sql`DROP TABLE IF EXISTS contracting_submittals CASCADE`.execute(db);
  },
};
