import { sql, type Kysely } from 'kysely';

// Closes the "Freight Audit & Rate Reconciliation" gap:
// Shipping lines (Maersk, MSC, CMA CGM, etc.) frequently issue invoices with
// unexpected surcharges or rates differing from negotiated contracts (Rate Cards).
// This migration introduces:
// 1. maritime_carrier_invoices: tracks carrier invoices, automatically audited
//    against active rate cards for the lane/container, recording variance and
//    enforcing maker-checker overrides for overcharges.
// 2. maritime_carrier_disputes: formal dispute tracking with shipping lines
//    demanding credit notes before invoice release.
export const migration = {
  async up(db: Kysely<unknown>): Promise<void> {
    await sql`
      CREATE TABLE IF NOT EXISTS maritime_carrier_invoices (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        job_id BIGINT NOT NULL REFERENCES maritime_jobs(id) ON DELETE CASCADE,
        shipping_line_id BIGINT NULL REFERENCES shipping_lines(id) ON DELETE SET NULL,
        carrier_name TEXT NOT NULL DEFAULT '',
        invoice_number TEXT NOT NULL,
        invoice_date DATE NOT NULL DEFAULT CURRENT_DATE,
        currency TEXT NOT NULL DEFAULT 'USD',
        total_invoiced_amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        ocean_freight NUMERIC(15, 3) NOT NULL DEFAULT 0,
        thc_charges NUMERIC(15, 3) NOT NULL DEFAULT 0,
        baf_charges NUMERIC(15, 3) NOT NULL DEFAULT 0,
        detention_demurrage NUMERIC(15, 3) NOT NULL DEFAULT 0,
        other_charges NUMERIC(15, 3) NOT NULL DEFAULT 0,
        rate_card_id BIGINT NULL REFERENCES maritime_rate_cards(id) ON DELETE SET NULL,
        contracted_amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        variance_amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        variance_pct NUMERIC(8, 2) NOT NULL DEFAULT 0,
        audit_status TEXT NOT NULL DEFAULT 'pending',
        override_approved_by BIGINT NULL,
        override_approved_at TIMESTAMPTZ NULL,
        override_reason TEXT NULL,
        journal_entry_id BIGINT NULL REFERENCES journal_entries(id) ON DELETE SET NULL,
        payment_status TEXT NOT NULL DEFAULT 'unpaid',
        notes TEXT NULL,
        created_by BIGINT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT chk_carrier_inv_audit_status CHECK (audit_status IN ('pending', 'matched', 'overcharge', 'undercharge', 'no_contract', 'approved_override', 'disputed')),
        CONSTRAINT chk_carrier_inv_payment_status CHECK (payment_status IN ('unpaid', 'partially_paid', 'paid', 'held_for_dispute'))
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_carrier_invoices_job
      ON maritime_carrier_invoices (tenant_id, job_id);
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_carrier_invoices_audit
      ON maritime_carrier_invoices (tenant_id, audit_status);
    `.execute(db);

    await sql`
      CREATE TABLE IF NOT EXISTS maritime_carrier_disputes (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        dispute_number TEXT NOT NULL,
        invoice_id BIGINT NOT NULL REFERENCES maritime_carrier_invoices(id) ON DELETE CASCADE,
        job_id BIGINT NOT NULL REFERENCES maritime_jobs(id) ON DELETE CASCADE,
        carrier_name TEXT NOT NULL DEFAULT '',
        disputed_amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        currency TEXT NOT NULL DEFAULT 'USD',
        dispute_reason TEXT NOT NULL DEFAULT '',
        dispute_status TEXT NOT NULL DEFAULT 'submitted',
        resolution_notes TEXT NULL,
        credit_note_number TEXT NULL,
        credit_note_amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        created_by BIGINT NULL,
        resolved_by BIGINT NULL,
        resolved_at TIMESTAMPTZ NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT chk_carrier_dispute_status CHECK (dispute_status IN ('draft', 'submitted', 'accepted', 'rejected', 'partially_accepted'))
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_carrier_disputes_inv
      ON maritime_carrier_disputes (tenant_id, invoice_id);
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_carrier_disputes_job
      ON maritime_carrier_disputes (tenant_id, job_id);
    `.execute(db);
  },

  async down(db: Kysely<unknown>): Promise<void> {
    await sql`DROP TABLE IF EXISTS maritime_carrier_disputes;`.execute(db);
    await sql`DROP TABLE IF EXISTS maritime_carrier_invoices;`.execute(db);
  },
};
