import { sql, type Kysely } from 'kysely';

export const migration = {
  async up(db: Kysely<unknown>): Promise<void> {
    // 1. Create cost_centers table
    await sql`
      CREATE TABLE IF NOT EXISTS cost_centers (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        code TEXT NOT NULL,
        name TEXT NOT NULL,
        parent_id BIGINT NULL REFERENCES cost_centers(id) ON DELETE SET NULL,
        is_active BOOLEAN NOT NULL DEFAULT TRUE,
        description TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_cost_centers_tenant_code UNIQUE (tenant_id, code)
      );
    `.execute(db);

    await sql`
      ALTER TABLE cost_centers 
      ADD COLUMN IF NOT EXISTS parent_id BIGINT NULL REFERENCES cost_centers(id) ON DELETE SET NULL;
    `.execute(db);

    await sql`
      ALTER TABLE cost_centers 
      ADD COLUMN IF NOT EXISTS description TEXT NULL;
    `.execute(db);

    // 2. Indexes for cost_centers
    await sql`
      CREATE INDEX IF NOT EXISTS idx_cost_centers_tenant 
      ON cost_centers (tenant_id);
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_cost_centers_parent 
      ON cost_centers (tenant_id, parent_id);
    `.execute(db);

    // 3. Add cost_center_id to journal_entry_lines
    await sql`
      ALTER TABLE journal_entry_lines 
      ADD COLUMN IF NOT EXISTS cost_center_id BIGINT NULL REFERENCES cost_centers(id) ON DELETE SET NULL;
    `.execute(db);

    // 4. Index for cost_center_id on journal_entry_lines
    await sql`
      CREATE INDEX IF NOT EXISTS idx_je_lines_tenant_cost_center 
      ON journal_entry_lines (tenant_id, cost_center_id) 
      WHERE cost_center_id IS NOT NULL;
    `.execute(db);
  },

  async down(db: Kysely<unknown>): Promise<void> {
    await sql`DROP INDEX IF EXISTS idx_je_lines_tenant_cost_center;`.execute(db);
    await sql`ALTER TABLE journal_entry_lines DROP COLUMN IF EXISTS cost_center_id;`.execute(db);
    await sql`DROP INDEX IF EXISTS idx_cost_centers_parent;`.execute(db);
    await sql`DROP INDEX IF EXISTS idx_cost_centers_tenant;`.execute(db);
    await sql`DROP TABLE IF EXISTS cost_centers;`.execute(db);
  },
};
