import { sql, type Kysely } from 'kysely';

export const migration = {
  async up(db: Kysely<unknown>): Promise<void> {
    // 1. Master BOQ Library Table
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_master_boq_library (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        trade_category TEXT NOT NULL,
        trade_name_ar TEXT NOT NULL,
        item_code TEXT NOT NULL,
        name TEXT NOT NULL,
        description TEXT NOT NULL DEFAULT '',
        unit TEXT NOT NULL DEFAULT 'm3',
        standard_cost NUMERIC(15, 3) NOT NULL DEFAULT 0,
        standard_price NUMERIC(15, 3) NOT NULL DEFAULT 0,
        is_active BOOLEAN NOT NULL DEFAULT true,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_contracting_master_boq_tenant_code UNIQUE (tenant_id, item_code)
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_master_boq_tenant_trade 
      ON contracting_master_boq_library (tenant_id, trade_category);
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_master_boq_search 
      ON contracting_master_boq_library (tenant_id, item_code, name);
    `.execute(db);

    // 2. Pre-seed Multi-Trade Items
    const seedItems = [
  {
    "code": "CIV-001",
    "name": "حفر في تربة رملية أو طينية وتطهير الموقع",
    "trade": "civil_concrete",
    "tradeAr": "الأعمال المدنية والخرسانات",
    "unit": "m3",
    "cost": 90,
    "price": 140,
    "desc": "حفر وتطهير ونقل المخلفات للمقالب العمومية المعتمدة مع سند الجوانب"
  },
  {
    "code": "CIV-002",
    "name": "حفر في تربة صخرية مع التكسير والترحيل",
    "trade": "civil_concrete",
    "tradeAr": "الأعمال المدنية والخرسانات",
    "unit": "m3",
    "cost": 260,
    "price": 380,
    "desc": "استخدام الدقاقات الهيدروليكية والتكسير والترحيل خارج حدود الموقع"
  },
  {
    "code": "CIV-003",
    "name": "طبقة إحلال من الرمل المتدرج والسن المدموك",
    "trade": "civil_concrete",
    "tradeAr": "الأعمال المدنية والخرسانات",
    "unit": "m3",
    "cost": 320,
    "price": 460,
    "desc": "توريد وفرش ودمك طبقات إحلال سمك 25 سم مع اختبارات بروكتور القياسية"
  },
  {
    "code": "CIV-004",
    "name": "خرسانة عادية للفرشات والأساسات محتوى 250 كجم",
    "trade": "civil_concrete",
    "tradeAr": "الأعمال المدنية والخرسانات",
    "unit": "m3",
    "cost": 1650,
    "price": 2200,
    "desc": "خلط وصب ودمك خرسانة عادية إجهاد 200 كجم/سم2 سمك 20 سم"
  },
  {
    "code": "CIV-005",
    "name": "خرسانة مسلحة للقواعد واللبشة محتوى 350 كجم SRC",
    "trade": "civil_concrete",
    "tradeAr": "الأعمال المدنية والخرسانات",
    "unit": "m3",
    "cost": 3850,
    "price": 5100,
    "desc": "خرسانة جاهزة بأسمنت مقاوم للكبريتات شاملة النجارة والحدادة والصب والدمك"
  },
  {
    "code": "CIV-006",
    "name": "خرسانة مسلحة للأعمدة والحوائط الخرسانية 400 كجم",
    "trade": "civil_concrete",
    "tradeAr": "الأعمال المدنية والخرسانات",
    "unit": "m3",
    "cost": 4400,
    "price": 5900,
    "desc": "خرسانة مسلحة إجهاد 350 كجم/سم2 شاملة الشدات الخشبية والتقويات والحديد"
  },
  {
    "code": "CIV-007",
    "name": "خرسانة مسلحة للأسقف والكمرات بلاطات مصمتة/فلات",
    "trade": "civil_concrete",
    "tradeAr": "الأعمال المدنية والخرسانات",
    "unit": "m3",
    "cost": 4100,
    "price": 5500,
    "desc": "شاملة حديد التسليح والشدة المعدنية ومعالجة الخرسانة بالرش بالمياه"
  },
  {
    "code": "CIV-008",
    "name": "خوازيق خرسانية ساندة/عاملة قطر 50-60 سم CFA",
    "trade": "civil_concrete",
    "tradeAr": "الأعمال المدنية والخرسانات",
    "unit": "m",
    "cost": 1100,
    "price": 1550,
    "desc": "حفر مستمر وصب بضغط البنتونيت وتنزيل القفص الحديدي حتى العمق التصميمي"
  },
  {
    "code": "MAS-001",
    "name": "مباني طوب أسمنتي مصمت سمك 25 سم لقصية الردم",
    "trade": "masonry_insulation",
    "tradeAr": "أعمال المباني والعزل",
    "unit": "m2",
    "cost": 260,
    "price": 360,
    "desc": "بناء بمونة أسمنتية بنسبة 350 كجم أسمنت لكل م3 رمل"
  },
  {
    "code": "MAS-002",
    "name": "مباني طوب طفلي مفرغ سمك 12 سم للقواطع الداخلية",
    "trade": "masonry_insulation",
    "tradeAr": "أعمال المباني والعزل",
    "unit": "m2",
    "cost": 150,
    "price": 220,
    "desc": "قواطع حوائط شاملة الكانات والتشحيط بالمونة تحت الكمرات"
  },
  {
    "code": "MAS-003",
    "name": "مباني طوب خفيف عازل AAC سمك 20 سم",
    "trade": "masonry_insulation",
    "tradeAr": "أعمال المباني والعزل",
    "unit": "m2",
    "cost": 310,
    "price": 440,
    "desc": "بناء طوب أوتوكلاف خفيف عازل حرارياً بالمونة الخاصة المعتمدة"
  },
  {
    "code": "MAS-004",
    "name": "عزل مائي بيتومين مؤكسد على الساخن طبقتين للأساسات",
    "trade": "masonry_insulation",
    "tradeAr": "أعمال المباني والعزل",
    "unit": "m2",
    "cost": 55,
    "price": 85,
    "desc": "دهان وجه تحضيري بارد ثم طبقتين بيتومين مؤكسد ساخن متعامدتين"
  },
  {
    "code": "MAS-005",
    "name": "عزل رطوبة ممبرين بوليستر 4 مم للحمامات والأسطح",
    "trade": "masonry_insulation",
    "tradeAr": "أعمال المباني والعزل",
    "unit": "m2",
    "cost": 180,
    "price": 260,
    "desc": "لفائف بيتومين مسلحة بالبوليستر 4 مم بركوب 10 سم مع الوزرات واختبار الغمر"
  },
  {
    "code": "MAS-006",
    "name": "عزل حراري بألواح بوليسترين مبثوق XPS سمك 5 سم",
    "trade": "masonry_insulation",
    "tradeAr": "أعمال المباني والعزل",
    "unit": "m2",
    "cost": 140,
    "price": 200,
    "desc": "ألواح فوم أزرق كثافة 35 كجم/م3 للأسطح مع طبقة النسيج الجيوتكستيل"
  },
  {
    "code": "FIN-001",
    "name": "بياض محارة داخلي حوائط وأسقف (بؤج وأوتار)",
    "trade": "finishes",
    "tradeAr": "أعمال التشطيبات والديكور",
    "unit": "m2",
    "cost": 85,
    "price": 130,
    "desc": "طرطشة مسمارية + بؤج وأوتار ليزر + بطانة وضهارة ناعمة واستلام بالقدة"
  },
  {
    "code": "FIN-002",
    "name": "بياض واجهات خارجية ملون جرافيتو معتمد",
    "trade": "finishes",
    "tradeAr": "أعمال التشطيبات والديكور",
    "unit": "m2",
    "cost": 160,
    "price": 240,
    "desc": "محارة واجهات بمواد عازلة ومقاومة للعوامل الجوية مع تشطيب جرافيتو"
  },
  {
    "code": "FIN-003",
    "name": "توريد وتركيب سيراميك أرضيات فرز أول",
    "trade": "finishes",
    "tradeAr": "أعمال التشطيبات والديكور",
    "unit": "m2",
    "cost": 220,
    "price": 320,
    "desc": "شامل فرشة الرمل ومونة اللصق والسقية بالروبة الملونة"
  },
  {
    "code": "FIN-004",
    "name": "توريد وتركيب بورسلين أرضيات قطع ليزر",
    "trade": "finishes",
    "tradeAr": "أعمال التشطيبات والديكور",
    "unit": "m2",
    "cost": 380,
    "price": 540,
    "desc": "تركيب بمادة لصق سيراميك خاصة وفواصل صليبة 2 مم مع الكلبسات"
  },
  {
    "code": "FIN-005",
    "name": "توريد وتركيب رخام درج وسلالم تريستا أو جلالة",
    "trade": "finishes",
    "tradeAr": "أعمال التشطيبات والديكور",
    "unit": "m",
    "cost": 350,
    "price": 500,
    "desc": "نائمة سمك 4 سم وقائمة سمك 2 سم مع الشطف والفرز والتلميع"
  },
  {
    "code": "FIN-006",
    "name": "دهانات داخلية سيلر + 3 سكينات معجون + وجهين بلاستيك",
    "trade": "finishes",
    "tradeAr": "أعمال التشطيبات والديكور",
    "unit": "m2",
    "cost": 75,
    "price": 115,
    "desc": "دهان بلاستيك نصف لامع قابل للغسيل شامل الصنفرة والتلقيط"
  },
  {
    "code": "FIN-007",
    "name": "أسقف معلقة جبسوم بورد فلات شامل الشاش والمعجون",
    "trade": "finishes",
    "tradeAr": "أعمال التشطيبات والديكور",
    "unit": "m2",
    "cost": 230,
    "price": 340,
    "desc": "ألواح كناوف 12.5 مم وهيكل صاج مجلفن محمل 0.5 مم مع أوميجا وزوايا"
  },
  {
    "code": "FIN-008",
    "name": "أسقف جبسوم بورد مقاوم للرطوبة (أخضر) للحمامات والمطابخ",
    "trade": "finishes",
    "tradeAr": "أعمال التشطيبات والديكور",
    "unit": "m2",
    "cost": 270,
    "price": 390,
    "desc": "ألواح كناوف خضراء عازلة للرطوبة شاملة فتحات الإنارة والتهوية"
  },
  {
    "code": "ELE-001",
    "name": "مخرج نقطة إنارة عادية شاملة المواسير والأسلاك والشاسيه",
    "trade": "electrical",
    "tradeAr": "أعمال الكهرباء والإنارة",
    "unit": "point",
    "cost": 160,
    "price": 250,
    "desc": "خراطيم مصطفى محمود وسلك سويدي معتمد 2 مم وشاسيه ولقمة ماجيك"
  },
  {
    "code": "ELE-002",
    "name": "مخرج نقطة بريزة قوى 16 أمبير ماجيك شاملة التغذية",
    "trade": "electrical",
    "tradeAr": "أعمال الكهرباء والإنارة",
    "unit": "point",
    "cost": 190,
    "price": 290,
    "desc": "سلك سويدي نحاس معتمد 3 مم مع خط أرضي وشاسيه وش الماجيك"
  },
  {
    "code": "ELE-003",
    "name": "مخرج قوى تكييف أو سخان 20-32 أمبير مع مفتاح دبل بول",
    "trade": "electrical",
    "tradeAr": "أعمال الكهرباء والإنارة",
    "unit": "point",
    "cost": 320,
    "price": 470,
    "desc": "تغذية مباشرة من اللوحة بسلك 4 مم أو 6 مم مع مفتاح قاطع حماية"
  },
  {
    "code": "ELE-004",
    "name": "توريد وتركيب لوحة توزيع رئيسية 24 خط بالقواطع",
    "trade": "electrical",
    "tradeAr": "أعمال الكهرباء والإنارة",
    "unit": "pcs",
    "cost": 4200,
    "price": 6200,
    "desc": "لوحة صاج شنايدر أو فينوس شاملة القاطع الرئيسي 63A والقواطع الفرعية"
  },
  {
    "code": "ELE-005",
    "name": "توريد وتركيب لوحة توزيع فرعية 12 خط",
    "trade": "electrical",
    "tradeAr": "أعمال الكهرباء والإنارة",
    "unit": "pcs",
    "cost": 2300,
    "price": 3400,
    "desc": "شاملة القواطع الأوتوماتيكية MCB والبارات النحاسية والروزتات"
  },
  {
    "code": "ELE-006",
    "name": "توريد ومد كابل نحاس معزول 4×16 مم2 داخل مواسير",
    "trade": "electrical",
    "tradeAr": "أعمال الكهرباء والإنارة",
    "unit": "m",
    "cost": 380,
    "price": 520,
    "desc": "كابل السويدي نحاس معزول PVC/XLPE 0.6/1KV مسلح أو غير مسلح"
  },
  {
    "code": "ELE-007",
    "name": "توريد وتركيب كشاف ليد 60×60 سم غاطس 40 وات معتمد",
    "trade": "electrical",
    "tradeAr": "أعمال الكهرباء والإنارة",
    "unit": "pcs",
    "cost": 360,
    "price": 530,
    "desc": "كشاف إضاءة مكتبية بدون فليكر مع المحول والضمان سنتين"
  },
  {
    "code": "ELE-008",
    "name": "توريد وتركيب سبوت لايت ليد 7 وات غاطس بالجبس",
    "trade": "electrical",
    "tradeAr": "أعمال الكهرباء والإنارة",
    "unit": "pcs",
    "cost": 65,
    "price": 110,
    "desc": "سبوت متحرك ليد أبيض/ورم شامل اللمبة والترانس والتركيب"
  },
  {
    "code": "ELV-001",
    "name": "مخرج نقطة شبكة وداتا Cat6 مع التيست والترقيم",
    "trade": "smart_systems_elv",
    "tradeAr": "الأنظمة الذكية والإلكترونيات والـ ELV",
    "unit": "point",
    "cost": 210,
    "price": 320,
    "desc": "كابل Cat6 UTP 3M/Legrand مع فيش RJ45 والباتش بانل والإنهاء"
  },
  {
    "code": "ELV-002",
    "name": "مخرج نقطة كاميرا مراقبة خارجية IP بدقة 5 ميجابكسل",
    "trade": "smart_systems_elv",
    "tradeAr": "الأنظمة الذكية والإلكترونيات والـ ELV",
    "unit": "point",
    "cost": 350,
    "price": 520,
    "desc": "تمديد كابل Cat6 وشبكة PoE وبوكس الحماية المقاوم للعوامل الجوية"
  },
  {
    "code": "ELV-003",
    "name": "توريد وبرمجة كاميرا مراقبة شبكية Dome IP دقة 5MP",
    "trade": "smart_systems_elv",
    "tradeAr": "الأنظمة الذكية والإلكترونيات والـ ELV",
    "unit": "pcs",
    "cost": 1100,
    "price": 1600,
    "desc": "كاميرا هيكفيجن أو داهوا برؤية ليلية بالأشعة تحت الحمراء وميكروفون"
  },
  {
    "code": "ELV-004",
    "name": "مخرج نقطة كاشف دخان وحرارة لشبكة إنذار الحريق",
    "trade": "smart_systems_elv",
    "tradeAr": "الأنظمة الذكية والإلكترونيات والـ ELV",
    "unit": "point",
    "cost": 280,
    "price": 420,
    "desc": "سلك مقاوم للحريق Fire Rated 2x1.5mm2 داخل مواسير EMT مع القاعدة"
  },
  {
    "code": "ELV-005",
    "name": "لوحة تحكم إنذار حريق معنونة 2 لوب Addressable",
    "trade": "smart_systems_elv",
    "tradeAr": "الأنظمة الذكية والإلكترونيات والـ ELV",
    "unit": "pcs",
    "cost": 18500,
    "price": 26000,
    "desc": "لوحة إنذار معنونة تسع حتى 500 جهاز مع البطاريات الاحتياطية والبرمجة"
  },
  {
    "code": "ELV-006",
    "name": "نقطة سماعة ساوند سستم سقفية 6 وات شاملة التمديد",
    "trade": "smart_systems_elv",
    "tradeAr": "الأنظمة الذكية والإلكترونيات والـ ELV",
    "unit": "point",
    "cost": 290,
    "price": 440,
    "desc": "سماعة سقفية غاطسة مع سلك صوت شيلد ومحول ترانس 100V"
  },
  {
    "code": "ELV-007",
    "name": "مخرج نقطة إنتركم مرئي ديجيتال شاشة 7 بوصة بالألوان",
    "trade": "smart_systems_elv",
    "tradeAr": "الأنظمة الذكية والإلكترونيات والـ ELV",
    "unit": "point",
    "cost": 1600,
    "price": 2300,
    "desc": "شامل الكابلات والتهيئة وربط كالون الباب الكهربائي والإنهاء"
  },
  {
    "code": "ELV-008",
    "name": "لوحة تحكم وتحكم ذكي Smart Home للمفاتيح والتكييف",
    "trade": "smart_systems_elv",
    "tradeAr": "الأنظمة الذكية والإلكترونيات والـ ELV",
    "unit": "pcs",
    "cost": 8500,
    "price": 12500,
    "desc": "متحكم ذكي يدعم بروتوكول Zigbee / KNX للتحكم عبر الموبايل والحساسات"
  },
  {
    "code": "PLU-001",
    "name": "مخرج نقطة تغذية مياه بولي بروبلين PPR قطر 3/4 بوصة",
    "trade": "plumbing",
    "tradeAr": "الأعمال الصحية والسباكة",
    "unit": "point",
    "cost": 180,
    "price": 280,
    "desc": "مواسير وقطع بولي بروبلين الشريف أو أكواثيرم واختبار ضغط 15 بار"
  },
  {
    "code": "PLU-002",
    "name": "مخرج نقطة صرف صحي أبيض ثقيل PVC سمك 1.5-2 بوصة",
    "trade": "plumbing",
    "tradeAr": "الأعمال الصحية والسباكة",
    "unit": "point",
    "cost": 150,
    "price": 230,
    "desc": "تمديدات صرف الحوض والغسالة والبانيو شاملة الجلب والسيفونات"
  },
  {
    "code": "PLU-003",
    "name": "قائم صرف عمومي ثقيل PVC قطر 4 بوصة للمخلفات",
    "trade": "plumbing",
    "tradeAr": "الأعمال الصحية والسباكة",
    "unit": "m",
    "cost": 220,
    "price": 330,
    "desc": "شامل كيعان الباب والأفزان الحديدية والوصلات والمناور"
  },
  {
    "code": "PLU-004",
    "name": "قائم صرف مطر وتهوية PVC قطر 3 بوصة",
    "trade": "plumbing",
    "tradeAr": "الأعمال الصحية والسباكة",
    "unit": "m",
    "cost": 170,
    "price": 260,
    "desc": "شامل الجرجوري على السطح وشبك منع القوارض والتثبيت"
  },
  {
    "code": "PLU-005",
    "name": "توريد وتركيب غرفة تفتيش خرسانية 60×60 سم بغطاء زهر",
    "trade": "plumbing",
    "tradeAr": "الأعمال الصحية والسباكة",
    "unit": "pcs",
    "cost": 1400,
    "price": 2100,
    "desc": "خرسانة مسلحة مع المجرى المائل الانسيابي وغطاء زهر دكتايل محمل"
  },
  {
    "code": "PLU-006",
    "name": "توريد وتركيب طقم حمام كامل (مرحاض معلق + حوض + خلاطات)",
    "trade": "plumbing",
    "tradeAr": "الأعمال الصحية والسباكة",
    "unit": "set",
    "cost": 5500,
    "price": 7800,
    "desc": "طقم إيديال ستاندرد أو ديورافيت مع خلاطات جروهي وسيفون دفن"
  },
  {
    "code": "PLU-007",
    "name": "توريد وتركيب مضخة مياه 1.5 حصان كالبيدا مع الفلوماك",
    "trade": "plumbing",
    "tradeAr": "الأعمال الصحية والسباكة",
    "unit": "pcs",
    "cost": 6800,
    "price": 9500,
    "desc": "مضخة رفع إيطالي أصلية شاملة محابس عدم الرجوع والفلوماك الإلكتروني"
  },
  {
    "code": "HVC-001",
    "name": "تأسيس مواسير نحاس تكييف كونسيلد مع العزل ومسار الصرف",
    "trade": "hvac_firefighting",
    "tradeAr": "التكييف والتهوية ومكافحة الحريق",
    "unit": "m",
    "cost": 320,
    "price": 460,
    "desc": "مواسير نحاس جنوب أفريقي أصلية مع عزل أرمفلكس وخرطوم صرف معزول"
  },
  {
    "code": "HVC-002",
    "name": "توريد وتركيب مجاري هواء صاج مجلفن Duct مع العزل",
    "trade": "hvac_firefighting",
    "tradeAr": "التكييف والتهوية ومكافحة الحريق",
    "unit": "m2",
    "cost": 420,
    "price": 620,
    "desc": "صاج مجلفن نيبون سمك 0.7-0.9 مم مع عزل صوف زجاجي داخلي وخارجي"
  },
  {
    "code": "HVC-003",
    "name": "جريلات مخارج ومداخل هواء ألومنيوم خطي Linear Bar",
    "trade": "hvac_firefighting",
    "tradeAr": "التكييف والتهوية ومكافحة الحريق",
    "unit": "m2",
    "cost": 580,
    "price": 850,
    "desc": "جريلات ألومنيوم دهان فرن إلكتروستاتيك مع الدامبر المنظم للتدفق"
  },
  {
    "code": "HVC-004",
    "name": "شبكة مواسير إطفاء حريق حديد أسود سيملس جدول 40 قطر 2 بوصة",
    "trade": "hvac_firefighting",
    "tradeAr": "التكييف والتهوية ومكافحة الحريق",
    "unit": "m",
    "cost": 480,
    "price": 690,
    "desc": "شامل اللحام والفتنج المعتمد واختبار الضغط الهيدروستاتيكي 20 بار"
  },
  {
    "code": "HVC-005",
    "name": "توريد وتركيب رشاش مياه حريق زجاجة حمراء 68C Sprinkler",
    "trade": "hvac_firefighting",
    "tradeAr": "التكييف والتهوية ومكافحة الحريق",
    "unit": "pcs",
    "cost": 130,
    "price": 210,
    "desc": "رشاش حريق UL/FM معتمد مع الوردة الديكورية للأسقف المعلقة"
  },
  {
    "code": "HVC-006",
    "name": "صندوق إطفاء حريق استانلس 1.5 بوصة خرطوم 30 متر كامل",
    "trade": "hvac_firefighting",
    "tradeAr": "التكييف والتهوية ومكافحة الحريق",
    "unit": "pcs",
    "cost": 4200,
    "price": 6000,
    "desc": "شامل بكرة الخرطوم والمحبس النحاس والقاذف والزجاج المقوى"
  },
  {
    "code": "STL-001",
    "name": "تصنيع وتركيب جمالونات وهياكل معدنية قطاعات مدرفلة",
    "trade": "steel_structures",
    "tradeAr": "الجمالونات والمنشآت المعدنية والحدادة",
    "unit": "ton",
    "cost": 52000,
    "price": 68000,
    "desc": "قطاعات IPE / HEA مع ألواح الربط والمسامير عالية المقاومة والدهان"
  },
  {
    "code": "STL-002",
    "name": "توريد وتركيب صاج ساندوتش بانل عازل للأسقف سمك 5 سم",
    "trade": "steel_structures",
    "tradeAr": "الجمالونات والمنشآت المعدنية والحدادة",
    "unit": "m2",
    "cost": 490,
    "price": 710,
    "desc": "بانل معزول بفوم بولي يوريثان كثافة 40 كجم/م3 شامل الإكسسوار والمزاريب"
  },
  {
    "code": "STL-003",
    "name": "درابزين سلالم وبلكونات حديد مشغول كريتال دهان دوكو",
    "trade": "steel_structures",
    "tradeAr": "الجمالونات والمنشآت المعدنية والحدادة",
    "unit": "m",
    "cost": 650,
    "price": 950,
    "desc": "شامل الخوص والزخارف واللحام والتثبيت الكيميائي في الخرسانة"
  },
  {
    "code": "FAC-001",
    "name": "باب خشب سويد قشرة أرو تجليد دهان أستر كامل",
    "trade": "doors_windows_facades",
    "tradeAr": "النجارة والألومنيوم والواجهات",
    "unit": "pcs",
    "cost": 3200,
    "price": 4600,
    "desc": "حلق زان وبرور وكالون كمبيوتر ومفصلات استانلس دهان أستر فاخر"
  },
  {
    "code": "FAC-002",
    "name": "شبابيك وأبواب ألومنيوم قطاع جامبو عازل للصوت بزجاج دبل",
    "trade": "doors_windows_facades",
    "tradeAr": "النجارة والألومنيوم والواجهات",
    "unit": "m2",
    "cost": 2400,
    "price": 3400,
    "desc": "قطاع جامبو شريف علي مع زجاج دبل جورجيا عاكس ومسكات إيطالي"
  },
  {
    "code": "FAC-003",
    "name": "واجهات زجاجية كرتن وول Curtain Wall زجاج سيكوريت عاكس",
    "trade": "doors_windows_facades",
    "tradeAr": "النجارة والألومنيوم والواجهات",
    "unit": "m2",
    "cost": 3800,
    "price": 5400,
    "desc": "قطاعات ألومنيوم رأسية وأفقية مع زجاج سيكوريت دبل عازل للحرارة والصوت"
  },
  {
    "code": "FAC-004",
    "name": "تجليد واجهات بألواح الكلادينج الألومنيوم المقاوم للحريق PVDF",
    "trade": "doors_windows_facades",
    "tradeAr": "النجارة والألومنيوم والواجهات",
    "unit": "m2",
    "cost": 1100,
    "price": 1600,
    "desc": "ألواح كلادينج سمك 4 مم طبقة ألومنيوم 0.5 مم على هيكل تيوبات حديد"
  },
  {
    "code": "LAN-001",
    "name": "توريد وتركيب بلاطات إنترلوك خرساني سمك 8 سم للمرور الثقيل",
    "trade": "landscape_infrastructure",
    "tradeAr": "الموقع العام والبنية التحتية واللاندسكيب",
    "unit": "m2",
    "cost": 170,
    "price": 250,
    "desc": "إجهاد 450 كجم/سم2 فرشة رمل مدموك وسقية رمل سيلكا واختبارات معملية"
  },
  {
    "code": "LAN-002",
    "name": "بردروات خرسانية عجالي للأرصفة 50×30×15 سم مع الدهان",
    "trade": "landscape_infrastructure",
    "tradeAr": "الموقع العام والبنية التحتية واللاندسكيب",
    "unit": "m",
    "cost": 130,
    "price": 190,
    "desc": "تركيب على فرشة خرسانية عادية مع حبسة خرسانة خلفية والدهان عاكس"
  },
  {
    "code": "LAN-003",
    "name": "طبقة أساس ورصف أسفلتي سمك 6 سم بعد الدمك",
    "trade": "landscape_infrastructure",
    "tradeAr": "الموقع العام والبنية التحتية واللاندسكيب",
    "unit": "m2",
    "cost": 280,
    "price": 410,
    "desc": "رش طبقة MC ثم فرش خلطة أسفلتية ساخنة والدمك بالهراس حتى الكثافة"
  },
  {
    "code": "LAN-004",
    "name": "شبكة ري حدائق بالرش والتنقيط مع المحابس الكهربائية Solenoid",
    "trade": "landscape_infrastructure",
    "tradeAr": "الموقع العام والبنية التحتية واللاندسكيب",
    "unit": "m2",
    "cost": 95,
    "price": 145,
    "desc": "مواسير بولي إيثيلين ورشاشات روتور ونقاطات ومتحكم ري أوتوماتيك"
  }
];

    for (const it of seedItems) {
      await sql`
        INSERT INTO contracting_master_boq_library (
          tenant_id, trade_category, trade_name_ar, item_code, name, description, unit, standard_cost, standard_price, is_active
        ) VALUES (
          '', ${it.trade}, ${it.tradeAr}, ${it.code}, ${it.name}, ${it.desc}, ${it.unit}, ${it.cost}, ${it.price}, true
        )
        ON CONFLICT (tenant_id, item_code) DO UPDATE SET
          name = EXCLUDED.name,
          description = EXCLUDED.description,
          trade_category = EXCLUDED.trade_category,
          trade_name_ar = EXCLUDED.trade_name_ar,
          unit = EXCLUDED.unit,
          standard_cost = EXCLUDED.standard_cost,
          standard_price = EXCLUDED.standard_price,
          updated_at = NOW();
      `.execute(db);
    }
  },

  async down(db: Kysely<unknown>): Promise<void> {
    await sql`DROP TABLE IF EXISTS contracting_master_boq_library CASCADE;`.execute(db);
  }
};
