import { Kysely, sql } from 'kysely';

export const migration = {
  async up(db: Kysely<unknown>): Promise<void> {
    await sql`CREATE TABLE IF NOT EXISTS sale_pharmacy_batch_allocations (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      tenant_id TEXT NOT NULL,
      account_id TEXT NOT NULL,
      sale_id BIGINT NOT NULL,
      sale_item_id BIGINT NOT NULL,
      product_id BIGINT NOT NULL,
      pharmacy_batch_id BIGINT NOT NULL,
      quantity NUMERIC(14, 3) NOT NULL CHECK (quantity > 0),
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )`.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_sale_pharmacy_batch_allocations_line
      ON sale_pharmacy_batch_allocations (tenant_id, sale_item_id, id)`.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_sale_pharmacy_batch_allocations_sale
      ON sale_pharmacy_batch_allocations (tenant_id, sale_id)`.execute(db);
  },

  async down(db: Kysely<unknown>): Promise<void> {
    await sql`DROP TABLE IF EXISTS sale_pharmacy_batch_allocations`.execute(db);
  },
};
