import { sql, type Kysely } from 'kysely';

// Closes two gaps found in the September 2026 Tier-1 construction ERP benchmark
// (vs Procore / CMiC / Autodesk Build): a real drawing/document register with
// revision history and a distribution log, and a meeting-minutes module with
// trackable action items. Both are net-new tables (no existing numbering debt
// to inherit), so numbering uses the collision-proof insert-temp-then-rename
// pattern (see insertPostedJournal), not COUNT(*)+1.
export const migration = {
  async up(db: Kysely<unknown>): Promise<void> {
    // 1. Document Register (drawings, specs, contracts, correspondence — one row per logical document)
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_documents (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        project_id BIGINT NOT NULL REFERENCES contracting_projects(id) ON DELETE CASCADE,
        doc_number TEXT NOT NULL,
        title TEXT NOT NULL,
        discipline TEXT NOT NULL DEFAULT 'architectural',
        doc_type TEXT NOT NULL DEFAULT 'drawing',
        current_revision_id BIGINT NULL,
        status TEXT NOT NULL DEFAULT 'draft',
        notes TEXT NULL,
        created_by BIGINT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_contracting_documents_tenant_num UNIQUE (tenant_id, doc_number),
        CONSTRAINT chk_contracting_documents_type CHECK (doc_type IN ('drawing', 'specification', 'contract', 'correspondence', 'method_statement', 'other')),
        CONSTRAINT chk_contracting_documents_status CHECK (status IN ('draft', 'for_review', 'approved', 'superseded', 'void'))
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_documents_tenant_project
      ON contracting_documents (tenant_id, project_id, status);
    `.execute(db);

    // 2. Document Revisions (full history — a document is never overwritten, only superseded)
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_document_revisions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        document_id BIGINT NOT NULL REFERENCES contracting_documents(id) ON DELETE CASCADE,
        rev_code TEXT NOT NULL,
        file_ref TEXT NULL,
        review_status TEXT NOT NULL DEFAULT 'for_review',
        issued_date DATE NOT NULL DEFAULT CURRENT_DATE,
        reviewed_by TEXT NULL,
        review_date DATE NULL,
        review_comments TEXT NULL,
        notes TEXT NULL,
        created_by BIGINT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_contracting_doc_revisions_doc_rev UNIQUE (tenant_id, document_id, rev_code),
        CONSTRAINT chk_contracting_doc_revisions_status CHECK (review_status IN ('for_review', 'approved', 'approved_as_noted', 'revise_resubmit', 'rejected', 'superseded'))
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_doc_revisions_document
      ON contracting_document_revisions (tenant_id, document_id, created_at DESC);
    `.execute(db);

    await sql`
      ALTER TABLE contracting_documents
      ADD CONSTRAINT fk_contracting_documents_current_revision
      FOREIGN KEY (current_revision_id) REFERENCES contracting_document_revisions(id) ON DELETE SET NULL;
    `.execute(db);

    // 3. Distribution Log (who received which revision, and how)
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_document_distributions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        document_id BIGINT NOT NULL REFERENCES contracting_documents(id) ON DELETE CASCADE,
        revision_id BIGINT NOT NULL REFERENCES contracting_document_revisions(id) ON DELETE CASCADE,
        recipient_name TEXT NOT NULL,
        recipient_role TEXT NOT NULL DEFAULT 'internal',
        distribution_method TEXT NOT NULL DEFAULT 'email',
        distributed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        acknowledged_at TIMESTAMPTZ NULL,
        notes TEXT NULL,
        created_by BIGINT NULL,
        CONSTRAINT chk_contracting_doc_dist_role CHECK (recipient_role IN ('internal', 'consultant', 'owner', 'subcontractor', 'authority', 'other'))
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_doc_distributions_revision
      ON contracting_document_distributions (tenant_id, revision_id);
    `.execute(db);

    // 4. Meeting Minutes
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_meeting_minutes (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        project_id BIGINT NOT NULL REFERENCES contracting_projects(id) ON DELETE CASCADE,
        minute_number TEXT NOT NULL,
        meeting_type TEXT NOT NULL DEFAULT 'site_progress',
        meeting_date DATE NOT NULL DEFAULT CURRENT_DATE,
        location TEXT NULL,
        attendees JSONB NOT NULL DEFAULT '[]'::jsonb,
        agenda TEXT NULL,
        summary TEXT NULL,
        prepared_by TEXT NULL,
        status TEXT NOT NULL DEFAULT 'draft',
        created_by BIGINT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_contracting_meeting_minutes_tenant_num UNIQUE (tenant_id, minute_number),
        CONSTRAINT chk_contracting_meeting_minutes_status CHECK (status IN ('draft', 'issued'))
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_meeting_minutes_project
      ON contracting_meeting_minutes (tenant_id, project_id, meeting_date DESC);
    `.execute(db);

    // 5. Meeting Action Items (trackable, optionally linked to an RFI or Change Order)
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_meeting_action_items (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        minute_id BIGINT NOT NULL REFERENCES contracting_meeting_minutes(id) ON DELETE CASCADE,
        description TEXT NOT NULL,
        owner_name TEXT NULL,
        due_date DATE NULL,
        status TEXT NOT NULL DEFAULT 'open',
        linked_rfi_id BIGINT NULL,
        linked_change_order_id BIGINT NULL,
        closed_at TIMESTAMPTZ NULL,
        notes TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT chk_contracting_meeting_action_status CHECK (status IN ('open', 'closed'))
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_meeting_action_items_minute
      ON contracting_meeting_action_items (tenant_id, minute_id, status);
    `.execute(db);
  },

  async down(db: Kysely<unknown>): Promise<void> {
    await sql`DROP TABLE IF EXISTS contracting_meeting_action_items;`.execute(db);
    await sql`DROP TABLE IF EXISTS contracting_meeting_minutes;`.execute(db);
    await sql`DROP TABLE IF EXISTS contracting_document_distributions;`.execute(db);
    await sql`ALTER TABLE contracting_documents DROP CONSTRAINT IF EXISTS fk_contracting_documents_current_revision;`.execute(db);
    await sql`DROP TABLE IF EXISTS contracting_document_revisions;`.execute(db);
    await sql`DROP TABLE IF EXISTS contracting_documents;`.execute(db);
  },
};
