import { sql, type Kysely } from 'kysely';

export const migration = {
  async up(db: Kysely<unknown>): Promise<void> {
    // 1. Create crm_deals table
    await sql`
      CREATE TABLE IF NOT EXISTS crm_deals (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        title TEXT NOT NULL,
        stage TEXT NOT NULL DEFAULT 'new',
        expected_amount NUMERIC(15, 4) NOT NULL DEFAULT 0,
        currency TEXT NOT NULL DEFAULT 'EGP',
        probability INTEGER NOT NULL DEFAULT 50,
        expected_close_date DATE NULL,
        contact_name TEXT NULL,
        contact_phone TEXT NULL,
        contact_email TEXT NULL,
        company_name TEXT NULL,
        source TEXT NOT NULL DEFAULT 'direct',
        priority TEXT NOT NULL DEFAULT 'medium',
        assigned_user_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
        customer_id BIGINT NULL REFERENCES customers(id) ON DELETE SET NULL,
        lost_reason TEXT NULL,
        notes TEXT NULL,
        created_by BIGINT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_crm_deals_tenant_stage 
      ON crm_deals (tenant_id, stage);
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_crm_deals_tenant_assigned 
      ON crm_deals (tenant_id, assigned_user_id);
    `.execute(db);

    // 2. Create crm_activities table
    await sql`
      CREATE TABLE IF NOT EXISTS crm_activities (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        deal_id BIGINT NOT NULL REFERENCES crm_deals(id) ON DELETE CASCADE,
        activity_type TEXT NOT NULL DEFAULT 'note',
        summary TEXT NOT NULL,
        due_date TIMESTAMPTZ NULL,
        is_completed BOOLEAN NOT NULL DEFAULT FALSE,
        created_by BIGINT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_crm_activities_deal 
      ON crm_activities (tenant_id, deal_id);
    `.execute(db);
  },

  async down(db: Kysely<unknown>): Promise<void> {
    await sql`DROP TABLE IF EXISTS crm_activities;`.execute(db);
    await sql`DROP TABLE IF EXISTS crm_deals;`.execute(db);
  },
};
