import { sql, type Kysely } from 'kysely';

export const migration = {
  async up(db: Kysely<unknown>): Promise<void> {
    // 1. Master Price List (أسعار السوق للخامات والمصنعيات والمعدات)
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_master_price_list (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        item_type TEXT NOT NULL DEFAULT 'material', -- material, labor, equipment, subcontract
        code TEXT NOT NULL,
        name TEXT NOT NULL,
        unit TEXT NOT NULL DEFAULT 'm3',
        unit_rate NUMERIC(15, 3) NOT NULL DEFAULT 0,
        category TEXT NOT NULL DEFAULT 'general',
        notes TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_contracting_price_list_tenant_code UNIQUE (tenant_id, code)
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_price_list_tenant_type 
      ON contracting_master_price_list (tenant_id, item_type);
    `.execute(db);

    // 2. Engineering Constants (الثوابت والمعادلات الهندسية وتحليل البنود)
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_engineering_constants (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        item_code TEXT NOT NULL,
        item_name TEXT NOT NULL,
        unit TEXT NOT NULL DEFAULT 'm3',
        waste_percent NUMERIC(5, 2) NOT NULL DEFAULT 5.00,
        overhead_percent NUMERIC(5, 2) NOT NULL DEFAULT 7.00,
        profit_markup_percent NUMERIC(5, 2) NOT NULL DEFAULT 15.00,
        components_json JSONB NOT NULL DEFAULT '[]'::jsonb,
        notes TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_contracting_constants_tenant_code UNIQUE (tenant_id, item_code)
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_constants_tenant 
      ON contracting_engineering_constants (tenant_id);
    `.execute(db);

    // 3. Cost Baseline Snapshots (تجميد تكلفة وميزانية المشروع)
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_cost_snapshots (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        project_id BIGINT NOT NULL REFERENCES contracting_projects(id) ON DELETE CASCADE,
        snapshot_name TEXT NOT NULL,
        total_budget_cost NUMERIC(15, 3) NOT NULL DEFAULT 0,
        total_contract_value NUMERIC(15, 3) NOT NULL DEFAULT 0,
        is_locked BOOLEAN NOT NULL DEFAULT true,
        locked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        locked_by TEXT NULL,
        boq_snapshot_json JSONB NOT NULL DEFAULT '[]'::jsonb,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_snapshots_project 
      ON contracting_cost_snapshots (tenant_id, project_id);
    `.execute(db);

    // 4. Retention & Guarantees Records (سجل ضمان الأعمال والمبالغ المحتجزة)
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_retention_records (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        project_id BIGINT NOT NULL REFERENCES contracting_projects(id) ON DELETE CASCADE,
        subcontract_id BIGINT NULL REFERENCES contracting_subcontracts(id) ON DELETE SET NULL,
        party_type TEXT NOT NULL DEFAULT 'subcontractor', -- client, subcontractor
        party_id BIGINT NULL,
        party_name TEXT NOT NULL DEFAULT '',
        held_amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        released_amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        retention_percent NUMERIC(5, 2) NOT NULL DEFAULT 5.00,
        ipc_invoice_id BIGINT NULL,
        release_due_date DATE NULL,
        status TEXT NOT NULL DEFAULT 'held', -- held, partially_released, fully_released
        guarantee_certificate_ref TEXT NULL,
        notes TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_retention_project 
      ON contracting_retention_records (tenant_id, project_id, status);
    `.execute(db);

    // 5. Payment Holds & Penalties (حجز دفعات لعيوب جودة أو تأخير)
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_payment_holds (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        project_id BIGINT NOT NULL REFERENCES contracting_projects(id) ON DELETE CASCADE,
        subcontract_id BIGINT NULL REFERENCES contracting_subcontracts(id) ON DELETE SET NULL,
        party_type TEXT NOT NULL DEFAULT 'subcontractor',
        party_name TEXT NOT NULL DEFAULT '',
        hold_amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        reason TEXT NOT NULL,
        defect_description TEXT NULL,
        is_released BOOLEAN NOT NULL DEFAULT false,
        released_at TIMESTAMPTZ NULL,
        released_by TEXT NULL,
        release_notes TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_holds_project 
      ON contracting_payment_holds (tenant_id, project_id, is_released);
    `.execute(db);

    // 6. Supplier Returns & Credit Notes (أذون مرتجع الخامات وإشعارات الدائن)
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_supplier_returns (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        project_id BIGINT NOT NULL REFERENCES contracting_projects(id) ON DELETE CASCADE,
        return_number TEXT NOT NULL,
        supplier_id BIGINT NULL REFERENCES suppliers(id) ON DELETE SET NULL,
        supplier_name TEXT NOT NULL DEFAULT '',
        return_date DATE NOT NULL DEFAULT CURRENT_DATE,
        total_amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        status TEXT NOT NULL DEFAULT 'posted', -- draft, posted
        credit_note_number TEXT NULL,
        items_json JSONB NOT NULL DEFAULT '[]'::jsonb,
        notes TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_contracting_supplier_returns_num UNIQUE (tenant_id, return_number)
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_supplier_returns_project 
      ON contracting_supplier_returns (tenant_id, project_id);
    `.execute(db);

    // 7. Site Labor Attendance & Split Allocation (اليوميات وتوزيع ساعات العمالة على المشاريع)
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_labor_attendance (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        project_id BIGINT NOT NULL REFERENCES contracting_projects(id) ON DELETE CASCADE,
        worker_name TEXT NOT NULL,
        trade TEXT NOT NULL DEFAULT 'carpenter', -- carpenter, blacksmith, mason, helper, operator, surveyor, electrician, plumber
        work_date DATE NOT NULL DEFAULT CURRENT_DATE,
        shift_type TEXT NOT NULL DEFAULT 'full_day',
        hours_worked NUMERIC(5, 2) NOT NULL DEFAULT 8.00,
        split_project_id BIGINT NULL REFERENCES contracting_projects(id) ON DELETE SET NULL,
        split_hours NUMERIC(5, 2) NOT NULL DEFAULT 0,
        daily_rate NUMERIC(15, 3) NOT NULL DEFAULT 0,
        total_wage NUMERIC(15, 3) NOT NULL DEFAULT 0,
        status TEXT NOT NULL DEFAULT 'recorded', -- recorded, approved, paid
        notes TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_labor_project_date 
      ON contracting_labor_attendance (tenant_id, project_id, work_date);
    `.execute(db);

    // 8. Petty Cash & Site Custody (العهد النقدية لمهندسي الموقع مع منع التكرار قبل الإغلاق)
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_petty_cash (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        project_id BIGINT NOT NULL REFERENCES contracting_projects(id) ON DELETE CASCADE,
        custodian_name TEXT NOT NULL,
        custodian_role TEXT NOT NULL DEFAULT 'site_engineer',
        disbursement_number TEXT NOT NULL,
        amount_given NUMERIC(15, 3) NOT NULL DEFAULT 0,
        amount_settled NUMERIC(15, 3) NOT NULL DEFAULT 0,
        remaining_balance NUMERIC(15, 3) NOT NULL DEFAULT 0,
        issue_date DATE NOT NULL DEFAULT CURRENT_DATE,
        settlement_due_date DATE NULL,
        status TEXT NOT NULL DEFAULT 'active', -- active, settled, overdue
        receipts_json JSONB NOT NULL DEFAULT '[]'::jsonb,
        closure_notes TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_contracting_petty_cash_num UNIQUE (tenant_id, disbursement_number)
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_petty_cash_project 
      ON contracting_petty_cash (tenant_id, project_id, status);
    `.execute(db);

    // 9. Government Licenses & Site Compliance (تراخيص وتصاريح المشروع الحكومية)
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_government_licenses (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        project_id BIGINT NOT NULL REFERENCES contracting_projects(id) ON DELETE CASCADE,
        license_type TEXT NOT NULL DEFAULT 'excavation', -- excavation, building, civil_defense, road_occupancy, environmental, other
        license_number TEXT NOT NULL,
        issuing_authority TEXT NOT NULL,
        issue_date DATE NULL,
        expiry_date DATE NOT NULL,
        fee_amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        status TEXT NOT NULL DEFAULT 'active', -- active, expiring_soon, expired, renewed
        document_url TEXT NULL,
        alert_lead_days INTEGER NOT NULL DEFAULT 30,
        notes TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_contracting_licenses_tenant_num UNIQUE (tenant_id, project_id, license_number)
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_licenses_expiry 
      ON contracting_government_licenses (tenant_id, project_id, expiry_date);
    `.execute(db);
  },

  async down(db: Kysely<unknown>): Promise<void> {
    await sql`DROP TABLE IF EXISTS contracting_government_licenses CASCADE;`.execute(db);
    await sql`DROP TABLE IF EXISTS contracting_petty_cash CASCADE;`.execute(db);
    await sql`DROP TABLE IF EXISTS contracting_labor_attendance CASCADE;`.execute(db);
    await sql`DROP TABLE IF EXISTS contracting_supplier_returns CASCADE;`.execute(db);
    await sql`DROP TABLE IF EXISTS contracting_payment_holds CASCADE;`.execute(db);
    await sql`DROP TABLE IF EXISTS contracting_retention_records CASCADE;`.execute(db);
    await sql`DROP TABLE IF EXISTS contracting_cost_snapshots CASCADE;`.execute(db);
    await sql`DROP TABLE IF EXISTS contracting_engineering_constants CASCADE;`.execute(db);
    await sql`DROP TABLE IF EXISTS contracting_master_price_list CASCADE;`.execute(db);
  },
};
