import { sql, type Kysely } from 'kysely';

export const migration = {
  async up(db: Kysely<unknown>): Promise<void> {
    // =========================================================================
    // 1. Ensure Composite Unique Constraints on Referenced Tables
    // =========================================================================
    await sql`
      DO $$
      BEGIN
        IF NOT EXISTS (
          SELECT 1 FROM pg_constraint WHERE conname = 'uq_contracting_projects_tenant_id'
        ) THEN
          ALTER TABLE contracting_projects
            ADD CONSTRAINT uq_contracting_projects_tenant_id UNIQUE (tenant_id, id);
        END IF;

        IF NOT EXISTS (
          SELECT 1 FROM pg_constraint WHERE conname = 'uq_contracting_boq_items_tenant_id'
        ) THEN
          ALTER TABLE contracting_boq_items
            ADD CONSTRAINT uq_contracting_boq_items_tenant_id UNIQUE (tenant_id, id);
        END IF;
      END $$;
    `.execute(db);

    // =========================================================================
    // 2. Add Cost Breakdown & True Actual Cost Columns to contracting_boq_items
    // =========================================================================
    await sql`
      DO $$
      BEGIN
        IF NOT EXISTS (
          SELECT 1 FROM information_schema.columns
          WHERE table_name = 'contracting_boq_items' AND column_name = 'allocated_indirect_cost'
        ) THEN
          ALTER TABLE contracting_boq_items
            ADD COLUMN allocated_indirect_cost NUMERIC(15, 3) NOT NULL DEFAULT 0,
            ADD COLUMN direct_labor_cost NUMERIC(15, 3) NOT NULL DEFAULT 0,
            ADD COLUMN direct_material_cost NUMERIC(15, 3) NOT NULL DEFAULT 0,
            ADD COLUMN direct_equipment_cost NUMERIC(15, 3) NOT NULL DEFAULT 0,
            ADD COLUMN total_actual_cost NUMERIC(15, 3) NOT NULL DEFAULT 0;
        END IF;
      END $$;
    `.execute(db);

    // =========================================================================
    // 3. Create contracting_cost_pools (AACE RP 10S-90 / 34R-05 4 Cost Pools)
    // =========================================================================
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_cost_pools (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        project_id BIGINT NOT NULL,
        pool_code TEXT NOT NULL,
        pool_name TEXT NOT NULL,
        pool_type TEXT NOT NULL DEFAULT 'labor_care',
        driver_type TEXT NOT NULL DEFAULT 'labor_days',
        description TEXT NULL,
        is_active BOOLEAN NOT NULL DEFAULT true,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_cost_pool_tenant_id UNIQUE (tenant_id, id),
        CONSTRAINT uq_cost_pool_tenant_proj_code UNIQUE (tenant_id, project_id, pool_code),
        CONSTRAINT chk_cost_pool_type CHECK (
          pool_type IN ('labor_care', 'labor_burden', 'equipment_shared', 'site_supervision', 'custom')
        ),
        CONSTRAINT chk_cost_pool_driver CHECK (
          driver_type IN ('labor_days', 'labor_cost', 'equipment_hours', 'direct_effort', 'manual_ratio')
        ),
        CONSTRAINT fk_cost_pools_project
          FOREIGN KEY (tenant_id, project_id)
          REFERENCES contracting_projects(tenant_id, id)
          ON DELETE CASCADE
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_cost_pools_proj 
      ON contracting_cost_pools (tenant_id, project_id, pool_type, is_active);
    `.execute(db);

    // =========================================================================
    // 4. Create contracting_allocation_batches (Monthly / Periodic Allocation Runs)
    // =========================================================================
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_allocation_batches (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        project_id BIGINT NOT NULL,
        batch_number TEXT NOT NULL,
        period_start DATE NOT NULL,
        period_end DATE NOT NULL,
        status TEXT NOT NULL DEFAULT 'draft',
        total_gross_expenses NUMERIC(15, 3) NOT NULL DEFAULT 0,
        total_recovered_backcharges NUMERIC(15, 3) NOT NULL DEFAULT 0,
        total_net_pool_cost NUMERIC(15, 3) NOT NULL DEFAULT 0,
        total_allocated_amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        deferred_in_amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        deferred_out_amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        posted_at TIMESTAMPTZ NULL,
        posted_by TEXT NULL,
        notes TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_allocation_batch_tenant_id UNIQUE (tenant_id, id),
        CONSTRAINT uq_allocation_batch_tenant_num UNIQUE (tenant_id, project_id, batch_number),
        CONSTRAINT chk_allocation_batch_status CHECK (status IN ('draft', 'posted', 'reversed')),
        CONSTRAINT fk_allocation_batches_project
          FOREIGN KEY (tenant_id, project_id)
          REFERENCES contracting_projects(tenant_id, id)
          ON DELETE CASCADE
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_alloc_batches_proj 
      ON contracting_allocation_batches (tenant_id, project_id, status, period_start);
    `.execute(db);

    // =========================================================================
    // 5. Create contracting_indirect_expenses (Expenses linked to Cost Pools)
    // =========================================================================
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_indirect_expenses (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        project_id BIGINT NOT NULL,
        pool_id BIGINT NOT NULL,
        batch_id BIGINT NULL,
        mobilization_expense_id BIGINT NULL REFERENCES contracting_site_mobilization_expenses(id) ON DELETE SET NULL,
        expense_title TEXT NOT NULL,
        gross_amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        recovered_amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        net_amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        expense_date DATE NOT NULL DEFAULT CURRENT_DATE,
        voucher_ref TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT fk_indirect_expenses_project
          FOREIGN KEY (tenant_id, project_id)
          REFERENCES contracting_projects(tenant_id, id)
          ON DELETE CASCADE,
        CONSTRAINT fk_indirect_expenses_pool
          FOREIGN KEY (tenant_id, pool_id)
          REFERENCES contracting_cost_pools(tenant_id, id)
          ON DELETE CASCADE
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_indirect_exp_pool 
      ON contracting_indirect_expenses (tenant_id, project_id, pool_id, batch_id);
    `.execute(db);

    // =========================================================================
    // 6. Create contracting_boq_indirect_allocations (Itemized Allocation Ledger)
    // =========================================================================
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_boq_indirect_allocations (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        project_id BIGINT NOT NULL,
        batch_id BIGINT NOT NULL,
        pool_id BIGINT NOT NULL,
        boq_item_id BIGINT NOT NULL,
        driver_type TEXT NOT NULL,
        driver_qty NUMERIC(15, 4) NOT NULL DEFAULT 0,
        total_pool_driver_qty NUMERIC(15, 4) NOT NULL DEFAULT 0,
        allocation_ratio NUMERIC(10, 6) NOT NULL DEFAULT 0,
        pool_net_cost NUMERIC(15, 3) NOT NULL DEFAULT 0,
        allocated_amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_boq_alloc_batch_pool_item UNIQUE (tenant_id, batch_id, pool_id, boq_item_id),
        CONSTRAINT fk_boq_alloc_project
          FOREIGN KEY (tenant_id, project_id)
          REFERENCES contracting_projects(tenant_id, id)
          ON DELETE CASCADE,
        CONSTRAINT fk_boq_alloc_batch
          FOREIGN KEY (tenant_id, batch_id)
          REFERENCES contracting_allocation_batches(tenant_id, id)
          ON DELETE CASCADE,
        CONSTRAINT fk_boq_alloc_pool
          FOREIGN KEY (tenant_id, pool_id)
          REFERENCES contracting_cost_pools(tenant_id, id)
          ON DELETE CASCADE,
        CONSTRAINT fk_boq_alloc_boq_item
          FOREIGN KEY (tenant_id, boq_item_id)
          REFERENCES contracting_boq_items(tenant_id, id)
          ON DELETE RESTRICT
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_boq_alloc_item 
      ON contracting_boq_indirect_allocations (tenant_id, boq_item_id);
      
      CREATE INDEX IF NOT EXISTS idx_contracting_boq_alloc_batch 
      ON contracting_boq_indirect_allocations (tenant_id, batch_id, pool_id);
    `.execute(db);
  },

  async down(db: Kysely<unknown>): Promise<void> {
    await sql`DROP TABLE IF EXISTS contracting_boq_indirect_allocations CASCADE;`.execute(db);
    await sql`DROP TABLE IF EXISTS contracting_indirect_expenses CASCADE;`.execute(db);
    await sql`DROP TABLE IF EXISTS contracting_allocation_batches CASCADE;`.execute(db);
    await sql`DROP TABLE IF EXISTS contracting_cost_pools CASCADE;`.execute(db);

    await sql`
      ALTER TABLE contracting_boq_items
        DROP COLUMN IF EXISTS allocated_indirect_cost,
        DROP COLUMN IF EXISTS direct_labor_cost,
        DROP COLUMN IF EXISTS direct_material_cost,
        DROP COLUMN IF EXISTS direct_equipment_cost,
        DROP COLUMN IF EXISTS total_actual_cost;
    `.execute(db);
  },
};
