import { Kysely, sql } from 'kysely';

export const migration = {
  up: async (db: Kysely<any>): Promise<void> => {
    await sql`
      CREATE TABLE IF NOT EXISTS fixed_assets (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        account_id TEXT NOT NULL DEFAULT '',
        code TEXT NOT NULL,
        name TEXT NOT NULL,
        category TEXT NOT NULL DEFAULT 'general',
        purchase_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        purchase_cost NUMERIC(15, 4) NOT NULL DEFAULT 0,
        salvage_value NUMERIC(15, 4) NOT NULL DEFAULT 0,
        useful_life_months INTEGER NOT NULL DEFAULT 60,
        depreciation_method TEXT NOT NULL DEFAULT 'straight_line',
        accumulated_depreciation NUMERIC(15, 4) NOT NULL DEFAULT 0,
        status TEXT NOT NULL DEFAULT 'active',
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_fixed_assets_tenant_status 
      ON fixed_assets (tenant_id, status);
    `.execute(db);

    await sql`
      CREATE TABLE IF NOT EXISTS asset_depreciation_logs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        account_id TEXT NOT NULL DEFAULT '',
        asset_id BIGINT NOT NULL REFERENCES fixed_assets(id) ON DELETE CASCADE,
        period_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        depreciation_amount NUMERIC(15, 4) NOT NULL DEFAULT 0,
        accumulated_amount NUMERIC(15, 4) NOT NULL DEFAULT 0,
        book_value NUMERIC(15, 4) NOT NULL DEFAULT 0,
        journal_entry_id BIGINT NULL,
        note TEXT NOT NULL DEFAULT '',
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_asset_depr_tenant_asset 
      ON asset_depreciation_logs (tenant_id, asset_id);
    `.execute(db);
  },

  down: async (db: Kysely<any>): Promise<void> => {
    await sql`DROP TABLE IF EXISTS asset_depreciation_logs`.execute(db);
    await sql`DROP TABLE IF EXISTS fixed_assets`.execute(db);
  },
};
