import { sql, type Kysely } from 'kysely';

export const migration = {
  async up(db: Kysely<unknown>): Promise<void> {
    // 1. BOQ CAD Takeoff Sheet (حصر كميات لوحات الكاد بالملي والأبعاد)
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_boq_takeoffs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        project_id BIGINT NOT NULL REFERENCES contracting_projects(id) ON DELETE CASCADE,
        boq_item_id BIGINT NOT NULL REFERENCES contracting_boq_items(id) ON DELETE CASCADE,
        drawing_ref TEXT NOT NULL DEFAULT '',
        axis_ref TEXT NOT NULL DEFAULT '',
        description TEXT NOT NULL DEFAULT '',
        length NUMERIC(15, 3) NOT NULL DEFAULT 0,
        width NUMERIC(15, 3) NOT NULL DEFAULT 0,
        height NUMERIC(15, 3) NOT NULL DEFAULT 0,
        count_multiplier NUMERIC(10, 2) NOT NULL DEFAULT 1,
        void_deduction NUMERIC(15, 3) NOT NULL DEFAULT 0,
        net_qty NUMERIC(15, 3) NOT NULL DEFAULT 0,
        waste_percent NUMERIC(5, 2) NOT NULL DEFAULT 0,
        total_with_waste NUMERIC(15, 3) NOT NULL DEFAULT 0,
        notes TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_takeoffs_boq 
      ON contracting_boq_takeoffs (tenant_id, boq_item_id);
    `.execute(db);

    // 2. Site Mobilization & Setup Expenses (مصاريف تجهيز الموقع وسكن العمال والمرافق)
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_site_mobilization_expenses (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        project_id BIGINT NOT NULL REFERENCES contracting_projects(id) ON DELETE CASCADE,
        expense_category TEXT NOT NULL DEFAULT 'worker_housing',
        title TEXT NOT NULL,
        amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        expense_date DATE NOT NULL DEFAULT CURRENT_DATE,
        paid_to TEXT NOT NULL DEFAULT '',
        payment_method TEXT NOT NULL DEFAULT 'petty_cash',
        reference_receipt TEXT NULL,
        notes TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_mobilization_proj 
      ON contracting_site_mobilization_expenses (tenant_id, project_id, expense_category);
    `.execute(db);

    // 3. Labor Attendance, Overtime & Deductions/Bonuses (كشوف يوميات العمالة والمشرفين والسهرات)
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_labor_attendance_records (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        project_id BIGINT NOT NULL REFERENCES contracting_projects(id) ON DELETE CASCADE,
        boq_item_id BIGINT NULL REFERENCES contracting_boq_items(id) ON DELETE SET NULL,
        worker_name TEXT NOT NULL,
        worker_role TEXT NOT NULL DEFAULT 'technician',
        attendance_date DATE NOT NULL DEFAULT CURRENT_DATE,
        status TEXT NOT NULL DEFAULT 'present',
        daily_base_wage NUMERIC(15, 3) NOT NULL DEFAULT 0,
        overtime_hours NUMERIC(6, 2) NOT NULL DEFAULT 0,
        overtime_rate_per_hour NUMERIC(15, 3) NOT NULL DEFAULT 0,
        night_shift_allowance NUMERIC(15, 3) NOT NULL DEFAULT 0,
        bonus_amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        deduction_amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        total_payable NUMERIC(15, 3) NOT NULL DEFAULT 0,
        is_paid BOOLEAN NOT NULL DEFAULT false,
        payment_batch_ref TEXT NULL,
        notes TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_labor_proj_date 
      ON contracting_labor_attendance_records (tenant_id, project_id, attendance_date);
    `.execute(db);

    // 4. Client Payment Milestones & In-Kind Barter Settlements (جدول الدفعات والمقايضة العينية)
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_client_payment_milestones (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        project_id BIGINT NOT NULL REFERENCES contracting_projects(id) ON DELETE CASCADE,
        milestone_name TEXT NOT NULL,
        due_date DATE NULL,
        required_progress_percent NUMERIC(5, 2) NOT NULL DEFAULT 0,
        scheduled_amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        received_amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        settlement_type TEXT NOT NULL DEFAULT 'cash',
        in_kind_unit_ref TEXT NULL,
        in_kind_valuation NUMERIC(15, 3) NOT NULL DEFAULT 0,
        status TEXT NOT NULL DEFAULT 'pending',
        settled_at TIMESTAMPTZ NULL,
        notes TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_milestones_proj 
      ON contracting_client_payment_milestones (tenant_id, project_id, status);
    `.execute(db);

    // 5. Equipment & Tools Asset Tracking (سجل وتتبع العِدة والمعدات الميدانية بالمشاريع)
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_equipment_assets (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        asset_code TEXT NOT NULL,
        name TEXT NOT NULL,
        category TEXT NOT NULL DEFAULT 'heavy_machinery',
        serial_number TEXT NULL,
        current_project_id BIGINT NULL REFERENCES contracting_projects(id) ON DELETE SET NULL,
        current_location_desc TEXT NOT NULL DEFAULT 'المخزن الرئيسي',
        assigned_supervisor TEXT NULL,
        operational_status TEXT NOT NULL DEFAULT 'active_working',
        purchase_cost NUMERIC(15, 3) NOT NULL DEFAULT 0,
        purchase_date DATE NULL,
        notes TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_contracting_equipment_code UNIQUE (tenant_id, asset_code)
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_equipment_proj 
      ON contracting_equipment_assets (tenant_id, current_project_id, operational_status);
    `.execute(db);

    // 6. Equipment Transfers Ledger (سجل حركات نقل العِدة بين المشاريع)
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_equipment_transfers (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        equipment_id BIGINT NOT NULL REFERENCES contracting_equipment_assets(id) ON DELETE CASCADE,
        from_project_id BIGINT NULL REFERENCES contracting_projects(id) ON DELETE SET NULL,
        to_project_id BIGINT NULL REFERENCES contracting_projects(id) ON DELETE SET NULL,
        transfer_date DATE NOT NULL DEFAULT CURRENT_DATE,
        dispatched_by TEXT NOT NULL DEFAULT '',
        received_by TEXT NOT NULL DEFAULT '',
        condition_on_dispatch TEXT NOT NULL DEFAULT 'good',
        condition_on_receipt TEXT NOT NULL DEFAULT 'good',
        notes TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `.execute(db);

    // 7. Supplier Price Memory & Rating Directory (دليل الموردين والذاكرة السعرية والتقييم)
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_supplier_price_memory (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        supplier_id BIGINT NOT NULL REFERENCES suppliers(id) ON DELETE CASCADE,
        supplier_name TEXT NOT NULL DEFAULT '',
        material_name TEXT NOT NULL,
        unit TEXT NOT NULL DEFAULT 'item',
        last_unit_price NUMERIC(15, 3) NOT NULL DEFAULT 0,
        last_purchase_date DATE NOT NULL DEFAULT CURRENT_DATE,
        last_project_id BIGINT NULL REFERENCES contracting_projects(id) ON DELETE SET NULL,
        governorate TEXT NOT NULL DEFAULT 'القاهرة',
        payment_terms TEXT NOT NULL DEFAULT 'cash',
        quality_rating NUMERIC(3, 1) NOT NULL DEFAULT 5.0,
        delivery_speed_rating NUMERIC(3, 1) NOT NULL DEFAULT 5.0,
        notes TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_supplier_memory 
      ON contracting_supplier_price_memory (tenant_id, supplier_id, material_name);
    `.execute(db);

    // 8. Add project quotation taxes & insurance columns if they don't exist
    await sql`
      ALTER TABLE contracting_projects 
      ADD COLUMN IF NOT EXISTS vat_included BOOLEAN NOT NULL DEFAULT false,
      ADD COLUMN IF NOT EXISTS vat_percent NUMERIC(5, 2) NOT NULL DEFAULT 14.00,
      ADD COLUMN IF NOT EXISTS social_insurance_percent NUMERIC(5, 2) NOT NULL DEFAULT 2.16,
      ADD COLUMN IF NOT EXISTS contractor_office_tax_percent NUMERIC(5, 2) NOT NULL DEFAULT 1.00;
    `.execute(db);

    // 9. Add boq_item_id tagging to material requisitions
    await sql`
      ALTER TABLE contracting_material_requisitions 
      ADD COLUMN IF NOT EXISTS boq_item_id BIGINT NULL REFERENCES contracting_boq_items(id) ON DELETE SET NULL,
      ADD COLUMN IF NOT EXISTS boq_item_code TEXT NULL;
    `.execute(db);
  },

  async down(db: Kysely<unknown>): Promise<void> {
    await sql`DROP TABLE IF EXISTS contracting_supplier_price_memory CASCADE;`.execute(db);
    await sql`DROP TABLE IF EXISTS contracting_equipment_transfers CASCADE;`.execute(db);
    await sql`DROP TABLE IF EXISTS contracting_equipment_assets CASCADE;`.execute(db);
    await sql`DROP TABLE IF EXISTS contracting_client_payment_milestones CASCADE;`.execute(db);
    await sql`DROP TABLE IF EXISTS contracting_labor_attendance_records CASCADE;`.execute(db);
    await sql`DROP TABLE IF EXISTS contracting_site_mobilization_expenses CASCADE;`.execute(db);
    await sql`DROP TABLE IF EXISTS contracting_boq_takeoffs CASCADE;`.execute(db);
  },
};
