import { sql, type Kysely } from 'kysely';

export const migration = {
  async up(db: Kysely<unknown>): Promise<void> {
    // 1. Create approval_rules table
    await sql`
      CREATE TABLE IF NOT EXISTS approval_rules (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        module TEXT NOT NULL,
        min_amount NUMERIC(15, 4) NOT NULL DEFAULT 0,
        max_amount NUMERIC(15, 4) NULL,
        tier_level INT NOT NULL DEFAULT 1,
        required_role TEXT NOT NULL DEFAULT 'admin',
        approver_user_id INT NULL,
        is_active BOOLEAN NOT NULL DEFAULT TRUE,
        notes TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_approval_rules_tenant_module 
      ON approval_rules (tenant_id, module, tier_level);
    `.execute(db);

    // 2. Create approval_requests table
    await sql`
      CREATE TABLE IF NOT EXISTS approval_requests (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        module TEXT NOT NULL,
        record_id BIGINT NOT NULL,
        record_ref TEXT NOT NULL DEFAULT '',
        amount NUMERIC(15, 4) NOT NULL DEFAULT 0,
        currency TEXT NOT NULL DEFAULT 'EGP',
        current_tier INT NOT NULL DEFAULT 1,
        max_tier INT NOT NULL DEFAULT 1,
        status TEXT NOT NULL DEFAULT 'pending',
        requested_by INT NOT NULL,
        requested_by_name TEXT NULL,
        notes TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_approval_requests_tenant_status 
      ON approval_requests (tenant_id, status);
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_approval_requests_record 
      ON approval_requests (tenant_id, module, record_id);
    `.execute(db);

    // 3. Create approval_request_logs table
    await sql`
      CREATE TABLE IF NOT EXISTS approval_request_logs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        request_id BIGINT NOT NULL REFERENCES approval_requests(id) ON DELETE CASCADE,
        tier_level INT NOT NULL DEFAULT 1,
        action TEXT NOT NULL,
        action_by INT NOT NULL,
        action_by_name TEXT NULL,
        action_role TEXT NULL,
        notes TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_approval_logs_request 
      ON approval_request_logs (tenant_id, request_id);
    `.execute(db);
  },

  async down(db: Kysely<unknown>): Promise<void> {
    await sql`DROP TABLE IF EXISTS approval_request_logs CASCADE;`.execute(db);
    await sql`DROP TABLE IF EXISTS approval_requests CASCADE;`.execute(db);
    await sql`DROP TABLE IF EXISTS approval_rules CASCADE;`.execute(db);
  },
};
