import { Kysely, sql } from 'kysely';

export const migration = {
  up: async (db: Kysely<any>): Promise<void> => {
    await sql`
      CREATE TABLE IF NOT EXISTS customer_installment_plans (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        account_id TEXT NOT NULL DEFAULT '',
        plan_number TEXT NOT NULL,
        sale_id BIGINT NULL REFERENCES sales(id) ON DELETE SET NULL,
        customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
        total_amount NUMERIC(15, 4) NOT NULL DEFAULT 0,
        down_payment NUMERIC(15, 4) NOT NULL DEFAULT 0,
        financed_amount NUMERIC(15, 4) NOT NULL DEFAULT 0,
        interest_rate_percent NUMERIC(8, 4) NOT NULL DEFAULT 0,
        interest_amount NUMERIC(15, 4) NOT NULL DEFAULT 0,
        total_with_interest NUMERIC(15, 4) NOT NULL DEFAULT 0,
        installment_count INTEGER NOT NULL DEFAULT 1,
        monthly_amount NUMERIC(15, 4) NOT NULL DEFAULT 0,
        start_date DATE NOT NULL DEFAULT CURRENT_DATE,
        status TEXT NOT NULL DEFAULT 'active',
        notes TEXT NOT NULL DEFAULT '',
        branch_id BIGINT NULL,
        created_by BIGINT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_customer_installment_plans_tenant_cust 
      ON customer_installment_plans (tenant_id, customer_id);
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_customer_installment_plans_tenant_status 
      ON customer_installment_plans (tenant_id, status);
    `.execute(db);

    await sql`
      CREATE TABLE IF NOT EXISTS customer_installments (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        account_id TEXT NOT NULL DEFAULT '',
        plan_id BIGINT NOT NULL REFERENCES customer_installment_plans(id) ON DELETE CASCADE,
        sale_id BIGINT NULL REFERENCES sales(id) ON DELETE SET NULL,
        customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
        installment_number INTEGER NOT NULL,
        due_date DATE NOT NULL,
        amount NUMERIC(15, 4) NOT NULL DEFAULT 0,
        paid_amount NUMERIC(15, 4) NOT NULL DEFAULT 0,
        status TEXT NOT NULL DEFAULT 'pending',
        paid_at TIMESTAMPTZ NULL,
        payment_method TEXT NOT NULL DEFAULT 'cash',
        receipt_no TEXT NULL,
        notes TEXT NOT NULL DEFAULT '',
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_customer_installments_tenant_plan 
      ON customer_installments (tenant_id, plan_id);
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_customer_installments_tenant_due 
      ON customer_installments (tenant_id, due_date);
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_customer_installments_tenant_status 
      ON customer_installments (tenant_id, status);
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_customer_installments_tenant_cust 
      ON customer_installments (tenant_id, customer_id);
    `.execute(db);
  },

  down: async (db: Kysely<any>): Promise<void> => {
    await sql`DROP TABLE IF EXISTS customer_installments`.execute(db);
    await sql`DROP TABLE IF EXISTS customer_installment_plans`.execute(db);
  },
};
