import { sql, type Kysely } from 'kysely';

export const migration = {
  async up(db: Kysely<unknown>): Promise<void> {
    // 1. Create forex_revaluation_runs table
    await sql`
      CREATE TABLE IF NOT EXISTS forex_revaluation_runs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        period_date DATE NOT NULL,
        currency_code TEXT NOT NULL,
        book_exchange_rate NUMERIC(15, 6) NOT NULL DEFAULT 1.0,
        closing_exchange_rate NUMERIC(15, 6) NOT NULL DEFAULT 1.0,
        foreign_balance_total NUMERIC(15, 4) NOT NULL DEFAULT 0,
        unrealized_gain_loss NUMERIC(15, 4) NOT NULL DEFAULT 0,
        journal_entry_id BIGINT NULL,
        journal_entry_no TEXT NULL,
        status TEXT NOT NULL DEFAULT 'posted',
        notes TEXT NULL,
        created_by INT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_forex_runs_tenant 
      ON forex_revaluation_runs (tenant_id, period_date);
    `.execute(db);

    // 2. Create forex_revaluation_lines table
    await sql`
      CREATE TABLE IF NOT EXISTS forex_revaluation_lines (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        run_id BIGINT NOT NULL REFERENCES forex_revaluation_runs(id) ON DELETE CASCADE,
        account_id BIGINT NOT NULL,
        account_code TEXT NOT NULL,
        account_name TEXT NOT NULL,
        foreign_balance NUMERIC(15, 4) NOT NULL DEFAULT 0,
        book_local_value NUMERIC(15, 4) NOT NULL DEFAULT 0,
        revalued_local_value NUMERIC(15, 4) NOT NULL DEFAULT 0,
        unrealized_difference NUMERIC(15, 4) NOT NULL DEFAULT 0,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_forex_lines_run 
      ON forex_revaluation_lines (tenant_id, run_id);
    `.execute(db);
  },

  async down(db: Kysely<unknown>): Promise<void> {
    await sql`DROP TABLE IF EXISTS forex_revaluation_lines CASCADE;`.execute(db);
    await sql`DROP TABLE IF EXISTS forex_revaluation_runs CASCADE;`.execute(db);
  },
};
