import { sql, type Kysely } from 'kysely';

export const migration = {
  async up(db: Kysely<unknown>): Promise<void> {
    // =========================================================================
    // 1. Create Bank Guarantees Table (contracting_guarantees)
    // =========================================================================
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_guarantees (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        project_id BIGINT NOT NULL,
        subcontract_id BIGINT NULL,
        subcontractor_id BIGINT NULL,
        guarantee_number TEXT NOT NULL,
        guarantee_type TEXT NOT NULL DEFAULT 'advance_payment',
        issuing_bank TEXT NOT NULL,
        amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        currency TEXT NOT NULL DEFAULT 'EGP',
        issue_date DATE NOT NULL,
        expiry_date DATE NOT NULL,
        claim_expiry_date DATE NULL,
        reduction_schedule JSONB NULL,
        status TEXT NOT NULL DEFAULT 'active',
        document_url TEXT NULL,
        notes TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_contracting_guarantees_tenant_code UNIQUE (tenant_id, guarantee_number),
        CONSTRAINT uq_contracting_guarantees_tenant_id UNIQUE (tenant_id, id)
      );
    `.execute(db);

    // =========================================================================
    // 2. Add Composite Multi-Tenant FKs with ON DELETE RESTRICT
    // =========================================================================
    await sql`
      DO $$
      BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_guarantees_project_tenant') THEN
          ALTER TABLE contracting_guarantees
            ADD CONSTRAINT fk_guarantees_project_tenant
            FOREIGN KEY (project_id)
            REFERENCES contracting_projects(id)
            ON DELETE RESTRICT;
        END IF;

        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_guarantees_subcontract_tenant') THEN
          ALTER TABLE contracting_guarantees
            ADD CONSTRAINT fk_guarantees_subcontract_tenant
            FOREIGN KEY (tenant_id, subcontract_id)
            REFERENCES contracting_subcontracts(tenant_id, id)
            ON DELETE RESTRICT;
        END IF;

        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_guarantees_subcontractor_tenant') THEN
          ALTER TABLE contracting_guarantees
            ADD CONSTRAINT fk_guarantees_subcontractor_tenant
            FOREIGN KEY (tenant_id, subcontractor_id)
            REFERENCES contracting_subcontractors(tenant_id, id)
            ON DELETE RESTRICT;
        END IF;
      END $$;
    `.execute(db);

    // =========================================================================
    // 3. Add CHECK Constraints for Integrity & Enumerations
    // =========================================================================
    await sql`
      DO $$
      BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_guarantee_type') THEN
          ALTER TABLE contracting_guarantees
            ADD CONSTRAINT chk_guarantee_type
            CHECK (guarantee_type IN ('advance_payment', 'performance', 'retention', 'maintenance', 'bid_bond'));
        END IF;

        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_guarantee_status') THEN
          ALTER TABLE contracting_guarantees
            ADD CONSTRAINT chk_guarantee_status
            CHECK (status IN ('active', 'expired', 'released', 'confiscated_invoked', 'cancelled'));
        END IF;

        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_guarantee_amount') THEN
          ALTER TABLE contracting_guarantees
            ADD CONSTRAINT chk_guarantee_amount
            CHECK (amount >= 0);
        END IF;

        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_guarantee_dates') THEN
          ALTER TABLE contracting_guarantees
            ADD CONSTRAINT chk_guarantee_dates
            CHECK (expiry_date >= issue_date AND (claim_expiry_date IS NULL OR claim_expiry_date >= expiry_date));
        END IF;
      END $$;
    `.execute(db);

    // =========================================================================
    // 4. Performance & Expiry Alert Indexes
    // =========================================================================
    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_guarantees_tenant_proj
        ON contracting_guarantees (tenant_id, project_id);

      CREATE INDEX IF NOT EXISTS idx_contracting_guarantees_subcontract
        ON contracting_guarantees (tenant_id, subcontract_id);

      CREATE INDEX IF NOT EXISTS idx_contracting_guarantees_expiry
        ON contracting_guarantees (tenant_id, status, expiry_date);
    `.execute(db);
  },

  async down(db: Kysely<unknown>): Promise<void> {
    await sql`DROP TABLE IF EXISTS contracting_guarantees CASCADE;`.execute(db);
  },
};
