import { Kysely, sql } from 'kysely';

export const migration = {
  up: async (db: Kysely<any>): Promise<void> => {
    await sql`
      CREATE TABLE IF NOT EXISTS currency_exchange_rates (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        account_id TEXT NOT NULL DEFAULT '',
        currency_code TEXT NOT NULL,
        currency_name TEXT NOT NULL,
        exchange_rate NUMERIC(15, 6) NOT NULL DEFAULT 1,
        is_base BOOLEAN NOT NULL DEFAULT FALSE,
        symbol TEXT NOT NULL DEFAULT '',
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_tenant_currency UNIQUE (tenant_id, currency_code)
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_curr_rate_tenant 
      ON currency_exchange_rates (tenant_id);
    `.execute(db);
  },

  down: async (db: Kysely<any>): Promise<void> => {
    await sql`DROP TABLE IF EXISTS currency_exchange_rates`.execute(db);
  },
};
