import { sql, type Kysely } from 'kysely';

// Closes the "Customs & Compliance" gap found in the freight-forwarding
// benchmark (CargoWise): "customs" previously existed only as free descriptive
// text in the carrier directory ("services_offered: Customs Clearance"), with
// zero HS code, duty, or declaration tracking anywhere in the schema.
// This is deliberately scoped to internal record-keeping (HS codes, declared
// value, duty amounts, declaration status) — NOT live filing with a customs
// authority API/EDI, which needs a paid broker/government integration and
// credentials this session does not have (see ARCHITECTURE_INVARIANTS.md O18).
export const migration = {
  async up(db: Kysely<unknown>): Promise<void> {
    await sql`
      CREATE TABLE IF NOT EXISTS maritime_customs_declarations (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        job_id BIGINT NOT NULL REFERENCES maritime_jobs(id) ON DELETE CASCADE,
        declaration_number TEXT NULL,
        declaration_type TEXT NOT NULL DEFAULT 'import',
        customs_authority TEXT NULL,
        broker_name TEXT NULL,
        submitted_date DATE NULL,
        cleared_date DATE NULL,
        status TEXT NOT NULL DEFAULT 'pending',
        total_customs_value NUMERIC(15, 3) NOT NULL DEFAULT 0,
        total_duty_amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        currency TEXT NOT NULL DEFAULT 'USD',
        notes TEXT NULL,
        created_by BIGINT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT chk_maritime_customs_decl_type CHECK (declaration_type IN ('import', 'export')),
        CONSTRAINT chk_maritime_customs_decl_status CHECK (status IN ('pending', 'submitted', 'cleared', 'held', 'rejected'))
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_maritime_customs_declarations_job
      ON maritime_customs_declarations (tenant_id, job_id);
    `.execute(db);

    await sql`
      CREATE TABLE IF NOT EXISTS maritime_customs_declaration_items (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        declaration_id BIGINT NOT NULL REFERENCES maritime_customs_declarations(id) ON DELETE CASCADE,
        hs_code TEXT NOT NULL,
        commodity_description TEXT NOT NULL DEFAULT '',
        quantity NUMERIC(15, 3) NOT NULL DEFAULT 0,
        unit TEXT NOT NULL DEFAULT 'PCS',
        customs_value NUMERIC(15, 3) NOT NULL DEFAULT 0,
        duty_rate_percent NUMERIC(6, 3) NOT NULL DEFAULT 0,
        duty_amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        notes TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT chk_maritime_customs_items_rate CHECK (duty_rate_percent >= 0 AND duty_rate_percent <= 100)
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_maritime_customs_declaration_items_decl
      ON maritime_customs_declaration_items (tenant_id, declaration_id);
    `.execute(db);
  },

  async down(db: Kysely<unknown>): Promise<void> {
    await sql`DROP TABLE IF EXISTS maritime_customs_declaration_items;`.execute(db);
    await sql`DROP TABLE IF EXISTS maritime_customs_declarations;`.execute(db);
  },
};
