import { sql, type Kysely } from 'kysely';

export const migration = {
  async up(db: Kysely<unknown>): Promise<void> {
    const mepMasterItems = [
      {
        code: 'FF-PIP-STM-65',
        name: 'مواسير سيملس حديد أسود جدول 40 قطر 65 مم (2.5 بوصة) ASTM A53',
        trade: 'fire_fighting',
        tradeAr: 'شبكات مكافحة وإطفاء الحريق',
        unit: 'm',
        cost: 380,
        price: 490,
        desc: 'توريد وتركيب واختبار مواسير صلب سيملس جدول 40 قطر 65 مم غير ملحومة ASTM A53 Gr. B شاملة المساليب والكيعان والفلكسبل والهناجر وفتحات الاختبار والغسيل',
      },
      {
        code: 'FF-PIP-STM-40',
        name: 'مواسير سيملس حديد أسود جدول 40 قطر 40 مم (1.5 بوصة) ASTM A53',
        trade: 'fire_fighting',
        tradeAr: 'شبكات مكافحة وإطفاء الحريق',
        unit: 'm',
        cost: 195,
        price: 250,
        desc: 'توريد وتركيب واختبار مواسير صلب سيملس جدول 40 قطر 40 مم ASTM A53 Gr. B شاملة الملحقات والهناجر وطبقات الحماية والاختبار الهيدروستاتيكي',
      },
      {
        code: 'FF-PIP-STM-50',
        name: 'مواسير سيملس حديد أسود جدول 40 قطر 50 مم (2 بوصة) ASTM A53',
        trade: 'fire_fighting',
        tradeAr: 'شبكات مكافحة وإطفاء الحريق',
        unit: 'm',
        cost: 290,
        price: 380,
        desc: 'توريد وتركيب واختبار مواسير صلب سيملس جدول 40 قطر 50 مم شاملة لوازم الربط الجروف والمشتركات',
      },
      {
        code: 'FF-PIP-STM-80',
        name: 'مواسير سيملس حديد أسود جدول 40 قطر 80 مم (3 بوصة) ASTM A53',
        trade: 'fire_fighting',
        tradeAr: 'شبكات مكافحة وإطفاء الحريق',
        unit: 'm',
        cost: 540,
        price: 690,
        desc: 'توريد وتركيب واختبار مواسير صلب سيملس جدول 40 قطر 80 مم لشبكات التغذية الرأسية والصواعد',
      },
      {
        code: 'FF-PIP-STM-100',
        name: 'مواسير سيملس حديد أسود جدول 40 قطر 100 مم (4 بوصة) ASTM A53',
        trade: 'fire_fighting',
        tradeAr: 'شبكات مكافحة وإطفاء الحريق',
        unit: 'm',
        cost: 720,
        price: 920,
        desc: 'توريد وتركيب واختبار مواسير صلب سيملس جدول 40 قطر 100 مم لشبكات التغذية الرئيسية',
      },
      {
        code: 'FF-PIP-HDP-90',
        name: 'مواسير بولي إيثيلين عالي الكثافة شبكات حريق HDPE SDR11 PN16 قطر 90 مم',
        trade: 'fire_fighting',
        tradeAr: 'شبكات مكافحة وإطفاء الحريق',
        unit: 'm',
        cost: 240,
        price: 330,
        desc: 'توريد وتركيب واختبار مواسير شبكة حريق مدفونة بولي إيثيلين HDPE SDR11 ضغط 16 بار قطر 90 مم',
      },
      {
        code: 'FF-PIP-HDP-65',
        name: 'مواسير بولي إيثيلين عالي الكثافة شبكات حريق HDPE SDR11 PN16 قطر 65 مم',
        trade: 'fire_fighting',
        tradeAr: 'شبكات مكافحة وإطفاء الحريق',
        unit: 'm',
        cost: 180,
        price: 250,
        desc: 'توريد وتركيب واختبار مواسير حريق بولي إيثيلين HDPE SDR11 ضغط 16 بار قطر 65 مم',
      },
      {
        code: 'FF-PIP-HDP-110',
        name: 'مواسير بولي إيثيلين عالي الكثافة شبكات حريق HDPE SDR11 PN16 قطر 110 مم',
        trade: 'fire_fighting',
        tradeAr: 'شبكات مكافحة وإطفاء الحريق',
        unit: 'm',
        cost: 320,
        price: 440,
        desc: 'توريد وتركيب واختبار مواسير حريق مدفونة HDPE SDR11 ضغط 16 بار قطر 110 مم',
      },
      {
        code: 'FF-VLV-NRS-80',
        name: 'محبس سكينة غير صاعد 80 مم NRS Gate Valve وصلة Tie-In',
        trade: 'fire_fighting',
        tradeAr: 'شبكات مكافحة وإطفاء الحريق',
        unit: 'item',
        cost: 3200,
        price: 4500,
        desc: 'توريد وتركيب واختبار محبس بوابة غير صاعد NRS Gate Valve مقاس 80 مم معتمد UL/FM لنقطة الربط Tie-In',
      },
      {
        code: 'FF-VLV-OSY-100',
        name: 'محبس سكينة صاعد 100 مم OS&Y Gate Valve مع مفتاح إشرافي Tamper Switch',
        trade: 'fire_fighting',
        tradeAr: 'شبكات مكافحة وإطفاء الحريق',
        unit: 'item',
        cost: 5800,
        price: 7900,
        desc: 'توريد وتركيب محبس سكينة صاعد OS&Y مقاس 100 مم مع مفتاح مراقبة كهربي Tamper Switch',
      },
      {
        code: 'FF-VLV-AAV-25',
        name: 'محبس تنفيس وتصريف هواء أوتوماتيكي 25 مم (1 بوصة) Automatic Air Vent',
        trade: 'fire_fighting',
        tradeAr: 'شبكات مكافحة وإطفاء الحريق',
        unit: 'item',
        cost: 850,
        price: 1250,
        desc: 'توريد وتركيب محبس تصريف وتنفيس هواء أوتوماتيكي سريع AAV مقاس 25 مم مع محبس عزل',
      },
      {
        code: 'FF-FHC-COMB-02',
        name: 'صندوق حريق تركيبي مزدوج FHC-2 (بكرة 1 بوصة 30م + محبس 1.5 + محبس زاوية + كابينة)',
        trade: 'fire_fighting',
        tradeAr: 'شبكات مكافحة وإطفاء الحريق',
        unit: 'item',
        cost: 8800,
        price: 12500,
        desc: 'توريد وتركيب صندوق حريق تركيبي FHC-2 يشمل بكرة خرطوم 1 بوصة 30 متر ومحبس كروي ومحبس زاوية وقاذف وكابينة صاج',
      },
      {
        code: 'FF-FHC-SGL-01',
        name: 'صندوق حريق مفرد FHC-1 هوز ريل بكرة 1 بوصة بطول 30 متر غاطس/ظاهر',
        trade: 'fire_fighting',
        tradeAr: 'شبكات مكافحة وإطفاء الحريق',
        unit: 'item',
        cost: 5400,
        price: 7600,
        desc: 'توريد وتركيب صندوق حريق مفرد هوز ريل 1 بوصة 30 متر مع القاذف النحاسي والكابينة',
      },
      {
        code: 'FF-EXT-DRY-06',
        name: 'طفاية حريق يدوية بودرة كيميائية جافة ABC سعة 6 كجم مع الكابينة والحامل',
        trade: 'fire_fighting',
        tradeAr: 'شبكات مكافحة وإطفاء الحريق',
        unit: 'item',
        cost: 650,
        price: 950,
        desc: 'توريد وتثبيت طفاية حريق يدوية بودرة جافة ABC سعة 6 كجم معتمدة بالمانومتر وحامل التثبيت',
      },
      {
        code: 'FF-EXT-CO2-06',
        name: 'طفاية حريق غاز ثاني أكسيد الكربون CO2 سعة 6 كجم لغرف ولوحات الكهرباء',
        trade: 'fire_fighting',
        tradeAr: 'شبكات مكافحة وإطفاء الحريق',
        unit: 'item',
        cost: 1400,
        price: 1950,
        desc: 'توريد وتثبيت طفاية غاز ثاني أكسيد الكربون CO2 سعة 6 كجم سيملس شاملة الخرطوم والعدسة',
      },
      {
        code: 'FF-SYS-FSRCH-01',
        name: 'نظام إطفاء لوحات الكهرباء التلقائي الذاتي Fire Search بأنبوب الاستشعار وشحنة CO2',
        trade: 'fire_fighting',
        tradeAr: 'شبكات مكافحة وإطفاء الحريق',
        unit: 'ls',
        cost: 6500,
        price: 9200,
        desc: 'توريد وتركيب نظام إطفاء ذاتي Fire Search للوحات الكهربائية شامل أسطوانة CO2 وخرطوم استشعار حراري ورأس الإطفاء',
      },
      {
        code: 'FF-SPK-PND-15',
        name: 'رشاش مياه حريق غاطس Pendent Sprinkler 1/2 بوصة K-5.6 حرارة 68°C',
        trade: 'fire_fighting',
        tradeAr: 'شبكات مكافحة وإطفاء الحريق',
        unit: 'item',
        cost: 140,
        price: 220,
        desc: 'توريد وتركيب رشاش مياه حريق غاطس Pendent نصف بوصة K-5.6 مع الوردة Escutcheon',
      },
      {
        code: 'FF-PMP-SET-500',
        name: 'مجموعة مضخات مكافحة حريق معتمدة 500 GPM (كهرباء + ديزل + جوكي + لوحات)',
        trade: 'fire_fighting',
        tradeAr: 'شبكات مكافحة وإطفاء الحريق',
        unit: 'set',
        cost: 480000,
        price: 620000,
        desc: 'توريد وتركيب طقم طلمبات حريق متكامل 500 GPM يشمل كهرباء + ديزل + جوكي + لوحات NFPA 20 ومجمع السحب والطرد',
      },
      {
        code: 'ELE-CBL-4X16',
        name: 'كابلات نحاس معزولة 4×16 مم2 مسلحة Cu/XLPE/PVC/STA جهد 0.6/1 ك.ف',
        trade: 'electrical_power',
        tradeAr: 'الأعمال الكهربائية والتيار الخفيف',
        unit: 'm',
        cost: 280,
        price: 370,
        desc: 'توريد ومد وتوصيل كابل نحاس مسلح قطاع 4×16 مم2 داخل خنادق كابلات أو حوامل كابلات',
      },
      {
        code: 'ELE-CBL-4X35',
        name: 'كابلات نحاس معزولة 4×35 مم2 مسلحة Cu/XLPE/PVC/STA جهد 0.6/1 ك.ف',
        trade: 'electrical_power',
        tradeAr: 'الأعمال الكهربائية والتيار الخفيف',
        unit: 'm',
        cost: 580,
        price: 750,
        desc: 'توريد ومد وتوصيل كابل نحاس مسلح قطاع 4×35 مم2 لتغذية لوحات التوزيع الفرعية',
      },
      {
        code: 'ELE-PNL-MDB',
        name: 'لوحة توزيع كهرباء رئيسية MDB سعة 400 أمبير شاملة القواطع والحماية',
        trade: 'electrical_power',
        tradeAr: 'الأعمال الكهربائية والتيار الخفيف',
        unit: 'item',
        cost: 45000,
        price: 62000,
        desc: 'توريد وتركيب لوحة توزيع رئيسية MDB صاج 2 مم IP54 قاطع رئيسي 400A MCCB وقواطع فرعية',
      },
      {
        code: 'ELE-LGT-LED-60',
        name: 'كشاف إضاءة ليد 60×60 سم غاطس 45 وات بروفايل معتمد',
        trade: 'electrical_power',
        tradeAr: 'الأعمال الكهربائية والتيار الخفيف',
        unit: 'item',
        cost: 320,
        price: 460,
        desc: 'توريد وتركيب كشاف إنارة ليد 60×60 سم 45 وات كفاءة عالية 120 لومن/وات',
      },
      {
        code: 'ELE-EARTH-PIT',
        name: 'بئر وغرفة تأريض نحاسي قياسي بمقاومة أقل من 2 أوم مع قضيب التأريض',
        trade: 'electrical_power',
        tradeAr: 'الأعمال الكهربائية والتيار الخفيف',
        unit: 'set',
        cost: 6500,
        price: 9000,
        desc: 'تنفيذ بئر تأريض بقضيب نحاس نقي 5/8 بوصة بطول 3 متر وغرفة تفتيش خرسانية',
      },
      {
        code: 'PLM-PIP-PPR-32',
        name: 'مواسير تغذية مياه بولي بروبلين PPR قطر 32 مم (1 بوصة) PN20',
        trade: 'plumbing_sanitary',
        tradeAr: 'الأعمال الصحية والصرف',
        unit: 'm',
        cost: 75,
        price: 110,
        desc: 'توريد وتركيب واختبار مواسير تغذية مياه شرب PPR ضغط 20 بار قطر 32 مم شاملة الوصلات',
      },
      {
        code: 'PLM-PIP-UPVC-110',
        name: 'مواسير صرف أبيض UPVC قطر 110 مم (4 بوصة) ثقيل سمك 3.2 مم',
        trade: 'plumbing_sanitary',
        tradeAr: 'الأعمال الصحية والصرف',
        unit: 'm',
        cost: 110,
        price: 160,
        desc: 'توريد وتركيب مواسير صرف صحي UPVC قطر 110 مم للصواعد والمخارج والمطابخ',
      },
      {
        code: 'PLM-MNH-BRK-60',
        name: 'غرفة تفتيش مباني 60×60 سم مع مجاري انسياب وغطاء زهر دكتايل B125',
        trade: 'plumbing_sanitary',
        tradeAr: 'الأعمال الصحية والصرف',
        unit: 'item',
        cost: 1800,
        price: 2600,
        desc: 'بناء غرفة تفتيش 60×60 سم طوب مصمت مع المحارة وقاعدة خرسانية وغطاء زهر دكتايل',
      },
      {
        code: 'HVC-VRF-OUT-16',
        name: 'وحدة تكييف مركزية خارجية بنظام تدفق وسيط التبريد المتغير VRF سعة 16 حصان',
        trade: 'hvac',
        tradeAr: 'التكييف والتهوية الميكانيكية',
        unit: 'item',
        cost: 165000,
        price: 215000,
        desc: 'توريد وتركيب وتشغيل وحدة تكييف خارجية VRF إنفرتر سعة 16 حصان',
      },
      {
        code: 'HVC-FCU-CONC-03',
        name: 'وحدة تكييف فان كويل كونسيلد مخفي FCU سعة 3 طن تبريد',
        trade: 'hvac',
        tradeAr: 'التكييف والتهوية الميكانيكية',
        unit: 'item',
        cost: 18500,
        price: 24500,
        desc: 'توريد وتركيب ماكينة تكييف مخفية كونسيلد سعة 3 طن مع المحابس الكروية وفلتر الهواء',
      },
      {
        code: 'HVC-DCT-GI-100',
        name: 'مجاري هواء صاج مجلفن Ductwork مع العزل الحراري والداخلي',
        trade: 'hvac',
        tradeAr: 'التكييف والتهوية الميكانيكية',
        unit: 'm2',
        cost: 360,
        price: 490,
        desc: 'تصنيع وتركيب مجاري هواء صاج مجلفن سمك 0.8 مم شاملة العزل الخارجي صوف زجاجي',
      },
    ];

    for (const it of mepMasterItems) {
      await sql`
        INSERT INTO contracting_master_boq_library (
          tenant_id, trade_category, trade_name_ar, item_code, name, description, unit, standard_cost, standard_price, is_active
        ) VALUES (
          '', ${it.trade}, ${it.tradeAr}, ${it.code}, ${it.name}, ${it.desc}, ${it.unit}, ${it.cost}, ${it.price}, true
        )
        ON CONFLICT (tenant_id, item_code) DO UPDATE SET
          name = EXCLUDED.name,
          description = EXCLUDED.description,
          trade_category = EXCLUDED.trade_category,
          trade_name_ar = EXCLUDED.trade_name_ar,
          unit = EXCLUDED.unit,
          standard_cost = EXCLUDED.standard_cost,
          standard_price = EXCLUDED.standard_price,
          updated_at = NOW();
      `.execute(db);
    }

    const mepEngineeringConstants = [
      {
        item_code: 'FF-PIP-STM-65',
        item_name: 'مواسير سيملس حديد أسود جدول 40 قطر 65 مم (2.5 بوصة) ASTM A53',
        unit: 'm',
        waste_percent: 5.0,
        overhead_percent: 7.0,
        profit_markup_percent: 15.0,
        components: [
          { componentCode: 'MAT-FF-PIP-65', componentName: 'مواسير سيملس جدول 40 قطر 65 مم معتمدة', unit: 'm', qtyPerUnit: 1.05, unitRate: 310, componentType: 'material' },
          { componentCode: 'MAT-FF-FIT-65', componentName: 'لوازم وهناجر ومسامير وفلكسبل 65 مم', unit: 'ls', qtyPerUnit: 1.0, unitRate: 45, componentType: 'material' },
          { componentCode: 'LAB-FF-PIP-FIT', componentName: 'مصنعية فني ولحام وتركيب مواسير حريق', unit: 'm', qtyPerUnit: 1.0, unitRate: 65, componentType: 'labor' },
        ],
        notes: 'مواسير سيملس غير ملحومة ASTM A53 Gr. B لشبكات مكافحة الحريق مع الاختبار الهيدروستاتيكي.',
      },
      {
        item_code: 'FF-PIP-STM-40',
        item_name: 'مواسير سيملس حديد أسود جدول 40 قطر 40 مم (1.5 بوصة) ASTM A53',
        unit: 'm',
        waste_percent: 5.0,
        overhead_percent: 7.0,
        profit_markup_percent: 15.0,
        components: [
          { componentCode: 'MAT-FF-PIP-40', componentName: 'مواسير سيملس جدول 40 قطر 40 مم معتمدة', unit: 'm', qtyPerUnit: 1.05, unitRate: 155, componentType: 'material' },
          { componentCode: 'MAT-FF-FIT-40', componentName: 'لوازم وهناجر ومسامير 40 مم', unit: 'ls', qtyPerUnit: 1.0, unitRate: 25, componentType: 'material' },
          { componentCode: 'LAB-FF-PIP-FIT', componentName: 'مصنعية فني وتركيب مواسير حريق', unit: 'm', qtyPerUnit: 1.0, unitRate: 45, componentType: 'labor' },
        ],
        notes: 'مواسير سيملس 1.5 بوصة لتغذية الرشاشات وصناديق الحريق.',
      },
      {
        item_code: 'FF-PIP-HDP-90',
        item_name: 'مواسير بولي إيثيلين شبكة حريق HDPE SDR11 PN16 قطر 90 مم',
        unit: 'm',
        waste_percent: 4.0,
        overhead_percent: 7.0,
        profit_markup_percent: 15.0,
        components: [
          { componentCode: 'MAT-HDP-PIP-90', componentName: 'مواسير HDPE SDR11 ضغط 16 بار قطر 90 مم', unit: 'm', qtyPerUnit: 1.03, unitRate: 175, componentType: 'material' },
          { componentCode: 'MAT-HDP-FIT-90', componentName: 'وصلات ولحام كهروحراري Electrofusion', unit: 'ls', qtyPerUnit: 1.0, unitRate: 35, componentType: 'material' },
          { componentCode: 'LAB-HDP-LAY', componentName: 'مصنعية حفر وفرشة رملية وتركيب واختبار', unit: 'm', qtyPerUnit: 1.0, unitRate: 55, componentType: 'labor' },
        ],
        notes: 'مواسير شبكة حريق خارجية مدفونة HDPE ضغط 16 بار.',
      },
      {
        item_code: 'FF-PIP-HDP-65',
        item_name: 'مواسير بولي إيثيلين شبكة حريق HDPE SDR11 PN16 قطر 65 مم',
        unit: 'm',
        waste_percent: 4.0,
        overhead_percent: 7.0,
        profit_markup_percent: 15.0,
        components: [
          { componentCode: 'MAT-HDP-PIP-65', componentName: 'مواسير HDPE SDR11 ضغط 16 بار قطر 65 مم', unit: 'm', qtyPerUnit: 1.03, unitRate: 130, componentType: 'material' },
          { componentCode: 'MAT-HDP-FIT-65', componentName: 'وصلات ولحام كهروحراري', unit: 'ls', qtyPerUnit: 1.0, unitRate: 25, componentType: 'material' },
          { componentCode: 'LAB-HDP-LAY', componentName: 'مصنعية حفر وفرشة وتركيب واختبار', unit: 'm', qtyPerUnit: 1.0, unitRate: 45, componentType: 'labor' },
        ],
        notes: 'مواسير شبكة حريق مدفونة HDPE قطر 65 مم.',
      },
      {
        item_code: 'FF-VLV-NRS-80',
        item_name: 'محبس سكينة غير صاعد 80 مم NRS Gate Valve وصلة Tie-In',
        unit: 'item',
        waste_percent: 2.0,
        overhead_percent: 7.0,
        profit_markup_percent: 15.0,
        components: [
          { componentCode: 'MAT-VLV-NRS-80', componentName: 'محبس سكينة NRS مقاس 80 مم معتمد UL/FM', unit: 'item', qtyPerUnit: 1.0, unitRate: 2800, componentType: 'material' },
          { componentCode: 'MAT-FLG-SET-80', componentName: 'طقم فلانشات وجوانات ومسامير صلب 80 مم', unit: 'set', qtyPerUnit: 1.0, unitRate: 400, componentType: 'material' },
          { componentCode: 'LAB-VLV-INST', componentName: 'مصنعية تركيب واختبار المحبس', unit: 'item', qtyPerUnit: 1.0, unitRate: 350, componentType: 'labor' },
        ],
        notes: 'محبس سكينة غير صاعد لنقطة ربط شبكة الحريق الخارجية.',
      },
      {
        item_code: 'FF-VLV-AAV-25',
        item_name: 'محبس تنفيس وتصريف هواء أوتوماتيكي 25 مم (1 بوصة) Automatic Air Vent',
        unit: 'item',
        waste_percent: 2.0,
        overhead_percent: 7.0,
        profit_markup_percent: 15.0,
        components: [
          { componentCode: 'MAT-VLV-AAV-25', componentName: 'هواية أوتوماتيكية سريعة AAV 1 بوصة برونز', unit: 'item', qtyPerUnit: 1.0, unitRate: 650, componentType: 'material' },
          { componentCode: 'MAT-VLV-BAL-25', componentName: 'محبس عزل كروي نحاس 1 بوصة', unit: 'item', qtyPerUnit: 1.0, unitRate: 150, componentType: 'material' },
          { componentCode: 'LAB-VLV-SML', componentName: 'مصنعية تركيب واختبار الهواية', unit: 'item', qtyPerUnit: 1.0, unitRate: 120, componentType: 'labor' },
        ],
        notes: 'محبس تصريف هواء أوتوماتيكي عند أعلى نقاط الشبكة.',
      },
      {
        item_code: 'FF-FHC-COMB-02',
        item_name: 'صندوق حريق تركيبي مزدوج FHC-2 (بكرة 1 بوصة 30م + محبس 1.5 + محبس زاوية + كابينة)',
        unit: 'item',
        waste_percent: 2.0,
        overhead_percent: 7.0,
        profit_markup_percent: 15.0,
        components: [
          { componentCode: 'MAT-FHC-CAB-02', componentName: 'كابينة حريق صاج 1.5 مم مدهونة إلكتروستاتيك', unit: 'item', qtyPerUnit: 1.0, unitRate: 3800, componentType: 'material' },
          { componentCode: 'MAT-FHC-REEL-30', componentName: 'بكرة خرطوم مطاطي 1 بوصة 30م بالقاذف', unit: 'item', qtyPerUnit: 1.0, unitRate: 2800, componentType: 'material' },
          { componentCode: 'MAT-FHC-VLV-SET', componentName: 'محبس كروي 1.5 + محبس زاوية Angle Valve 1.5', unit: 'set', qtyPerUnit: 1.0, unitRate: 1600, componentType: 'material' },
          { componentCode: 'LAB-FHC-INST', componentName: 'مصنعية تثبيت الصندوق وتوصيل الخط واختباره', unit: 'item', qtyPerUnit: 1.0, unitRate: 600, componentType: 'labor' },
        ],
        notes: 'صندوق حريق مجمع مجهز ومعتمد للدفاع المدني والمشاريع السكنية والتجارية.',
      },
      {
        item_code: 'FF-EXT-DRY-06',
        item_name: 'طفاية حريق يدوية بودرة كيميائية جافة ABC سعة 6 كجم مع الكابينة والحامل',
        unit: 'item',
        waste_percent: 2.0,
        overhead_percent: 7.0,
        profit_markup_percent: 15.0,
        components: [
          { componentCode: 'MAT-EXT-DRY-6KG', componentName: 'طفاية بودرة ABC سعة 6 كجم معتمدة بالمانومتر', unit: 'item', qtyPerUnit: 1.0, unitRate: 520, componentType: 'material' },
          { componentCode: 'MAT-EXT-BRK', componentName: 'حامل تثبيت جداري ومسامير فيشر صلب', unit: 'item', qtyPerUnit: 1.0, unitRate: 40, componentType: 'material' },
          { componentCode: 'LAB-EXT-INST', componentName: 'مصنعية تركيب وتثبيت واستيكر فحص', unit: 'item', qtyPerUnit: 1.0, unitRate: 90, componentType: 'labor' },
        ],
        notes: 'طفاية حريق يدوية بودرة جافة ABC للأماكن العامة والممرات.',
      },
      {
        item_code: 'FF-EXT-CO2-06',
        item_name: 'طفاية حريق غاز ثاني أكسيد الكربون CO2 سعة 6 كجم لغرف ولوحات الكهرباء',
        unit: 'item',
        waste_percent: 2.0,
        overhead_percent: 7.0,
        profit_markup_percent: 15.0,
        components: [
          { componentCode: 'MAT-EXT-CO2-6KG', componentName: 'طفاية غاز CO2 سعة 6 كجم سيملس بالخرطوم والعدسة', unit: 'item', qtyPerUnit: 1.0, unitRate: 1150, componentType: 'material' },
          { componentCode: 'MAT-EXT-BRK', componentName: 'حامل تثبيت جداري ثقيل', unit: 'item', qtyPerUnit: 1.0, unitRate: 60, componentType: 'material' },
          { componentCode: 'LAB-EXT-INST', componentName: 'مصنعية تثبيت واستيكر معايرة', unit: 'item', qtyPerUnit: 1.0, unitRate: 110, componentType: 'labor' },
        ],
        notes: 'طفاية CO2 سعة 6 كجم للمخاطر واللوحات الكهربائية.',
      },
      {
        item_code: 'FF-SYS-FSRCH-01',
        item_name: 'نظام إطفاء لوحات الكهرباء التلقائي الذاتي Fire Search بأنبوب الاستشعار وشحنة CO2',
        unit: 'ls',
        waste_percent: 2.0,
        overhead_percent: 7.0,
        profit_markup_percent: 15.0,
        components: [
          { componentCode: 'MAT-FSRCH-CYL', componentName: 'أسطوانة غاز CO2/إطفاء مزودة برأس الصمام', unit: 'item', qtyPerUnit: 1.0, unitRate: 3500, componentType: 'material' },
          { componentCode: 'MAT-FSRCH-TUBE', componentName: 'خرطوم استشعار حراري Sensing Tube وكلبسات تثبيت', unit: 'ls', qtyPerUnit: 1.0, unitRate: 1800, componentType: 'material' },
          { componentCode: 'LAB-FSRCH-INST', componentName: 'مصنعية فني متخصص لتركيب وبرمجة واختبار النظام', unit: 'ls', qtyPerUnit: 1.0, unitRate: 1200, componentType: 'labor' },
        ],
        notes: 'نظام إطفاء ذاتي للوحات الكهربائية بخرطوم استشعاري حراري.',
      },
    ];

    for (const c of mepEngineeringConstants) {
      await sql`
        INSERT INTO contracting_engineering_constants (
          tenant_id, item_code, item_name, unit, waste_percent, overhead_percent, profit_markup_percent, components_json, notes
        ) VALUES (
          '', ${c.item_code}, ${c.item_name}, ${c.unit}, ${c.waste_percent}, ${c.overhead_percent}, ${c.profit_markup_percent}, ${JSON.stringify(c.components)}::jsonb, ${c.notes}
        )
        ON CONFLICT (tenant_id, item_code) DO UPDATE SET
          item_name = EXCLUDED.item_name,
          unit = EXCLUDED.unit,
          waste_percent = EXCLUDED.waste_percent,
          overhead_percent = EXCLUDED.overhead_percent,
          profit_markup_percent = EXCLUDED.profit_markup_percent,
          components_json = EXCLUDED.components_json,
          notes = EXCLUDED.notes,
          updated_at = NOW();
      `.execute(db);
    }
  },

  async down(db: Kysely<unknown>): Promise<void> {
    const codes = [
      'FF-PIP-STM-65', 'FF-PIP-STM-40', 'FF-PIP-STM-50', 'FF-PIP-STM-80', 'FF-PIP-STM-100',
      'FF-PIP-HDP-90', 'FF-PIP-HDP-65', 'FF-PIP-HDP-110', 'FF-VLV-NRS-80', 'FF-VLV-OSY-100',
      'FF-VLV-AAV-25', 'FF-FHC-COMB-02', 'FF-FHC-SGL-01', 'FF-EXT-DRY-06', 'FF-EXT-CO2-06',
      'FF-SYS-FSRCH-01', 'FF-SPK-PND-15', 'FF-PMP-SET-500',
      'ELE-CBL-4X16', 'ELE-CBL-4X35', 'ELE-PNL-MDB', 'ELE-LGT-LED-60', 'ELE-EARTH-PIT',
      'PLM-PIP-PPR-32', 'PLM-PIP-UPVC-110', 'PLM-MNH-BRK-60',
      'HVC-VRF-OUT-16', 'HVC-FCU-CONC-03', 'HVC-DCT-GI-100',
    ];

    for (const code of codes) {
      await sql`
        DELETE FROM contracting_master_boq_library WHERE tenant_id = '' AND item_code = ${code};
      `.execute(db);
      await sql`
        DELETE FROM contracting_engineering_constants WHERE tenant_id = '' AND item_code = ${code};
      `.execute(db);
    }
  },
};
