import { Kysely, sql } from 'kysely';

export const migration = {
  up: async (db: Kysely<any>): Promise<void> => {
    await sql`
      CREATE TABLE IF NOT EXISTS saas_client_diagnostics (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        client_name TEXT NOT NULL,
        client_identifier TEXT NOT NULL,
        app_version TEXT NOT NULL DEFAULT '',
        log_period TEXT NOT NULL DEFAULT '',
        error_count_500 INTEGER NOT NULL DEFAULT 0,
        error_summary JSONB NULL,
        file_path TEXT NOT NULL,
        file_size_bytes BIGINT NOT NULL DEFAULT 0,
        uploaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_saas_client_diag_identifier
      ON saas_client_diagnostics (client_identifier);
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_saas_client_diag_uploaded_at
      ON saas_client_diagnostics (uploaded_at DESC);
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_saas_client_diag_errors
      ON saas_client_diagnostics (error_count_500 DESC);
    `.execute(db);
  },

  down: async (db: Kysely<any>): Promise<void> => {
    await sql`DROP TABLE IF EXISTS saas_client_diagnostics;`.execute(db);
  },
};
