import { sql, type Kysely } from 'kysely';

// Closes the "Rate Management" gap found in the September 2026 freight-forwarding
// benchmark (CargoWise/GoFreight): the only pricing mechanism was a live RFQ
// (ask now, wait for carrier bids) with no persisted, reusable contract-rate
// table to instantly quote against and compare margins — unlike CargoWise's
// tariff/contract rate management.
export const migration = {
  async up(db: Kysely<unknown>): Promise<void> {
    await sql`
      CREATE TABLE IF NOT EXISTS maritime_rate_cards (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        shipping_line_id BIGINT NULL REFERENCES shipping_lines(id) ON DELETE SET NULL,
        carrier_name TEXT NOT NULL DEFAULT '',
        pol_code TEXT NOT NULL,
        pol_name TEXT NOT NULL DEFAULT '',
        pod_code TEXT NOT NULL,
        pod_name TEXT NOT NULL DEFAULT '',
        cargo_mode TEXT NOT NULL DEFAULT 'FCL',
        container_type TEXT NOT NULL DEFAULT '40HC',
        ocean_freight NUMERIC(15, 3) NOT NULL DEFAULT 0,
        currency TEXT NOT NULL DEFAULT 'USD',
        thc_origin NUMERIC(15, 3) NOT NULL DEFAULT 0,
        thc_destination NUMERIC(15, 3) NOT NULL DEFAULT 0,
        baf_charges NUMERIC(15, 3) NOT NULL DEFAULT 0,
        other_charges NUMERIC(15, 3) NOT NULL DEFAULT 0,
        total_freight_cost NUMERIC(15, 3) NOT NULL DEFAULT 0,
        transit_time_days INTEGER NOT NULL DEFAULT 0,
        free_days INTEGER NOT NULL DEFAULT 14,
        valid_from DATE NOT NULL DEFAULT CURRENT_DATE,
        valid_until DATE NOT NULL,
        source TEXT NOT NULL DEFAULT 'manual',
        source_bid_id BIGINT NULL REFERENCES maritime_rfq_bids(id) ON DELETE SET NULL,
        status TEXT NOT NULL DEFAULT 'active',
        notes TEXT NULL,
        created_by BIGINT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT chk_maritime_rate_cards_status CHECK (status IN ('active', 'expired', 'draft')),
        CONSTRAINT chk_maritime_rate_cards_source CHECK (source IN ('manual', 'carrier_bid')),
        CONSTRAINT chk_maritime_rate_cards_validity CHECK (valid_until >= valid_from)
      );
    `.execute(db);

    // A carrier may legitimately have several overlapping rates on the same lane
    // (e.g. spot vs contract), so uniqueness is scoped to lane+container+validity
    // start rather than a hard one-rate-per-lane rule.
    await sql`
      CREATE UNIQUE INDEX IF NOT EXISTS uq_maritime_rate_cards_lane_validity
      ON maritime_rate_cards (tenant_id, COALESCE(shipping_line_id, 0), pol_code, pod_code, container_type, valid_from);
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_maritime_rate_cards_lookup
      ON maritime_rate_cards (tenant_id, pol_code, pod_code, container_type, status, valid_until);
    `.execute(db);
  },

  async down(db: Kysely<unknown>): Promise<void> {
    await sql`DROP TABLE IF EXISTS maritime_rate_cards;`.execute(db);
  },
};
