import { sql, type Kysely } from 'kysely';

export const migration = {
  async up(db: Kysely<unknown>): Promise<void> {
    const standardEngineeringConstants = [
      {
        item_code: 'BRK-RED-12',
        item_name: 'مباني طوب أحمر طفلي 12 سم (قاطع نصف طوبة بالمتر المسطح)',
        unit: 'm2',
        waste_percent: 5.0,
        overhead_percent: 7.0,
        profit_markup_percent: 15.0,
        components: [
          { componentCode: 'BRK-RED-CLAY', componentName: 'طوب أحمر طفلي 25×12×6 سم', unit: 'pcs', qtyPerUnit: 55, unitRate: 2.2, componentType: 'material' },
          { componentCode: 'SAND-MASON', componentName: 'رمل بناء حرش نظيف', unit: 'm3', qtyPerUnit: 0.02, unitRate: 180, componentType: 'material' },
          { componentCode: 'CEM-PORT', componentName: 'أسمنت بورتلاندي 42.5', unit: 'ton', qtyPerUnit: 0.01, unitRate: 2400, componentType: 'material' },
          { componentCode: 'LABOR-MASON', componentName: 'مصنعية بنا ومساعد ونقل داخلي', unit: 'm2', qtyPerUnit: 1.0, unitRate: 70, componentType: 'labor' },
        ],
        notes: 'كود المباني القياسي: المتر المسطح سمك 12 سم يستهلك معيارياً 55 طوبة + 0.02 م3 رمل + 10 كجم أسمنت + مصنعية البنا.',
      },
      {
        item_code: 'BRK-SOL-25',
        item_name: 'مباني طوب أسمنتي مصمت 25 سم (طوبة كاملة بالمتر المكعب)',
        unit: 'm3',
        waste_percent: 5.0,
        overhead_percent: 7.0,
        profit_markup_percent: 15.0,
        components: [
          { componentCode: 'BRK-SOL-CONC', componentName: 'طوب أسمنتي مصمت 25×12×6 سم', unit: 'pcs', qtyPerUnit: 450, unitRate: 2.8, componentType: 'material' },
          { componentCode: 'SAND-MASON', componentName: 'رمل بناء حرش نظيف', unit: 'm3', qtyPerUnit: 0.2, unitRate: 180, componentType: 'material' },
          { componentCode: 'CEM-PORT', componentName: 'أسمنت بورتلاندي 42.5', unit: 'ton', qtyPerUnit: 0.065, unitRate: 2400, componentType: 'material' },
          { componentCode: 'LABOR-MASON-CUB', componentName: 'مصنعية بنا وطاقم عمالة للمكعب', unit: 'm3', qtyPerUnit: 1.0, unitRate: 320, componentType: 'labor' },
        ],
        notes: 'كود المباني المكعبة: المتر المكعب سمك 25 سم يستهلك معيارياً 450 طوبة + 0.2 م3 رمل + 65 كجم أسمنت.',
      },
      {
        item_code: 'BRK-HLL-20',
        item_name: 'مباني طوب أسمنتي مفرغ 20×20×40 سم (بالمتر المسطح)',
        unit: 'm2',
        waste_percent: 5.0,
        overhead_percent: 7.0,
        profit_markup_percent: 15.0,
        components: [
          { componentCode: 'BRK-BLK-HLL', componentName: 'طوب أسمنتي مفرغ 20×20×40', unit: 'pcs', qtyPerUnit: 12.5, unitRate: 18, componentType: 'material' },
          { componentCode: 'SAND-MASON', componentName: 'رمل بناء حرش نظيف', unit: 'm3', qtyPerUnit: 0.04, unitRate: 180, componentType: 'material' },
          { componentCode: 'CEM-PORT', componentName: 'أسمنت بورتلاندي 42.5', unit: 'ton', qtyPerUnit: 0.015, unitRate: 2400, componentType: 'material' },
          { componentCode: 'LABOR-MASON', componentName: 'مصنعية بنا ومساعد', unit: 'm2', qtyPerUnit: 1.0, unitRate: 85, componentType: 'labor' },
        ],
        notes: 'مباني بلك أسمنتي مفرغ 20 سم للمناور والحوائط الخارجية.',
      },
      {
        item_code: 'CONC-PLN-C20',
        item_name: 'خرسانة عادية للأساسات والفرشات C20 (بالمتر المكعب)',
        unit: 'm3',
        waste_percent: 4.0,
        overhead_percent: 7.0,
        profit_markup_percent: 15.0,
        components: [
          { componentCode: 'GRAV-CRUSH', componentName: 'سن 1 و 2 / زلط متدرج', unit: 'm3', qtyPerUnit: 0.8, unitRate: 280, componentType: 'material' },
          { componentCode: 'SAND-CRS', componentName: 'رمل حرش نظيف', unit: 'm3', qtyPerUnit: 0.4, unitRate: 180, componentType: 'material' },
          { componentCode: 'CEM-PORT', componentName: 'أسمنت بورتلاندي 42.5 (5 شكاير)', unit: 'ton', qtyPerUnit: 0.25, unitRate: 2400, componentType: 'material' },
          { componentCode: 'LABOR-PLN-CONC', componentName: 'مصنعية نجارة وفرش ودك خرسانة عادية', unit: 'm3', qtyPerUnit: 1.0, unitRate: 220, componentType: 'labor' },
        ],
        notes: 'متر مكعب خرسانة عادية C20 محتوى 250 كجم أسمنت / م3.',
      },
      {
        item_code: 'CONC-FTG-C30',
        item_name: 'خرسانة مسلحة للقواعد والأساسات C30 (بالمتر المكعب)',
        unit: 'm3',
        waste_percent: 5.0,
        overhead_percent: 7.0,
        profit_markup_percent: 15.0,
        components: [
          { componentCode: 'GRAV-CRUSH', componentName: 'سن 1 و 2 / زلط متدرج', unit: 'm3', qtyPerUnit: 0.8, unitRate: 280, componentType: 'material' },
          { componentCode: 'SAND-CRS', componentName: 'رمل حرش نظيف', unit: 'm3', qtyPerUnit: 0.4, unitRate: 180, componentType: 'material' },
          { componentCode: 'CEM-PORT', componentName: 'أسمنت بورتلاندي 42.5 (7 شكاير)', unit: 'ton', qtyPerUnit: 0.35, unitRate: 2400, componentType: 'material' },
          { componentCode: 'STEEL-REBAR', componentName: 'حديد تسليح عالي الإجهاد (85 كجم)', unit: 'ton', qtyPerUnit: 0.085, unitRate: 42000, componentType: 'material' },
          { componentCode: 'LABOR-FTG', componentName: 'مصنعية نجارة وحدادة وصب قواعد مسلحة', unit: 'm3', qtyPerUnit: 1.0, unitRate: 480, componentType: 'labor' },
        ],
        notes: 'متر مكعب خرسانة مسلحة للقواعد والسميلات واللبشة بمعدل حديد 85 كجم/م3.',
      },
      {
        item_code: 'CONC-COL-C35',
        item_name: 'خرسانة مسلحة للأعمدة والحوائط C35 (بالمتر المكعب)',
        unit: 'm3',
        waste_percent: 5.0,
        overhead_percent: 7.0,
        profit_markup_percent: 15.0,
        components: [
          { componentCode: 'GRAV-FINO', componentName: 'سن فينو متدرج نظيف', unit: 'm3', qtyPerUnit: 0.8, unitRate: 310, componentType: 'material' },
          { componentCode: 'SAND-CRS', componentName: 'رمل حرش نظيف', unit: 'm3', qtyPerUnit: 0.4, unitRate: 180, componentType: 'material' },
          { componentCode: 'CEM-PORT', componentName: 'أسمنت بورتلاندي 42.5 (8 شكاير)', unit: 'ton', qtyPerUnit: 0.40, unitRate: 2400, componentType: 'material' },
          { componentCode: 'STEEL-REBAR', componentName: 'حديد تسليح عالي الإجهاد (140 كجم)', unit: 'ton', qtyPerUnit: 0.140, unitRate: 42000, componentType: 'material' },
          { componentCode: 'LABOR-COL', componentName: 'مصنعية نجارة وحدادة وصب أعمدة وحوائط', unit: 'm3', qtyPerUnit: 1.0, unitRate: 650, componentType: 'labor' },
        ],
        notes: 'متر مكعب خرسانة أعمدة وحوائط خرسانية C35 بمعدل حديد 140 كجم/م3.',
      },
      {
        item_code: 'CONC-SLB-C30',
        item_name: 'خرسانة مسلحة للأسقف والكمرات C30 (بالمتر المكعب)',
        unit: 'm3',
        waste_percent: 5.0,
        overhead_percent: 7.0,
        profit_markup_percent: 15.0,
        components: [
          { componentCode: 'GRAV-CRUSH', componentName: 'سن 1 و 2 / زلط متدرج', unit: 'm3', qtyPerUnit: 0.8, unitRate: 280, componentType: 'material' },
          { componentCode: 'SAND-CRS', componentName: 'رمل حرش نظيف', unit: 'm3', qtyPerUnit: 0.4, unitRate: 180, componentType: 'material' },
          { componentCode: 'CEM-PORT', componentName: 'أسمنت بورتلاندي 42.5 (7 شكاير)', unit: 'ton', qtyPerUnit: 0.35, unitRate: 2400, componentType: 'material' },
          { componentCode: 'STEEL-REBAR', componentName: 'حديد تسليح عالي الإجهاد (110 كجم)', unit: 'ton', qtyPerUnit: 0.110, unitRate: 42000, componentType: 'material' },
          { componentCode: 'LABOR-SLB', componentName: 'مصنعية شدات خشبية وحدادة وصب أسقف', unit: 'm3', qtyPerUnit: 1.0, unitRate: 550, componentType: 'labor' },
        ],
        notes: 'متر مكعب خرسانة أسقف وكمرات (سوليد / فلات سلاب) بمعدل حديد 110 كجم/م3.',
      },
      {
        item_code: 'PLAS-INT-01',
        item_name: 'أعمال بياض ومحارة داخلية للحوائط والأسقف (بالمتر المسطح)',
        unit: 'm2',
        waste_percent: 4.0,
        overhead_percent: 7.0,
        profit_markup_percent: 15.0,
        components: [
          { componentCode: 'SAND-PLAS', componentName: 'رمل ناعم للمحارة والطرطشة', unit: 'm3', qtyPerUnit: 0.025, unitRate: 180, componentType: 'material' },
          { componentCode: 'CEM-PORT', componentName: 'أسمنت بورتلاندي للمحارة', unit: 'ton', qtyPerUnit: 0.009, unitRate: 2400, componentType: 'material' },
          { componentCode: 'MESH-FIBER', componentName: 'سلك شبك فواصل وزوايا معدنية', unit: 'm', qtyPerUnit: 0.4, unitRate: 15, componentType: 'material' },
          { componentCode: 'LABOR-PLAS', componentName: 'مصنعية مبيض محارة وطاقمه', unit: 'm2', qtyPerUnit: 1.0, unitRate: 75, componentType: 'labor' },
        ],
        notes: 'بياض ومحارة داخلية طرطشة مسمارية + بؤج وأوتار + بطانة وضهارة ناعمة.',
      },
      {
        item_code: 'PLAS-EXT-02',
        item_name: 'أعمال بياض ومحارة واجهات ودراي ميكس ملونة (بالمتر المسطح)',
        unit: 'm2',
        waste_percent: 5.0,
        overhead_percent: 7.0,
        profit_markup_percent: 15.0,
        components: [
          { componentCode: 'SAND-PLAS', componentName: 'رمل محارة للبطانة', unit: 'm3', qtyPerUnit: 0.03, unitRate: 180, componentType: 'material' },
          { componentCode: 'CEM-PORT', componentName: 'أسمنت بورتلاندي', unit: 'ton', qtyPerUnit: 0.012, unitRate: 2400, componentType: 'material' },
          { componentCode: 'DRYMIX-TOP', componentName: 'عبوات بياض واجهات ملونة دراي ميكس', unit: 'kg', qtyPerUnit: 4.0, unitRate: 22, componentType: 'material' },
          { componentCode: 'LABOR-PLAS-EXT', componentName: 'مصنعية مبيض واجهات وسقالات', unit: 'm2', qtyPerUnit: 1.0, unitRate: 120, componentType: 'labor' },
        ],
        notes: 'محارة واجهات خارجية بطانة مضاف إليها مانع نفاذية + ضهارة دراي ميكس ملونة.',
      },
      {
        item_code: 'TILE-FLR-CER',
        item_name: 'سيراميك أرضيات فرز أول بالفرشة والمونة (بالمتر المسطح)',
        unit: 'm2',
        waste_percent: 7.0,
        overhead_percent: 7.0,
        profit_markup_percent: 15.0,
        components: [
          { componentCode: 'TILE-CER-FLR', componentName: 'بلاط سيراميك أرضيات فرز أول', unit: 'm2', qtyPerUnit: 1.05, unitRate: 260, componentType: 'material' },
          { componentCode: 'SAND-FILL', componentName: 'رمل فرشة وتأسيس منسوب', unit: 'm3', qtyPerUnit: 0.05, unitRate: 180, componentType: 'material' },
          { componentCode: 'CEM-PORT', componentName: 'أسمنت أسود لمونة التركيب', unit: 'ton', qtyPerUnit: 0.012, unitRate: 2400, componentType: 'material' },
          { componentCode: 'GROUT-WHT', componentName: 'أسمنت أبيض وروبة سقية فواصل', unit: 'kg', qtyPerUnit: 0.5, unitRate: 35, componentType: 'material' },
          { componentCode: 'LABOR-TILE', componentName: 'مصنعية مبلط أرضيات ومساعد', unit: 'm2', qtyPerUnit: 1.0, unitRate: 95, componentType: 'labor' },
        ],
        notes: 'سيراميك أرضيات فرز أول بالرمل والمونة الأسمنتية وسقية العراميس.',
      },
      {
        item_code: 'TILE-WAL-CER',
        item_name: 'سيراميك حوائط حمامات ومطابخ (بالمتر المسطح)',
        unit: 'm2',
        waste_percent: 7.0,
        overhead_percent: 7.0,
        profit_markup_percent: 15.0,
        components: [
          { componentCode: 'TILE-CER-WAL', componentName: 'بلاط سيراميك حوائط ديكور', unit: 'm2', qtyPerUnit: 1.05, unitRate: 280, componentType: 'material' },
          { componentCode: 'CEM-PORT', componentName: 'أسمنت أسود للمونة والطرطشة', unit: 'ton', qtyPerUnit: 0.015, unitRate: 2400, componentType: 'material' },
          { componentCode: 'GROUT-WHT', componentName: 'روبة سقية عراميس وسيليكون', unit: 'kg', qtyPerUnit: 0.6, unitRate: 35, componentType: 'material' },
          { componentCode: 'LABOR-TILE-WAL', componentName: 'مصنعية مبلط حوائط ووزنات ليزر', unit: 'm2', qtyPerUnit: 1.0, unitRate: 110, componentType: 'labor' },
        ],
        notes: 'سيراميك حوائط حمامات ومطابخ كامل الارتفاع مع وزنات الشيرب.',
      },
      {
        item_code: 'TILE-PORC-60',
        item_name: 'بورسلين أرضيات 60×120 سم بالمادة اللاصقة (بالمتر المسطح)',
        unit: 'm2',
        waste_percent: 7.0,
        overhead_percent: 7.0,
        profit_markup_percent: 15.0,
        components: [
          { componentCode: 'PORC-SLAB', componentName: 'بلاطات بورسلين هندي/إسباني 60×120', unit: 'm2', qtyPerUnit: 1.05, unitRate: 450, componentType: 'material' },
          { componentCode: 'SAND-FILL', componentName: 'رمل تسوية', unit: 'm3', qtyPerUnit: 0.04, unitRate: 180, componentType: 'material' },
          { componentCode: 'ADH-MORT', componentName: 'شكارة مادة لاصقة للبورسلين معتمدة', unit: 'kg', qtyPerUnit: 6.0, unitRate: 18, componentType: 'material' },
          { componentCode: 'LEVEL-CLIPS', componentName: 'صلايب وكلبسات ضبط استواء ليزر', unit: 'set', qtyPerUnit: 1.0, unitRate: 25, componentType: 'material' },
          { componentCode: 'LABOR-PORC', componentName: 'مصنعية فني تركيب بورسلين محترف', unit: 'm2', qtyPerUnit: 1.0, unitRate: 140, componentType: 'labor' },
        ],
        notes: 'بورسلين أرضيات مقاسات كبرى بفرشة مادة لاصقة سافيتو/سيكا وكلبسات تسوية.',
      },
      {
        item_code: 'PAINT-INT-03',
        item_name: 'دهانات داخلية بلاستيك 3 أوجه وسيلر ومعجون (بالمتر المسطح)',
        unit: 'm2',
        waste_percent: 5.0,
        overhead_percent: 7.0,
        profit_markup_percent: 15.0,
        components: [
          { componentCode: 'PAINT-SEAL', componentName: 'سيلر مائي مقاوم للقلويات', unit: 'L', qtyPerUnit: 0.15, unitRate: 45, componentType: 'material' },
          { componentCode: 'PAINT-PUTTY', componentName: 'معجون بلاستيك جاهز 3 سكاكين', unit: 'kg', qtyPerUnit: 1.4, unitRate: 30, componentType: 'material' },
          { componentCode: 'PAINT-PLAS', componentName: 'دهان بلاستيك نصف لمعة قابل للغسيل', unit: 'L', qtyPerUnit: 0.25, unitRate: 120, componentType: 'material' },
          { componentCode: 'LABOR-PAINT', componentName: 'مصنعية نقاش وصنفرة وتشطيب', unit: 'm2', qtyPerUnit: 1.0, unitRate: 60, componentType: 'labor' },
        ],
        notes: 'دهانات داخلية وجه سيلر + 3 سكاكين معجون + وجهين بلاستيك نصف لمعة ممتاز.',
      },
      {
        item_code: 'ISO-WTR-BIT',
        item_name: 'عزل رطوبة ممبرين بيتوميني 4 مم وحرارة فوم 5 سم للأسطح (بالمتر المسطح)',
        unit: 'm2',
        waste_percent: 6.0,
        overhead_percent: 7.0,
        profit_markup_percent: 15.0,
        components: [
          { componentCode: 'BIT-MEMB-4MM', componentName: 'لفائف ممبرين بيتوميني 4 مم بوليستر', unit: 'm2', qtyPerUnit: 1.15, unitRate: 180, componentType: 'material' },
          { componentCode: 'BIT-PRIMER', componentName: 'برايمر بيتوميني دهان تأسيس', unit: 'kg', qtyPerUnit: 0.3, unitRate: 65, componentType: 'material' },
          { componentCode: 'XPS-FOAM-5CM', componentName: 'ألواح فوم عازل حراري XPS سمك 5 سم', unit: 'm2', qtyPerUnit: 1.05, unitRate: 160, componentType: 'material' },
          { componentCode: 'LABOR-INSUL', componentName: 'مصنعية فني عزل ولحام لهب', unit: 'm2', qtyPerUnit: 1.0, unitRate: 75, componentType: 'labor' },
        ],
        notes: 'عزل أسطح مزدوج رطوبة ممبرين 4 مم مع ركوب 10 سم وعزل حراري فوم XPS كثافة 36 كجم.',
      },
      {
        item_code: 'ISO-CHM-WET',
        item_name: 'عزل أسمنتي كيميائي مرن للحمامات والمطابخ (بالمتر المسطح)',
        unit: 'm2',
        waste_percent: 5.0,
        overhead_percent: 7.0,
        profit_markup_percent: 15.0,
        components: [
          { componentCode: 'CEM-CHEM-ISO', componentName: 'عبوة عازل أسمنتي بوليمري مرن وجهين', unit: 'kg', qtyPerUnit: 3.5, unitRate: 75, componentType: 'material' },
          { componentCode: 'FIBER-TAPE', componentName: 'شريط فيبر جلاس لأركان رقبة الزجاجة', unit: 'm', qtyPerUnit: 0.5, unitRate: 15, componentType: 'material' },
          { componentCode: 'LABOR-ISO-WET', componentName: 'مصنعية تجهيز أرضيات وعزل واختبار غمر', unit: 'm2', qtyPerUnit: 1.0, unitRate: 80, componentType: 'labor' },
        ],
        notes: 'عزل حمامات ومطابخ مركب أسمنتي مرن سيكاتوب أو كيماكول وجهين متعامدين واختبار مياه 48 ساعة.',
      },
      {
        item_code: 'EXCAV-SOIL',
        item_name: 'أعمال حفر في تربة رملية/طينية وتشوين ونقل للمقالب (بالمتر المكعب)',
        unit: 'm3',
        waste_percent: 0.0,
        overhead_percent: 7.0,
        profit_markup_percent: 15.0,
        components: [
          { componentCode: 'EQP-EXCAV', componentName: 'ساعة تشغيل حفار كوماتسو', unit: 'hr', qtyPerUnit: 0.04, unitRate: 1200, componentType: 'equipment' },
          { componentCode: 'EQP-LOADER', componentName: 'ساعة تشغيل لودر وتشوين', unit: 'hr', qtyPerUnit: 0.03, unitRate: 900, componentType: 'equipment' },
          { componentCode: 'TRUCK-HAUL', componentName: 'نقل وتعتيق مخلفات بالمقطورة', unit: 'm3', qtyPerUnit: 1.0, unitRate: 65, componentType: 'subcontractor' },
        ],
        notes: 'أعمال حفر الموقع حتى المنسوب التأسيسي المعتمد ونقل ناتج الحفر.',
      },
      {
        item_code: 'BACKFILL-CMP',
        item_name: 'أعمال ردم بطبقات سن ورمل مع الرش والدمك والاختبار (بالمتر المكعب)',
        unit: 'm3',
        waste_percent: 5.0,
        overhead_percent: 7.0,
        profit_markup_percent: 15.0,
        components: [
          { componentCode: 'GRAV-FILL', componentName: 'ناتج سن متدرج لطبقات الإحلال', unit: 'm3', qtyPerUnit: 0.7, unitRate: 220, componentType: 'material' },
          { componentCode: 'SAND-CRS', componentName: 'رمل حرش للتثبيت والخلط', unit: 'm3', qtyPerUnit: 0.3, unitRate: 180, componentType: 'material' },
          { componentCode: 'EQP-ROLLER', componentName: 'إيجار هراس ودكاك ميكانيكي', unit: 'm3', qtyPerUnit: 1.0, unitRate: 45, componentType: 'equipment' },
          { componentCode: 'LABOR-FILL', componentName: 'عمالة فرد وضبط مناسيب واختبار بروكتور', unit: 'm3', qtyPerUnit: 1.0, unitRate: 35, componentType: 'labor' },
        ],
        notes: 'ردم وإحلال على طبقات 25 سم مع الرش والدمك للوصول إلى نسبة دمك 95% على الأقل.',
      },
      {
        item_code: 'PLUMB-POINT',
        item_name: 'تأسيس شبكة تغذية وصرف صحي للحمام (بالنقطة / المخرج)',
        unit: 'point',
        waste_percent: 5.0,
        overhead_percent: 7.0,
        profit_markup_percent: 15.0,
        components: [
          { componentCode: 'PPR-PIPE', componentName: 'مواسير ولوازم تغذية بولي بروبلين PPR معتمدة', unit: 'm', qtyPerUnit: 4.0, unitRate: 95, componentType: 'material' },
          { componentCode: 'PVC-DRAIN', componentName: 'مواسير ولوازم صرف رمادي ثقيل', unit: 'm', qtyPerUnit: 3.5, unitRate: 85, componentType: 'material' },
          { componentCode: 'VALVES-ACC', componentName: 'محابس زاوية وجلب سن وفحص', unit: 'set', qtyPerUnit: 1.0, unitRate: 320, componentType: 'material' },
          { componentCode: 'LABOR-PLUMB', componentName: 'مصنعية سباك واختبار ضغط هيدروليكي', unit: 'point', qtyPerUnit: 1.0, unitRate: 350, componentType: 'labor' },
        ],
        notes: 'تأسيس شبكة السباكة الداخلية من أجود أنواع البولي بروبلين واختبار بالبار بحضور الاستشاري.',
      },
      {
        item_code: 'ELEC-POINT',
        item_name: 'تأسيس نقطة كهرباء وإنارة ومخارج قوى (بالنقطة / المخرج)',
        unit: 'point',
        waste_percent: 5.0,
        overhead_percent: 7.0,
        profit_markup_percent: 15.0,
        components: [
          { componentCode: 'ELEC-WIRE', componentName: 'أسلاك نحاس معتمدة السويدي 2.5 و 3 مم', unit: 'm', qtyPerUnit: 15.0, unitRate: 22, componentType: 'material' },
          { componentCode: 'PVC-CONDUIT', componentName: 'خراطيم بيتفين وعُلب ماجيك وشاسيهات', unit: 'set', qtyPerUnit: 1.0, unitRate: 85, componentType: 'material' },
          { componentCode: 'LABOR-ELEC', componentName: 'مصنعية فني كهربائي وتكسير وتمديد', unit: 'point', qtyPerUnit: 1.0, unitRate: 180, componentType: 'labor' },
        ],
        notes: 'تأسيس مخارج الكهرباء والإنارة شاملة سحب الأسلاك والخراطيم وتثبيت العلب والشاسيهات.',
      },
      {
        item_code: 'GYPS-CEIL-01',
        item_name: 'أسقف معلقة جبسوم بورد مقاوم للرطوبة أخضر (بالمتر المسطح)',
        unit: 'm2',
        waste_percent: 5.0,
        overhead_percent: 7.0,
        profit_markup_percent: 15.0,
        components: [
          { componentCode: 'GYPS-BOARD', componentName: 'ألواح جبسوم بورد خضراء مقاومة للرطوبة 12.5 مم', unit: 'm2', qtyPerUnit: 1.05, unitRate: 160, componentType: 'material' },
          { componentCode: 'STEEL-GRID', componentName: 'شاسيه صاج مجلفن أوميجا وزوايا وتيش تعليق', unit: 'm2', qtyPerUnit: 1.0, unitRate: 110, componentType: 'material' },
          { componentCode: 'PUTTY-FIBER', componentName: 'معجون فواصل وشريط فيبر ومسامير', unit: 'm2', qtyPerUnit: 1.0, unitRate: 35, componentType: 'material' },
          { componentCode: 'LABOR-GYPS', componentName: 'مصنعية فني تركيب جبسوم بورد ومساعد', unit: 'm2', qtyPerUnit: 1.0, unitRate: 95, componentType: 'labor' },
        ],
        notes: 'أسقف جبسوم بورد مستوية ومستويات شاملة الشاسيه المقاوم للصدأ وشريط الفواصل والمعجون.',
      },
    ];

    // Upsert standard engineering constants into database
    for (const c of standardEngineeringConstants) {
      await sql`
        INSERT INTO contracting_engineering_constants (
          tenant_id, item_code, item_name, unit, waste_percent, overhead_percent, profit_markup_percent, components_json, notes, created_at, updated_at
        )
        VALUES (
          'zs', ${c.item_code}, ${c.item_name}, ${c.unit}, ${c.waste_percent}, ${c.overhead_percent}, ${c.profit_markup_percent},
          ${JSON.stringify(c.components)}::jsonb, ${c.notes}, NOW(), NOW()
        )
        ON CONFLICT (tenant_id, item_code)
        DO UPDATE SET
          item_name = EXCLUDED.item_name,
          unit = EXCLUDED.unit,
          waste_percent = EXCLUDED.waste_percent,
          overhead_percent = EXCLUDED.overhead_percent,
          profit_markup_percent = EXCLUDED.profit_markup_percent,
          components_json = EXCLUDED.components_json,
          notes = EXCLUDED.notes,
          updated_at = NOW();
      `.execute(db);
    }
  },

  async down(_db: Kysely<unknown>): Promise<void> {
    // Non-destructive down migration
  },
};
