import { sql, type Kysely } from 'kysely';

export const migration = {
  async up(db: Kysely<unknown>): Promise<void> {
    // 1. Shipping Ports Table
    await sql`
      CREATE TABLE IF NOT EXISTS shipping_ports (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        code TEXT NOT NULL,
        name_ar TEXT NOT NULL,
        name_en TEXT NOT NULL,
        country_code TEXT NOT NULL DEFAULT 'EG',
        country_name TEXT NOT NULL DEFAULT '',
        is_active BOOLEAN NOT NULL DEFAULT TRUE,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_shipping_ports_tenant_code UNIQUE (tenant_id, code)
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_shipping_ports_tenant 
      ON shipping_ports (tenant_id, is_active);
    `.execute(db);

    // 2. Shipping Lines Table
    await sql`
      CREATE TABLE IF NOT EXISTS shipping_lines (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        code TEXT NOT NULL,
        name_ar TEXT NOT NULL,
        name_en TEXT NOT NULL,
        contact_person TEXT NULL,
        email TEXT NULL,
        rfq_email TEXT NULL,
        phone TEXT NULL,
        tracking_url_template TEXT NULL,
        is_active BOOLEAN NOT NULL DEFAULT TRUE,
        notes TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_shipping_lines_tenant_code UNIQUE (tenant_id, code)
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_shipping_lines_tenant 
      ON shipping_lines (tenant_id, is_active);
    `.execute(db);

    // 3. Maritime RFQs Table
    await sql`
      CREATE TABLE IF NOT EXISTS maritime_rfqs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        rfq_number TEXT NOT NULL,
        direction TEXT NOT NULL DEFAULT 'import',
        pol_id BIGINT NULL REFERENCES shipping_ports(id) ON DELETE SET NULL,
        pol_code TEXT NOT NULL,
        pol_name TEXT NOT NULL,
        pod_id BIGINT NULL REFERENCES shipping_ports(id) ON DELETE SET NULL,
        pod_code TEXT NOT NULL,
        pod_name TEXT NOT NULL,
        incoterm TEXT NOT NULL DEFAULT 'FOB',
        cargo_mode TEXT NOT NULL DEFAULT 'FCL',
        container_type TEXT NOT NULL DEFAULT '40HC',
        container_count INTEGER NOT NULL DEFAULT 1,
        commodity_description TEXT NOT NULL DEFAULT '',
        cargo_nature TEXT NOT NULL DEFAULT 'general',
        cargo_ready_date DATE NULL,
        target_free_days INTEGER NOT NULL DEFAULT 14,
        payment_term TEXT NOT NULL DEFAULT 'prepaid',
        target_line_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
        status TEXT NOT NULL DEFAULT 'draft',
        notes TEXT NULL,
        created_by BIGINT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_maritime_rfqs_tenant_number UNIQUE (tenant_id, rfq_number)
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_maritime_rfqs_tenant_status 
      ON maritime_rfqs (tenant_id, status);
    `.execute(db);

    // 4. Maritime RFQ Bids Table
    await sql`
      CREATE TABLE IF NOT EXISTS maritime_rfq_bids (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        rfq_id BIGINT NOT NULL REFERENCES maritime_rfqs(id) ON DELETE CASCADE,
        shipping_line_id BIGINT NULL REFERENCES shipping_lines(id) ON DELETE SET NULL,
        shipping_line_name TEXT NOT NULL,
        ocean_freight NUMERIC(15, 4) NOT NULL DEFAULT 0,
        currency TEXT NOT NULL DEFAULT 'USD',
        thc_origin NUMERIC(15, 4) NOT NULL DEFAULT 0,
        thc_destination NUMERIC(15, 4) NOT NULL DEFAULT 0,
        baf_charges NUMERIC(15, 4) NOT NULL DEFAULT 0,
        other_charges NUMERIC(15, 4) NOT NULL DEFAULT 0,
        total_freight_cost NUMERIC(15, 4) NOT NULL DEFAULT 0,
        transit_time_days INTEGER NOT NULL DEFAULT 0,
        free_days INTEGER NOT NULL DEFAULT 14,
        validity_date DATE NULL,
        submission_channel TEXT NOT NULL DEFAULT 'manual',
        raw_bid_data JSONB NULL,
        is_awarded BOOLEAN NOT NULL DEFAULT FALSE,
        awarded_at TIMESTAMPTZ NULL,
        notes TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_maritime_rfq_bids_rfq 
      ON maritime_rfq_bids (tenant_id, rfq_id, is_awarded);
    `.execute(db);

    // 5. Maritime Client Quotations Table
    await sql`
      CREATE TABLE IF NOT EXISTS maritime_quotations (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        quotation_number TEXT NOT NULL,
        rfq_id BIGINT NULL REFERENCES maritime_rfqs(id) ON DELETE SET NULL,
        bid_id BIGINT NULL REFERENCES maritime_rfq_bids(id) ON DELETE SET NULL,
        customer_id BIGINT NULL,
        customer_name TEXT NOT NULL,
        customer_phone TEXT NULL,
        customer_email TEXT NULL,
        payment_term TEXT NOT NULL DEFAULT 'prepaid',
        base_cost NUMERIC(15, 4) NOT NULL DEFAULT 0,
        currency TEXT NOT NULL DEFAULT 'USD',
        margin_type TEXT NOT NULL DEFAULT 'fixed',
        margin_value NUMERIC(15, 4) NOT NULL DEFAULT 0,
        final_total NUMERIC(15, 4) NOT NULL DEFAULT 0,
        exchange_rate NUMERIC(15, 6) NOT NULL DEFAULT 1.000000,
        final_total_local NUMERIC(15, 4) NOT NULL DEFAULT 0,
        valid_until DATE NULL,
        status TEXT NOT NULL DEFAULT 'draft',
        converted_job_id BIGINT NULL,
        notes TEXT NULL,
        created_by BIGINT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_maritime_quotations_tenant_num UNIQUE (tenant_id, quotation_number)
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_maritime_quotations_tenant_status 
      ON maritime_quotations (tenant_id, status);
    `.execute(db);

    // 6. Maritime Jobs Table (Shipment File)
    await sql`
      CREATE TABLE IF NOT EXISTS maritime_jobs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        job_number TEXT NOT NULL,
        quotation_id BIGINT NULL REFERENCES maritime_quotations(id) ON DELETE SET NULL,
        rfq_id BIGINT NULL REFERENCES maritime_rfqs(id) ON DELETE SET NULL,
        customer_id BIGINT NULL,
        customer_name TEXT NOT NULL,
        direction TEXT NOT NULL DEFAULT 'import',
        payment_term TEXT NOT NULL DEFAULT 'prepaid',
        shipping_line_id BIGINT NULL REFERENCES shipping_lines(id) ON DELETE SET NULL,
        shipping_line_name TEXT NOT NULL,
        booking_number TEXT NULL,
        vessel_name TEXT NULL,
        voyage_number TEXT NULL,
        pol_code TEXT NOT NULL,
        pol_name TEXT NOT NULL,
        pod_code TEXT NOT NULL,
        pod_name TEXT NOT NULL,
        etd DATE NULL,
        eta DATE NULL,
        port_cut_off TIMESTAMPTZ NULL,
        bl_type TEXT NOT NULL DEFAULT 'original',
        mbl_number TEXT NULL,
        hbl_number TEXT NULL,
        shipper_details TEXT NULL,
        consignee_details TEXT NULL,
        notify_party TEXT NULL,
        milestone_status TEXT NOT NULL DEFAULT 'BOOK',
        delivery_order_released BOOLEAN NOT NULL DEFAULT FALSE,
        delivery_order_released_at TIMESTAMPTZ NULL,
        cost_center_id BIGINT NULL REFERENCES cost_centers(id) ON DELETE SET NULL,
        client_invoiced_total NUMERIC(15, 4) NOT NULL DEFAULT 0,
        carrier_cost_total NUMERIC(15, 4) NOT NULL DEFAULT 0,
        other_costs_total NUMERIC(15, 4) NOT NULL DEFAULT 0,
        net_profit NUMERIC(15, 4) NOT NULL DEFAULT 0,
        tracking_token TEXT NULL,
        status TEXT NOT NULL DEFAULT 'active',
        notes TEXT NULL,
        created_by BIGINT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_maritime_jobs_tenant_num UNIQUE (tenant_id, job_number)
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_maritime_jobs_tenant_status 
      ON maritime_jobs (tenant_id, status, milestone_status);
    `.execute(db);

    // 7. Maritime Containers Table
    await sql`
      CREATE TABLE IF NOT EXISTS maritime_containers (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        job_id BIGINT NOT NULL REFERENCES maritime_jobs(id) ON DELETE CASCADE,
        container_number TEXT NOT NULL,
        container_type TEXT NOT NULL DEFAULT '40HC',
        seal_number TEXT NULL,
        gross_weight_kg NUMERIC(12, 2) NOT NULL DEFAULT 0,
        cbm NUMERIC(10, 2) NOT NULL DEFAULT 0,
        gated_in_at TIMESTAMPTZ NULL,
        vessel_loaded_at TIMESTAMPTZ NULL,
        discharged_at TIMESTAMPTZ NULL,
        gated_out_at TIMESTAMPTZ NULL,
        empty_returned_at TIMESTAMPTZ NULL,
        free_days INTEGER NOT NULL DEFAULT 14,
        return_deadline DATE NULL,
        is_overdue BOOLEAN NOT NULL DEFAULT FALSE,
        overdue_days INTEGER NOT NULL DEFAULT 0,
        demurrage_rate_per_day NUMERIC(10, 2) NOT NULL DEFAULT 0,
        demurrage_amount NUMERIC(15, 4) NOT NULL DEFAULT 0,
        deposit_amount NUMERIC(15, 4) NOT NULL DEFAULT 0,
        deposit_currency TEXT NOT NULL DEFAULT 'EGP',
        deposit_status TEXT NOT NULL DEFAULT 'held_by_line',
        deposit_treasury_id BIGINT NULL,
        empty_return_proof_url TEXT NULL,
        notes TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_maritime_containers_job 
      ON maritime_containers (tenant_id, job_id, is_overdue);
    `.execute(db);

    // 8. Maritime Milestones Table (DCSA standard events)
    await sql`
      CREATE TABLE IF NOT EXISTS maritime_job_milestones (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        job_id BIGINT NOT NULL REFERENCES maritime_jobs(id) ON DELETE CASCADE,
        milestone_key TEXT NOT NULL,
        milestone_title TEXT NOT NULL,
        occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        location TEXT NULL,
        notes TEXT NULL,
        recorded_by BIGINT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_maritime_milestones_job 
      ON maritime_job_milestones (tenant_id, job_id);
    `.execute(db);

    // 9. Initial Seed Data for Ports and Carriers across active tenants or templates
    // Seed standard ports
    await sql`
      INSERT INTO shipping_ports (tenant_id, code, name_ar, name_en, country_code, country_name)
      VALUES 
        ('default', 'EGALY', 'ميناء الإسكندرية', 'Alexandria Port', 'EG', 'مصر'),
        ('default', 'EGPSD', 'ميناء بورسعيد', 'Port Said', 'EG', 'مصر'),
        ('default', 'EGDAM', 'ميناء دمياط', 'Damietta Port', 'EG', 'مصر'),
        ('default', 'EGSOK', 'ميناء السخنة', 'Ain Sokhna Port', 'EG', 'مصر'),
        ('default', 'EGEDK', 'ميناء الدخيلة', 'El Dekheila Port', 'EG', 'مصر'),
        ('default', 'SAJED', 'ميناء جدة الإسلامي', 'Jeddah Islamic Port', 'SA', 'السعودية'),
        ('default', 'SADMM', 'ميناء الملك عبد العزيز بالدمام', 'King Abdulaziz Port Dammam', 'SA', 'السعودية'),
        ('default', 'AEJEA', 'ميناء جبل علي - دبي', 'Jebel Ali Port Dubai', 'AE', 'الإمارات'),
        ('default', 'AEAUH', 'ميناء خليفة - أبوظبي', 'Khalifa Port Abu Dhabi', 'AE', 'الإمارات'),
        ('default', 'CNSHA', 'ميناء شنغهاي', 'Shanghai Port', 'CN', 'الصين'),
        ('default', 'CNNGB', 'ميناء نينغبو', 'Ningbo-Zhoushan Port', 'CN', 'الصين'),
        ('default', 'CNSZX', 'ميناء شنجن', 'Shenzhen Port', 'CN', 'الصين'),
        ('default', 'CNQDG', 'ميناء تشينغداو', 'Qingdao Port', 'CN', 'الصين'),
        ('default', 'SGSIN', 'ميناء سنغافورة', 'Singapore Port', 'SG', 'سنغافورة'),
        ('default', 'NLRTM', 'ميناء روتردام', 'Port of Rotterdam', 'NL', 'هولندا'),
        ('default', 'DEHAM', 'ميناء هامبورغ', 'Port of Hamburg', 'DE', 'ألمانيا'),
        ('default', 'TRIST', 'ميناء إسطنبول', 'Istanbul Port', 'TR', 'تركيا'),
        ('default', 'INNSA', 'ميناء نهافا شيفا - الهند', 'Nhava Sheva (JNPT)', 'IN', 'الهند')
      ON CONFLICT (tenant_id, code) DO NOTHING;
    `.execute(db);

    // Seed standard shipping lines
    await sql`
      INSERT INTO shipping_lines (tenant_id, code, name_ar, name_en, email, rfq_email)
      VALUES
        ('default', 'MSCU', 'إم إس سي (MSC)', 'Mediterranean Shipping Company (MSC)', 'info@msc.com', 'rfq@msc.com'),
        ('default', 'MAEU', 'ميرسك (Maersk)', 'A.P. Moller – Maersk', 'info@maersk.com', 'rfq@maersk.com'),
        ('default', 'CMDU', 'سي إم إيه سي جي إم (CMA CGM)', 'CMA CGM Group', 'info@cma-cgm.com', 'rfq@cma-cgm.com'),
        ('default', 'COSU', 'كوسكو للملاحة (COSCO)', 'COSCO Shipping Lines', 'info@coscon.com', 'rfq@cosco.com'),
        ('default', 'HLCU', 'هاباج لويد (Hapag-Lloyd)', 'Hapag-Lloyd AG', 'info@hlag.com', 'rfq@hlag.com'),
        ('default', 'ONEY', 'أوشن نتورك إكسبريس (ONE)', 'Ocean Network Express (ONE)', 'info@one-line.com', 'rfq@one-line.com'),
        ('default', 'EGLV', 'إيفرجرين (Evergreen)', 'Evergreen Marine Corp', 'info@evergreen-marine.com', 'rfq@evergreen-marine.com'),
        ('default', 'YMLU', 'يانغ مينغ (Yang Ming)', 'Yang Ming Marine Transport', 'info@yangming.com', 'rfq@yangming.com'),
        ('default', 'ZIMU', 'زيم (ZIM)', 'ZIM Integrated Shipping', 'info@zim.com', 'rfq@zim.com')
      ON CONFLICT (tenant_id, code) DO NOTHING;
    `.execute(db);

    // 10. Register Feature and Associate with Ultimate & Omnichannel plans
    await sql`
      INSERT INTO features (id, code, name, module)
      VALUES ('feat_maritime_freight', 'maritime_freight', 'الشحن البحري واللوجستيات والموانئ', 'maritime_freight')
      ON CONFLICT (code) DO UPDATE SET
        name = EXCLUDED.name,
        module = EXCLUDED.module;
    `.execute(db);

    await sql`
      INSERT INTO plan_features (plan_id, feature_code)
      VALUES 
        ('plan_ultimate', 'maritime_freight'),
        ('plan_omnichannel', 'maritime_freight')
      ON CONFLICT DO NOTHING;
    `.execute(db);
  },

  async down(db: Kysely<unknown>): Promise<void> {
    await sql`DROP TABLE IF EXISTS maritime_job_milestones;`.execute(db);
    await sql`DROP TABLE IF EXISTS maritime_containers;`.execute(db);
    await sql`DROP TABLE IF EXISTS maritime_jobs;`.execute(db);
    await sql`DROP TABLE IF EXISTS maritime_quotations;`.execute(db);
    await sql`DROP TABLE IF EXISTS maritime_rfq_bids;`.execute(db);
    await sql`DROP TABLE IF EXISTS maritime_rfqs;`.execute(db);
    await sql`DROP TABLE IF EXISTS shipping_lines;`.execute(db);
    await sql`DROP TABLE IF EXISTS shipping_ports;`.execute(db);
  },
};
