import { sql, type Kysely } from 'kysely';

interface DefaultCarrierSeed {
  code: string;
  name_ar: string;
  name_en: string;
  carrier_type: 'shipping_line' | 'overseas_agent';
  country_name?: string | null;
  country_code?: string | null;
  city_name?: string | null;
  contact_person?: string | null;
  email?: string | null;
  rfq_email?: string | null;
  booking_email?: string | null;
  phone?: string | null;
  whatsapp?: string | null;
  wechat?: string | null;
  trade_lanes?: string | null;
  services_offered?: string | null;
  supported_ports?: string | null;
  tracking_url_template?: string | null;
  notes?: string | null;
}

interface DefaultPortSeed {
  code: string;
  name_ar: string;
  name_en: string;
  country_code: string;
  country_name: string;
}

const DEFAULT_SHIPPING_LINES: DefaultCarrierSeed[] = [
  {
    "code": "MSCU",
    "name_ar": "إم إس سي للملاحة (MSC Egypt & Global)",
    "name_en": "Mediterranean Shipping Company (MSC)",
    "carrier_type": "shipping_line",
    "country_name": "مصر والشرق الأوسط",
    "country_code": "EG",
    "city_name": "الإسكندرية والقاهرة",
    "contact_person": "MSC Egypt Sales & Ocean Rates Desk",
    "email": "EGY-rates@msc.com",
    "rfq_email": "EGY-rates@msc.com",
    "booking_email": "EGY-booking@msc.com",
    "phone": "+20 3 488 4000",
    "whatsapp": null,
    "trade_lanes": "far_east,europe_med,americas,arabian_gulf,africa",
    "services_offered": "FCL, Reefer, Breakbulk, Project Cargo",
    "supported_ports": null,
    "tracking_url_template": "https://www.msc.com/en/track-a-shipment?query={query}",
    "notes": "الخط الأول عالمياً - مكتب التسعير الإقليمي لمصر والبحر المتوسط (الإسكندرية، دمياط، بورسعيد، السخنة)"
  },
  {
    "code": "MAEU",
    "name_ar": "ميرسك سيلاند (Maersk Line Egypt)",
    "name_en": "A.P. Moller – Maersk",
    "carrier_type": "shipping_line",
    "country_name": "مصر",
    "country_code": "EG",
    "city_name": "القاهرة والإسكندرية",
    "contact_person": "Maersk Egypt Commercial & Rates Desk",
    "email": "egypt.sales@maersk.com",
    "rfq_email": "egypt.sales@maersk.com",
    "booking_email": "egypt.import@maersk.com",
    "phone": "+20 2 2461 3000",
    "whatsapp": null,
    "trade_lanes": "far_east,europe_med,americas,arabian_gulf,africa",
    "services_offered": "FCL, Cold Chain Reefer, End-to-End Logistics",
    "supported_ports": null,
    "tracking_url_template": "https://www.maersk.com/tracking/{query}",
    "notes": "مكتب ميرسك مصر - نايل سيتي تاورز، مبيعات النولون البحري"
  },
  {
    "code": "CMDU",
    "name_ar": "سي إم إيه سي جي إم (CMA CGM Egypt)",
    "name_en": "CMA CGM Group",
    "carrier_type": "shipping_line",
    "country_name": "مصر",
    "country_code": "EG",
    "city_name": "القاهرة والإسكندرية",
    "contact_person": "CMA CGM Egypt Rates & Commercial Desk",
    "email": "cai.sales@cma-cgm.com",
    "rfq_email": "cai.sales@cma-cgm.com",
    "booking_email": "alx.booking@cma-cgm.com",
    "phone": "+20 2 2728 0500",
    "whatsapp": null,
    "trade_lanes": "far_east,europe_med,americas,arabian_gulf,africa",
    "services_offered": "FCL, Reefers, Intermodal, Special Cargo",
    "supported_ports": null,
    "tracking_url_template": "https://www.cma-cgm.com/ebusiness/tracking/search?SearchBy=Container&Reference={query}",
    "notes": "مكتب سي إم إيه مصر - التسعير والحجوزات"
  },
  {
    "code": "COSU",
    "name_ar": "كوسكو للملاحة (COSCO Shipping Egypt)",
    "name_en": "COSCO Shipping Lines",
    "carrier_type": "shipping_line",
    "country_name": "مصر",
    "country_code": "EG",
    "city_name": "الإسكندرية وبورسعيد",
    "contact_person": "COSCO Shipping Lines Egypt Commercial Dept.",
    "email": "cscegy@coscon.com",
    "rfq_email": "cscegy@coscon.com",
    "booking_email": "marketing@cosco.com.eg",
    "phone": "+20 3 487 7144",
    "whatsapp": null,
    "trade_lanes": "far_east,europe_med,arabian_gulf",
    "services_offered": "FCL, China & Far East Direct Services, Bulk",
    "supported_ports": null,
    "tracking_url_template": "https://elines.coscoshipping.com/ebusiness/cargoTracking?trackingType=CONTAINER&number={query}",
    "notes": "المكتب الإقليمي للخط الصيني كوسكو بمصر"
  },
  {
    "code": "HLCU",
    "name_ar": "هاباج لويد (Hapag-Lloyd Area Egypt)",
    "name_en": "Hapag-Lloyd AG",
    "carrier_type": "shipping_line",
    "country_name": "مصر",
    "country_code": "EG",
    "city_name": "الإسكندرية والقاهرة",
    "contact_person": "Hapag-Lloyd Area Egypt Sales Desk",
    "email": "areaegypt@hlag.com",
    "rfq_email": "areaegypt@hlag.com",
    "booking_email": "alexandria@hlag.com",
    "phone": "+20 3 488 6600",
    "whatsapp": null,
    "trade_lanes": "far_east,europe_med,americas,arabian_gulf",
    "services_offered": "FCL, Dangerous Cargo (IMO), Reefer, Special Equipment",
    "supported_ports": null,
    "tracking_url_template": "https://www.hapag-lloyd.com/en/online-business/track/track-by-booking-solution.html?blno={query}",
    "notes": "المكتب الإقليمي لهاباج لويد مصر - الإسكندرية والقاهرة"
  },
  {
    "code": "ONEY",
    "name_ar": "أوشن نتورك إكسبريس (ONE Line Egypt)",
    "name_en": "Ocean Network Express (ONE)",
    "carrier_type": "shipping_line",
    "country_name": "مصر",
    "country_code": "EG",
    "city_name": "الإسكندرية",
    "contact_person": "Ocean Network Express Egypt Sales Team",
    "email": "eg.sales@one-line.com",
    "rfq_email": "eg.sales@one-line.com",
    "booking_email": "eg.booking@one-line.com",
    "phone": "+20 3 481 0550",
    "whatsapp": null,
    "trade_lanes": "far_east,europe_med,americas,arabian_gulf",
    "services_offered": "FCL, Magenta Reefers, Transpacific & Intra-Asia",
    "supported_ports": null,
    "tracking_url_template": "https://ecomm.one-line.com/one-ecom/manage-shipment/cargo-tracking?ctrac-field={query}",
    "notes": "التحالف الياباني (NYK, MOL, K-Line) - مكتب مصر"
  },
  {
    "code": "EGLV",
    "name_ar": "إيفرجرين (Evergreen Line Egypt)",
    "name_en": "Evergreen Marine Corp",
    "carrier_type": "shipping_line",
    "country_name": "مصر",
    "country_code": "EG",
    "city_name": "الإسكندرية",
    "contact_person": "Evergreen Marine Egypt Agency Commercial Team",
    "email": "biz@evergreen-shipping.com.eg",
    "rfq_email": "biz@evergreen-shipping.com.eg",
    "booking_email": "egyp-biz@evergreen-marine.com",
    "phone": "+20 3 484 2160",
    "whatsapp": null,
    "trade_lanes": "far_east,europe_med,americas",
    "services_offered": "FCL, General Cargo, Heavy Lift",
    "supported_ports": null,
    "tracking_url_template": "https://www.shipmentlink.com/servlet/TTrn_Tracking?type=CONTAINER&no={query}",
    "notes": "توكيل إيفرجرين التايواني في مصر"
  },
  {
    "code": "YMLU",
    "name_ar": "يانغ مينغ (Yang Ming Egypt Agency)",
    "name_en": "Yang Ming Marine Transport",
    "carrier_type": "shipping_line",
    "country_name": "مصر",
    "country_code": "EG",
    "city_name": "الإسكندرية",
    "contact_person": "Yang Ming Line Egypt Pricing Team",
    "email": "sales@yangming.com.eg",
    "rfq_email": "sales@yangming.com.eg",
    "booking_email": "pricing@yangming.com.eg",
    "phone": "+20 3 483 3100",
    "whatsapp": null,
    "trade_lanes": "far_east,europe_med,arabian_gulf",
    "services_offered": "FCL, Reefer Services",
    "supported_ports": null,
    "tracking_url_template": "https://www.yangming.com/e-service/track_trace/track_trace_cargo_tracking.aspx?type=CONTAINER&no={query}",
    "notes": "توكيل يانغ مينغ بمصر"
  },
  {
    "code": "ZIMU",
    "name_ar": "زيم للملاحة (ZIM Line Regional Desk)",
    "name_en": "ZIM Integrated Shipping",
    "carrier_type": "shipping_line",
    "country_name": "البحر المتوسط",
    "country_code": "CY",
    "city_name": "ليماسول",
    "contact_person": "ZIM Mediterranean Pricing Center",
    "email": "pricing.med@zim.com",
    "rfq_email": "pricing.med@zim.com",
    "booking_email": "booking.med@zim.com",
    "phone": "+357 25 889 000",
    "whatsapp": null,
    "trade_lanes": "europe_med,americas",
    "services_offered": "FCL, Transatlantic, Cross-Med",
    "supported_ports": null,
    "tracking_url_template": "https://www.zim.com/tools/track-a-shipment?consignment={query}",
    "notes": "المكتب الإقليمي للبحر المتوسط"
  },
  {
    "code": "HMMU",
    "name_ar": "إتش إم إم (Hyundai Merchant Marine Egypt)",
    "name_en": "HMM Co., Ltd. (Hyundai Merchant Marine)",
    "carrier_type": "shipping_line",
    "country_name": "مصر",
    "country_code": "EG",
    "city_name": "القاهرة والإسكندرية",
    "contact_person": "HMM Egypt Commercial & Ocean Freight Desk",
    "email": "eg.rates@hmm21.com",
    "rfq_email": "eg.rates@hmm21.com",
    "booking_email": "eg.booking@hmm21.com",
    "phone": "+20 2 2268 9100",
    "whatsapp": null,
    "trade_lanes": "far_east,europe_med,americas",
    "services_offered": "FCL, Mega Container Vessels, Korea & Far East routes",
    "supported_ports": null,
    "tracking_url_template": "https://www.hmm21.com/cms/business/ebusiness/trackTrace/index.jsp?number={query}",
    "notes": "العملاق الكوري الجنوبي - مكتب مصر للتسعير والحجوزات"
  },
  {
    "code": "ARKU",
    "name_ar": "أركاس لاين (Arkas Line Egypt)",
    "name_en": "Arkas Container Transport",
    "carrier_type": "shipping_line",
    "country_name": "مصر وتركيا",
    "country_code": "EG",
    "city_name": "الإسكندرية",
    "contact_person": "Arkas Egypt Rates & Sales Desk",
    "email": "pricing@arkas-egypt.com",
    "rfq_email": "pricing@arkas-egypt.com",
    "booking_email": "sales@arkas-egypt.com",
    "phone": "+20 3 487 0000",
    "whatsapp": null,
    "trade_lanes": "europe_med,black_sea,north_africa",
    "services_offered": "FCL, Feeder, Shortsea Mediterranean & Black Sea",
    "supported_ports": null,
    "tracking_url_template": "https://www.arkasline.com.tr/en/container-tracking?no={query}",
    "notes": "أكبر خط ملاحي إقليمي للبحر المتوسط والبحر الأسود وموانئ تركيا ومصر وإيطاليا وإسبانيا"
  },
  {
    "code": "PCIU",
    "name_ar": "بي آي إل (PIL Line Regional)",
    "name_en": "Pacific International Lines (PIL)",
    "carrier_type": "shipping_line",
    "country_name": "سنغافورة",
    "country_code": "SG",
    "city_name": "سنغافورة",
    "contact_person": "PIL Trade & Quotations Desk",
    "email": "rates@pilship.com",
    "rfq_email": "rates@pilship.com",
    "booking_email": "booking@pilship.com",
    "phone": "+65 6221 8133",
    "whatsapp": null,
    "trade_lanes": "far_east,red_sea,africa",
    "services_offered": "FCL, Red Sea, East & West Africa Specialist",
    "supported_ports": null,
    "tracking_url_template": "https://www.pilship.com/en-our-track-and-trace/120.html?ref={query}",
    "notes": "خط بي آي إل السنغافوري - تخصص البحر الأحمر وشرق وغرب إفريقيا"
  },
  {
    "code": "OOCL",
    "name_ar": "أو أو سي إل للملاحة (OOCL Egypt & Global)",
    "name_en": "Orient Overseas Container Line (OOCL)",
    "carrier_type": "shipping_line",
    "country_name": "مصر وهونغ كونغ",
    "country_code": "EG",
    "city_name": "الإسكندرية والقاهرة",
    "contact_person": "OOCL Egypt Rates & Customer Service",
    "email": "rates@oocl.com",
    "rfq_email": "egyrfq@oocl.com",
    "booking_email": "egyibk@oocl.com",
    "phone": "+20 3 487 5500",
    "whatsapp": null,
    "trade_lanes": "far_east,europe_med,americas",
    "services_offered": "FCL, Reefers, Intermodal",
    "supported_ports": "EGALY,EGPSD,CNSHA,CNNGB",
    "tracking_url_template": "https://www.oocl.com/eng/ourservices/eservices/cargotracking/Pages/cargotracking.aspx?query={query}",
    "notes": "خط ملاحي عالمي تابع لمجموعة كوسكو متفوق في خطوط الشرق الأقصى"
  },
  {
    "code": "WHLU",
    "name_ar": "وان هاي لاينز (Wan Hai Lines Regional)",
    "name_en": "Wan Hai Lines Ltd.",
    "carrier_type": "shipping_line",
    "country_name": "تايوان والشرق الأقصى",
    "country_code": "TW",
    "city_name": "تايبيه والشرق الأوسط",
    "contact_person": "Wan Hai Pricing & Route Desk",
    "email": "pricing@wanhai.com",
    "rfq_email": "rfq@wanhai.com",
    "booking_email": "booking@wanhai.com",
    "phone": "+886 2 2567 7961",
    "whatsapp": null,
    "trade_lanes": "far_east,arabian_gulf,red_sea",
    "services_offered": "Intra-Asia, Red Sea & Gulf Direct Calls",
    "supported_ports": "EGALY,CNSHA,CNNGB,SGSIN",
    "tracking_url_template": "https://www.wanhai.com/views/cargo/Track.xhtml?q={query}",
    "notes": "أكبر خط متخصص في خطوط شرق آسيا والبحر الأحمر"
  }
];

const DEFAULT_OVERSEAS_AGENTS: DefaultCarrierSeed[] = [
  {
    "code": "AGT-CN-SINO",
    "name_ar": "سينوترانس للشحن الدولي (Sinotrans China - وكيل الصين الأكبر)",
    "name_en": "Sinotrans Limited (China Ocean Freight & Logistics)",
    "carrier_type": "overseas_agent",
    "country_name": "الصين",
    "country_code": "CN",
    "city_name": "شنغهاي ونينغبو وتشنشن",
    "contact_person": "Sinotrans Overseas Ocean Pricing Desk",
    "email": "rates.eastchina@sinotrans.com",
    "rfq_email": "rates.eastchina@sinotrans.com",
    "booking_email": "booking.sh@sinotrans.com",
    "phone": "+86 21 6329 0000",
    "whatsapp": "+86 138 0000 8888",
    "wechat": "sinotrans_rates_desk",
    "trade_lanes": "far_east",
    "services_offered": "EXW, FOB, Ocean Freight, Customs Clearance, Rail Freight, Warehousing",
    "supported_ports": null,
    "notes": "الوكيل الحكومي الأكبر في الصين - تغطية شاملة لكافة موانئ ومصانع الصين (شنغهاي، نينغبو، شنتشن، تشينغداو)"
  },
  {
    "code": "AGT-TR-EKOL",
    "name_ar": "إيكول للشحن واللوجستيات (Ekol Turkey - وكيل تركيا والمتوسط)",
    "name_en": "Ekol Logistics (Turkey & Mediterranean Freight)",
    "carrier_type": "overseas_agent",
    "country_name": "تركيا",
    "country_code": "TR",
    "city_name": "إسطنبول ومرسين وإزمير",
    "contact_person": "Ekol Ocean Commercial & Rates Desk",
    "email": "turkey.pricing@ekol.com",
    "rfq_email": "turkey.pricing@ekol.com",
    "booking_email": "ocean.booking@ekol.com",
    "phone": "+90 216 564 3000",
    "whatsapp": "+90 530 000 1234",
    "wechat": null,
    "trade_lanes": "europe_med",
    "services_offered": "EXW, FOB, Door-to-Port, Turkish Customs, Inland Haulage, FCL/LCL",
    "supported_ports": null,
    "notes": "أكبر شبكة لوجستية ووكالة شحن بتركيا وموانئ أمبارلي ومرسين وإزمير وغبزة"
  },
  {
    "code": "AGT-DE-KN",
    "name_ar": "كوني آند ناجل الدولية (Kuehne + Nagel - الوكيل الأول عالمياً)",
    "name_en": "Kuehne + Nagel International AG",
    "carrier_type": "overseas_agent",
    "country_name": "ألمانيا",
    "country_code": "DE",
    "city_name": "هامبورغ وبريمرهافن وروتردام",
    "contact_person": "Kuehne+Nagel Ocean Freight Pricing Desk",
    "email": "ocean.pricing.de@kuehne-nagel.com",
    "rfq_email": "ocean.pricing.de@kuehne-nagel.com",
    "booking_email": "ocean.booking.de@kuehne-nagel.com",
    "phone": "+49 40 3010 1000",
    "whatsapp": "+49 170 000 9876",
    "wechat": null,
    "trade_lanes": "europe_med,americas",
    "services_offered": "FCL, LCL Seaexplorer, European Customs Clearance, Multimodal Rail & Road",
    "supported_ports": null,
    "notes": "الوكيل اللوجستي الأول عالمياً للشحن البحري - تغطية كامل الموانئ الأوروبية"
  },
  {
    "code": "AGT-AE-GAC",
    "name_ar": "وكالة الخليج للملاحة والشحن (GAC Dubai - وكيل الخليج وجبل علي)",
    "name_en": "Gulf Agency Company (GAC Logistics Dubai)",
    "carrier_type": "overseas_agent",
    "country_name": "الإمارات العربية المتحدة",
    "country_code": "AE",
    "city_name": "دبي - ميناء جبل علي",
    "contact_person": "GAC Freight & Commercial Pricing Desk",
    "email": "freight.dubai@gac.com",
    "rfq_email": "freight.dubai@gac.com",
    "booking_email": "operations.dubai@gac.com",
    "phone": "+971 4 881 1411",
    "whatsapp": "+971 50 000 4321",
    "wechat": null,
    "trade_lanes": "arabian_gulf",
    "services_offered": "Ocean Freight, Port Agency, Freezone Logistics, Cross-Trade, Transit Cargo",
    "supported_ports": null,
    "notes": "أعرق وأكبر وكيل شحن وخدمات موانئ في الخليج العربي وميناء جبل علي ومنطقة جافزا"
  },
  {
    "code": "AGT-US-EXPD",
    "name_ar": "إكسبيدايتورز الدولية للشحن (Expeditors USA)",
    "name_en": "Expeditors International of Washington",
    "carrier_type": "overseas_agent",
    "country_name": "الولايات المتحدة الأمريكية",
    "country_code": "US",
    "city_name": "سياتل ولوس أنجلوس ونيويورك",
    "contact_person": "Expeditors Ocean Rates & Compliance Desk",
    "email": "ocean.rates.us@expeditors.com",
    "rfq_email": "ocean.rates.us@expeditors.com",
    "booking_email": "booking.us@expeditors.com",
    "phone": "+1 206 674 3400",
    "whatsapp": null,
    "wechat": null,
    "trade_lanes": "americas,far_east",
    "services_offered": "FCL, FMC Licensed NVOCC, US Customs Brokerage, Intermodal Rail",
    "supported_ports": null,
    "notes": "أكبر وكيل شحن أمريكي معتمد ومرخص رسمياً من الهيئة البحرية الفيدرالية FMC"
  },
  {
    "code": "AGT-IN-ALLC",
    "name_ar": "أولكارجو لوجستكس (Allcargo India - وكيل شبه القارة الهندية)",
    "name_en": "Allcargo Logistics Ltd. (India & Subcontinent)",
    "carrier_type": "overseas_agent",
    "country_name": "الهند",
    "country_code": "IN",
    "city_name": "مومباي - ميناء نهافا شيفا",
    "contact_person": "Allcargo Ocean Pricing & Commercial Desk",
    "email": "pricing.india@allcargologistics.com",
    "rfq_email": "pricing.india@allcargologistics.com",
    "booking_email": "booking.bom@allcargologistics.com",
    "phone": "+91 22 6679 8100",
    "whatsapp": "+91 98 0000 5555",
    "wechat": null,
    "trade_lanes": "indian_sub",
    "services_offered": "FCL, LCL Consolidation, Nhava Sheva Port Handling, Indian Customs Export",
    "supported_ports": null,
    "notes": "الوكيل الهندي الأضخم وممثل موانئ نهافا شيفا (JNPT) وموندرا وتشيناي"
  },
  {
    "code": "AGT-DE-DHL",
    "name_ar": "دي إتش إل للشحن العالمي (DHL Global Forwarding)",
    "name_en": "DHL Global Forwarding",
    "carrier_type": "overseas_agent",
    "country_name": "ألمانيا",
    "country_code": "DE",
    "city_name": "بون وفرانكفورت وهامبورغ",
    "contact_person": "DHL Global Ocean Freight Pricing Desk",
    "email": "oceanfreight.rates@dhl.com",
    "rfq_email": "oceanfreight.rates@dhl.com",
    "booking_email": "ocean.booking@dhl.com",
    "phone": "+49 228 1820",
    "whatsapp": null,
    "wechat": null,
    "trade_lanes": "europe_med,far_east,americas,arabian_gulf",
    "services_offered": "FCL, LCL Consolidation, Temperature-Controlled Reefer, Global Customs",
    "supported_ports": null,
    "notes": "شبكة دي إتش إل اللوجستية العالمية للشحن البحري والجوي"
  },
  {
    "code": "AGT-DK-DSV",
    "name_ar": "دي إس في اللوجستية العالمية (DSV Global Logistics)",
    "name_en": "DSV Panalpina Global Transport and Logistics",
    "carrier_type": "overseas_agent",
    "country_name": "الدنمارك وأوروبا",
    "country_code": "DE",
    "city_name": "كوبنهاغن وروتردام وهامبورغ",
    "contact_person": "DSV Ocean Commercial & Pricing Team",
    "email": "sea.rates@dsv.com",
    "rfq_email": "sea.rates@dsv.com",
    "booking_email": "sea.booking@dsv.com",
    "phone": "+45 43 20 30 40",
    "whatsapp": null,
    "wechat": null,
    "trade_lanes": "europe_med,americas,far_east",
    "services_offered": "Ocean Freight FCL/LCL, Project Cargo, Supply Chain Solutions",
    "supported_ports": null,
    "notes": "ثاني أو ثالث أكبر عملاق لوجستي في العالم بعد الاستحواذ على بانالبينا وأجيليتي"
  },
  {
    "code": "AGT-DE-DB",
    "name_ar": "دي بي شينكر للشحن الدولي (DB Schenker Germany)",
    "name_en": "DB Schenker Logistics",
    "carrier_type": "overseas_agent",
    "country_name": "ألمانيا",
    "country_code": "DE",
    "city_name": "إيسن وهامبورغ وبرلين",
    "contact_person": "DB Schenker Ocean Desk",
    "email": "ocean.quotes@dbschenker.com",
    "rfq_email": "ocean.quotes@dbschenker.com",
    "booking_email": "ocean.bookings@dbschenker.com",
    "phone": "+49 201 8781 0",
    "whatsapp": null,
    "wechat": null,
    "trade_lanes": "europe_med,far_east",
    "services_offered": "Intermodal Rail-Sea, European Customs, Heavy Machinery, FCL",
    "supported_ports": null,
    "notes": "الذراع اللوجستي للسكك الحديدية الألمانية دويتشه بان"
  },
  {
    "code": "AGT-FR-CEVA",
    "name_ar": "سيفا لوجستكس (CEVA Logistics - مجموعة سي إم إيه)",
    "name_en": "CEVA Logistics (CMA CGM Group)",
    "carrier_type": "overseas_agent",
    "country_name": "فرنسا",
    "country_code": "FR",
    "city_name": "مارسيليا وباريس ولوهافر",
    "contact_person": "CEVA Ocean Freight Solutions Desk",
    "email": "ocean.rates@cevalogistics.com",
    "rfq_email": "ocean.rates@cevalogistics.com",
    "booking_email": "ocean.booking@cevalogistics.com",
    "phone": "+33 4 13 65 00 00",
    "whatsapp": null,
    "wechat": null,
    "trade_lanes": "europe_med,americas,africa",
    "services_offered": "End-to-End Ocean Logistics, Contract Logistics, Automotive, FCL",
    "supported_ports": null,
    "notes": "الذراع اللوجستي العالمي المتكامل لمجموعة CMA CGM الفرنسية"
  },
  {
    "code": "AGT-US-CHRW",
    "name_ar": "سي إتش روبنسون الدولية (C.H. Robinson USA)",
    "name_en": "C.H. Robinson Worldwide, Inc.",
    "carrier_type": "overseas_agent",
    "country_name": "الولايات المتحدة الأمريكية",
    "country_code": "US",
    "city_name": "مينيابوليس وشيكاغو ونيويورك",
    "contact_person": "C.H. Robinson Global Ocean Desk",
    "email": "oceanrates@chrobinson.com",
    "rfq_email": "oceanrates@chrobinson.com",
    "booking_email": "oceanbooking@chrobinson.com",
    "phone": "+1 855 229 6128",
    "whatsapp": null,
    "wechat": null,
    "trade_lanes": "americas,far_east",
    "services_offered": "FCL, NVOCC, North American Trucking, US Customs Clearance",
    "supported_ports": null,
    "notes": "أضخم منصة لوجستية وإدارة شحن بري وبحري في قارة أمريكا الشمالية"
  },
  {
    "code": "AGT-JP-NIPPON",
    "name_ar": "نيبون إكسبريس القابضة (Nippon Express - عملاق اليابان)",
    "name_en": "Nippon Express Holdings (NX Group)",
    "carrier_type": "overseas_agent",
    "country_name": "اليابان وشرق آسيا",
    "country_code": "JP",
    "city_name": "طوكيو ويوكوهاما وأوساكا",
    "contact_person": "NX Ocean Freight Commercial Desk",
    "email": "ocean.pricing@nipponexpress.com",
    "rfq_email": "ocean.pricing@nipponexpress.com",
    "booking_email": "ocean.booking@nipponexpress.com",
    "phone": "+81 3 6251 1111",
    "whatsapp": null,
    "wechat": null,
    "trade_lanes": "far_east,americas,europe_med",
    "services_offered": "High-Tech Cargo, Precision Equipment, FCL, Asian Intermodal",
    "supported_ports": null,
    "notes": "أكبر كيان لوجستي وشحن دولي في اليابان وشرق آسيا"
  },
  {
    "code": "AGT-FR-GEODIS",
    "name_ar": "جيوديس للشحن الدولي (Geodis France)",
    "name_en": "Geodis Global Freight Forwarding",
    "carrier_type": "overseas_agent",
    "country_name": "فرنسا وأوروبا",
    "country_code": "FR",
    "city_name": "باريس ولوهافر وليون",
    "contact_person": "Geodis Ocean Quotes Desk",
    "email": "ocean.pricing@geodis.com",
    "rfq_email": "ocean.pricing@geodis.com",
    "booking_email": "ocean.booking@geodis.com",
    "phone": "+33 1 56 76 26 00",
    "whatsapp": null,
    "wechat": null,
    "trade_lanes": "europe_med,americas",
    "services_offered": "Ocean Freight, European Distribution, Customs Brokerage",
    "supported_ports": null,
    "notes": "شركة الشحن والخدمات اللوجستية التابعة لمجموعة السكك الحديدية الفرنسية"
  },
  {
    "code": "AGT-DE-HELL",
    "name_ar": "هيلمان العالمية للوجستيات (Hellmann Worldwide)",
    "name_en": "Hellmann Worldwide Logistics",
    "carrier_type": "overseas_agent",
    "country_name": "ألمانيا",
    "country_code": "DE",
    "city_name": "أوسنابروك وهامبورغ وبريمن",
    "contact_person": "Hellmann Ocean Freight Rates Team",
    "email": "seafreight.rates@hellmann.com",
    "rfq_email": "seafreight.rates@hellmann.com",
    "booking_email": "seafreight.booking@hellmann.com",
    "phone": "+49 541 605 0",
    "whatsapp": null,
    "wechat": null,
    "trade_lanes": "europe_med,middle_east,americas",
    "services_offered": "Perishables, Automotive, Fashion Logistics, FCL/LCL",
    "supported_ports": null,
    "notes": "شركة لوجستيات ألمانية عريقة متخصصة في الشرق الأوسط وأوروبا"
  },
  {
    "code": "AGT-HK-KERRY",
    "name_ar": "كيري لوجستكس (Kerry Logistics - هونغ كونغ وجنوب آسيا)",
    "name_en": "Kerry Logistics Network Limited",
    "carrier_type": "overseas_agent",
    "country_name": "هونغ كونغ والصين",
    "country_code": "CN",
    "city_name": "هونغ كونغ وشنتشن وغوانغتشو",
    "contact_person": "Kerry Ocean Rates Commercial Desk",
    "email": "ocean.quotes@kerrylogistics.com",
    "rfq_email": "ocean.quotes@kerrylogistics.com",
    "booking_email": "ocean.booking@kerrylogistics.com",
    "phone": "+852 2410 3600",
    "whatsapp": "+852 9123 4567",
    "wechat": "kerry_ocean_rates",
    "trade_lanes": "far_east",
    "services_offered": "Greater China Logistics, Cross-Border E-Commerce, Ocean Freight",
    "supported_ports": null,
    "notes": "الشبكة اللوجستية الأوسع انتشاراً في جنوب الصين ودول الآسيان"
  },
  {
    "code": "AGT-JP-YUSEN",
    "name_ar": "يوسن لوجستكس (Yusen Logistics - مجموعة إن واي كيه)",
    "name_en": "Yusen Logistics (NYK Group)",
    "carrier_type": "overseas_agent",
    "country_name": "اليابان",
    "country_code": "JP",
    "city_name": "طوكيو ويوكوهاما وكوبي",
    "contact_person": "Yusen Ocean Freight Team",
    "email": "ocean.rates@jp.yusen-logistics.com",
    "rfq_email": "ocean.rates@jp.yusen-logistics.com",
    "booking_email": "booking@jp.yusen-logistics.com",
    "phone": "+81 3 6703 8100",
    "whatsapp": null,
    "wechat": null,
    "trade_lanes": "far_east,americas,europe_med",
    "services_offered": "FCL, Automotive Supply Chain, Pharmaceuticals, Ocean Freight",
    "supported_ports": null,
    "notes": "الذراع اللوجستي العالمي لعملاق الملاحة الياباني NYK Line"
  },
  {
    "code": "AGT-KW-AGIL",
    "name_ar": "أجيليتي لوجستكس (Agility - الكويت والشرق الأوسط)",
    "name_en": "Agility Logistics (Middle East & GCC)",
    "carrier_type": "overseas_agent",
    "country_name": "الكويت والخليج",
    "country_code": "AE",
    "city_name": "الكويت ودبي والرياض",
    "contact_person": "Agility Commercial Freight Desk",
    "email": "rates.me@agility.com",
    "rfq_email": "rates.me@agility.com",
    "booking_email": "booking.me@agility.com",
    "phone": "+965 1809 222",
    "whatsapp": "+965 9900 1122",
    "wechat": null,
    "trade_lanes": "arabian_gulf,middle_east",
    "services_offered": "Government & Defense, Project Logistics, GCC Warehousing, Customs",
    "supported_ports": null,
    "notes": "رائد اللوجستيات والمستودعات وسلاسل الإمداد في منطقة الخليج العربي"
  },
  {
    "code": "AGT-DE-DACH",
    "name_ar": "داكسر للشحن الذكي (Dachser Logistics Germany)",
    "name_en": "Dachser Intelligent Logistics",
    "carrier_type": "overseas_agent",
    "country_name": "ألمانيا وأوروبا",
    "country_code": "DE",
    "city_name": "كيمبتن وفرانكفورت وهامبورغ",
    "contact_person": "Dachser Air & Sea Logistics Desk",
    "email": "asl.quotes@dachser.com",
    "rfq_email": "asl.quotes@dachser.com",
    "booking_email": "asl.booking@dachser.com",
    "phone": "+49 831 5916 0",
    "whatsapp": null,
    "wechat": null,
    "trade_lanes": "europe_med,americas",
    "services_offered": "European Inland Transport, Air & Sea Logistics, Food Logistics",
    "supported_ports": null,
    "notes": "رائد اللوجستيات العائلية الألمانية وشبكة التوزيع الأوروبية الموحدة"
  },
  {
    "code": "AGT-SA-KANOO",
    "name_ar": "كانو للملاحة والخدمات اللوجستية (Kanoo Shipping Saudi)",
    "name_en": "Yusuf Bin Ahmed Kanoo Shipping",
    "carrier_type": "overseas_agent",
    "country_name": "المملكة العربية السعودية",
    "country_code": "AE",
    "city_name": "الدمام وجدة والجبيل",
    "contact_person": "Kanoo Commercial Shipping Desk",
    "email": "kanooshipping@kanoo.com",
    "rfq_email": "kanooshipping@kanoo.com",
    "booking_email": "agency.sa@kanoo.com",
    "phone": "+966 13 835 5555",
    "whatsapp": "+966 50 123 4567",
    "wechat": null,
    "trade_lanes": "arabian_gulf,middle_east",
    "services_offered": "Port Agency, Liner Representation, Offshore Support, Customs Clearance",
    "supported_ports": null,
    "notes": "أعرق وكالة ملاحية وخدمات موانئ في المملكة العربية السعودية وميناء الملك عبدالعزيز وجدة"
  },
  {
    "code": "AGT-AE-SHARAF",
    "name_ar": "شرف للشحن والتوكيلات الملاحية (Sharaf Shipping Agency)",
    "name_en": "Sharaf Shipping Agency",
    "carrier_type": "overseas_agent",
    "country_name": "الإمارات العربية المتحدة",
    "country_code": "AE",
    "city_name": "دبي - بر دبي وجبل علي",
    "contact_person": "Sharaf Ocean Rates Team",
    "email": "rates@sharafshipping.com",
    "rfq_email": "rates@sharafshipping.com",
    "booking_email": "booking@sharafshipping.com",
    "phone": "+971 4 520 4000",
    "whatsapp": "+971 50 999 8888",
    "wechat": null,
    "trade_lanes": "arabian_gulf,africa,indian_sub",
    "services_offered": "Liner Agency, Freight Forwarding, Hub Agency, Red Sea & East Africa",
    "supported_ports": null,
    "notes": "أكبر وكالة ملاحية إقليمية تغطي موانئ الخليج والبحر الأحمر وشرق إفريقيا"
  },
  {
    "code": "AGT-AE-DPW",
    "name_ar": "دي بي ورلد اللوجستية (DP World Logistics)",
    "name_en": "DP World Logistics & Supply Chain",
    "carrier_type": "overseas_agent",
    "country_name": "الإمارات العربية المتحدة",
    "country_code": "AE",
    "city_name": "دبي - موانئ دبي العالمية",
    "contact_person": "DP World Freight Solutions Desk",
    "email": "freight.solutions@dpworld.com",
    "rfq_email": "freight.solutions@dpworld.com",
    "booking_email": "cargo.booking@dpworld.com",
    "phone": "+971 4 880 5555",
    "whatsapp": null,
    "wechat": null,
    "trade_lanes": "arabian_gulf,far_east,europe_med,africa",
    "services_offered": "Global Port Terminal Operations, Free Trade Zone, End-to-End Freight",
    "supported_ports": null,
    "notes": "الذراع اللوجستي لموانئ دبي العالمية - ربط الموانئ بالمستودعات الذكية"
  },
  {
    "code": "AGT-JO-ARMX",
    "name_ar": "أرامكس للشحن الدولي واللوجستيات (Aramex Global Solutions)",
    "name_en": "Aramex International Freight Forwarding",
    "carrier_type": "overseas_agent",
    "country_name": "الأردن والشرق الأوسط",
    "country_code": "AE",
    "city_name": "عمّان ودبي والقاهرة",
    "contact_person": "Aramex Freight Solutions Manager",
    "email": "freightrates@aramex.com",
    "rfq_email": "freightrates@aramex.com",
    "booking_email": "freightbooking@aramex.com",
    "phone": "+962 6 535 8855",
    "whatsapp": "+962 79 123 4567",
    "wechat": null,
    "trade_lanes": "middle_east,arabian_gulf,americas",
    "services_offered": "Ocean Freight FCL, E-Commerce Cross-Border, Overland Trucking Middle East",
    "supported_ports": null,
    "notes": "شبكة أرامكس اللوجستية الكبرى للشحن البحري والبري والطرود بالشرق الأوسط"
  },
  {
    "code": "AGT-SG-BDP",
    "name_ar": "بي إس إيه بي دي بي الدولية (PSA BDP Singapore & USA)",
    "name_en": "PSA BDP International Logistics",
    "carrier_type": "overseas_agent",
    "country_name": "سنغافورة والولايات المتحدة",
    "country_code": "SG",
    "city_name": "سنغافورة وميامي وفيلادلفيا",
    "contact_person": "PSA BDP Ocean Control Desk",
    "email": "ocean.quotes@psabdp.com",
    "rfq_email": "ocean.quotes@psabdp.com",
    "booking_email": "booking@psabdp.com",
    "phone": "+65 6279 4000",
    "whatsapp": null,
    "wechat": null,
    "trade_lanes": "far_east,americas,europe_med",
    "services_offered": "Chemical Logistics, ISO Tanks, Mega Port Transshipment, Ocean Freight",
    "supported_ports": null,
    "notes": "التحالف اللوجستي العالمي بين هيئة موانئ سنغافورة PSA وعملاق الشحن BDP"
  },
  {
    "code": "AGT-CN-APEX",
    "name_ar": "أبكس لوجستكس الدولية (Apex Logistics China/US)",
    "name_en": "Apex Logistics International (Kuehne+Nagel Group)",
    "carrier_type": "overseas_agent",
    "country_name": "الصين والولايات المتحدة",
    "country_code": "CN",
    "city_name": "شنغهاي وشنتشن ولوس أنجلوس",
    "contact_person": "Apex Transpacific Rates Team",
    "email": "pricing.tp@apexglobe.com",
    "rfq_email": "pricing.tp@apexglobe.com",
    "booking_email": "booking.sha@apexglobe.com",
    "phone": "+86 21 6132 8888",
    "whatsapp": "+86 139 2222 3333",
    "wechat": "apex_freight_rates",
    "trade_lanes": "far_east,americas",
    "services_offered": "Transpacific Ocean Freight, China Export Customs, Cross-Border Logistics",
    "supported_ports": null,
    "notes": "أكبر وكيل متخصص في خطوط الملاحة بين موانئ الصين وموانئ الولايات المتحدة والشرق الأوسط"
  },
  {
    "code": "AGT-FR-BOLL",
    "name_ar": "بولوريه لوجستكس (Bolloré Logistics - متخصص إفريقيا والعالم)",
    "name_en": "Bolloré Logistics (Africa & Global Specialist)",
    "carrier_type": "overseas_agent",
    "country_name": "فرنسا وإفريقيا",
    "country_code": "FR",
    "city_name": "باريس وموانئ غرب إفريقيا",
    "contact_person": "Bolloré Africa Ocean Freight Desk",
    "email": "ocean.africa@bollore.com",
    "rfq_email": "ocean.africa@bollore.com",
    "booking_email": "booking.africa@bollore.com",
    "phone": "+33 1 46 96 44 33",
    "whatsapp": null,
    "wechat": null,
    "trade_lanes": "africa,europe_med",
    "services_offered": "African Port Corridors, Mining & Energy Logistics, Ocean Freight, Customs",
    "supported_ports": null,
    "notes": "الرائد التاريخي والأول عالمياً لموانئ ومعابر دول القارة الإفريقية"
  },
  {
    "code": "AGT-CN-SHA",
    "name_ar": "شنغهاي ترانس لوجستكس (وكيل شنغهاي)",
    "name_en": "Shanghai Trans-Cargo Logistics Co., Ltd.",
    "carrier_type": "overseas_agent",
    "country_name": "الصين",
    "country_code": "CN",
    "city_name": "شنغهاي",
    "contact_person": "Mr. David Wang / Rates Desk",
    "email": "rates@shanghaitrans-cargo.cn",
    "rfq_email": "rfq@shanghaitrans-cargo.cn",
    "booking_email": "booking@shanghaitrans-cargo.cn",
    "phone": "+86 21 6888 1234",
    "whatsapp": "+86 138 0000 1234",
    "wechat": "shanghai_trans_rates",
    "trade_lanes": "far_east",
    "services_offered": "FCL, LCL, Air Freight, Customs Clearance, Warehousing",
    "supported_ports": "CNSHA,CNNGB",
    "notes": "وكيل شحن رئيسي بموانئ شنغهاي وتشينغداو ونينغبو"
  },
  {
    "code": "AGT-CN-NGB",
    "name_ar": "نينغبو أوشن إكسبريس (وكيل نينغبو وتشيجيانغ)",
    "name_en": "Ningbo Ocean Express Logistics Ltd.",
    "carrier_type": "overseas_agent",
    "country_name": "الصين",
    "country_code": "CN",
    "city_name": "نينغبو",
    "contact_person": "Ms. Linda Chen / Booking Desk",
    "email": "pricing@ningbo-express.cn",
    "rfq_email": "rfq@ningbo-express.cn",
    "booking_email": "booking@ningbo-express.cn",
    "phone": "+86 574 8700 5678",
    "whatsapp": "+86 139 0000 5678",
    "wechat": "ningbo_ocean_rates",
    "trade_lanes": "far_east",
    "services_offered": "FCL, SOC Containers, Port Handling, Inland Drayage",
    "supported_ports": "CNNGB,CNSHA",
    "notes": "تغطية ميناء نينغبو-تشوشان والمناطق الصناعية المجاورة"
  }
];

const DEFAULT_SHIPPING_PORTS: DefaultPortSeed[] = [
  {
    "code": "EGALY",
    "name_ar": "ميناء الإسكندرية",
    "name_en": "Alexandria Port",
    "country_code": "EG",
    "country_name": "مصر"
  },
  {
    "code": "EGPSD",
    "name_ar": "ميناء بورسعيد",
    "name_en": "Port Said",
    "country_code": "EG",
    "country_name": "مصر"
  },
  {
    "code": "EGDAM",
    "name_ar": "ميناء دمياط",
    "name_en": "Damietta Port",
    "country_code": "EG",
    "country_name": "مصر"
  },
  {
    "code": "EGSOK",
    "name_ar": "ميناء السخنة",
    "name_en": "Ain Sokhna Port",
    "country_code": "EG",
    "country_name": "مصر"
  },
  {
    "code": "EGEDK",
    "name_ar": "ميناء الدخيلة",
    "name_en": "El Dekheila Port",
    "country_code": "EG",
    "country_name": "مصر"
  },
  {
    "code": "SAJED",
    "name_ar": "ميناء جدة الإسلامي",
    "name_en": "Jeddah Islamic Port",
    "country_code": "SA",
    "country_name": "السعودية"
  },
  {
    "code": "SADMM",
    "name_ar": "ميناء الملك عبد العزيز بالدمام",
    "name_en": "King Abdulaziz Port Dammam",
    "country_code": "SA",
    "country_name": "السعودية"
  },
  {
    "code": "AEJEA",
    "name_ar": "ميناء جبل علي - دبي",
    "name_en": "Jebel Ali Port Dubai",
    "country_code": "AE",
    "country_name": "الإمارات"
  },
  {
    "code": "AEAUH",
    "name_ar": "ميناء خليفة - أبوظبي",
    "name_en": "Khalifa Port Abu Dhabi",
    "country_code": "AE",
    "country_name": "الإمارات"
  },
  {
    "code": "CNSHA",
    "name_ar": "ميناء شنغهاي",
    "name_en": "Shanghai Port",
    "country_code": "CN",
    "country_name": "الصين"
  },
  {
    "code": "CNNGB",
    "name_ar": "ميناء نينغبو",
    "name_en": "Ningbo-Zhoushan Port",
    "country_code": "CN",
    "country_name": "الصين"
  },
  {
    "code": "CNSZX",
    "name_ar": "ميناء شنجن",
    "name_en": "Shenzhen Port",
    "country_code": "CN",
    "country_name": "الصين"
  },
  {
    "code": "CNQDG",
    "name_ar": "ميناء تشينغداو",
    "name_en": "Qingdao Port",
    "country_code": "CN",
    "country_name": "الصين"
  },
  {
    "code": "SGSIN",
    "name_ar": "ميناء سنغافورة",
    "name_en": "Singapore Port",
    "country_code": "SG",
    "country_name": "سنغافورة"
  },
  {
    "code": "NLRTM",
    "name_ar": "ميناء روتردام",
    "name_en": "Port of Rotterdam",
    "country_code": "NL",
    "country_name": "هولندا"
  },
  {
    "code": "DEHAM",
    "name_ar": "ميناء هامبورغ",
    "name_en": "Port of Hamburg",
    "country_code": "DE",
    "country_name": "ألمانيا"
  },
  {
    "code": "TRIST",
    "name_ar": "ميناء إسطنبول",
    "name_en": "Istanbul Port",
    "country_code": "TR",
    "country_name": "تركيا"
  },
  {
    "code": "INNSA",
    "name_ar": "ميناء نهافا شيفا - الهند",
    "name_en": "Nhava Sheva (JNPT)",
    "country_code": "IN",
    "country_name": "الهند"
  }
];

export const migration = {
  async up(db: Kysely<unknown>): Promise<void> {
    // 1. Seed 18 Standard International Ports for 'default' tenant
    for (const port of DEFAULT_SHIPPING_PORTS) {
      await sql`
        INSERT INTO shipping_ports (tenant_id, code, name_ar, name_en, country_code, country_name, is_active)
        VALUES ('default', ${port.code}, ${port.name_ar}, ${port.name_en}, ${port.country_code}, ${port.country_name}, true)
        ON CONFLICT (tenant_id, code) DO NOTHING;
      `.execute(db);
    }

    // 2. Seed 14 Standard Global Shipping Lines for 'default' tenant
    for (const line of DEFAULT_SHIPPING_LINES) {
      await sql`
        INSERT INTO shipping_lines (
          tenant_id, code, name_ar, name_en, carrier_type, country_name, country_code,
          city_name, contact_person, email, rfq_email, booking_email, phone, whatsapp,
          wechat, trade_lanes, services_offered, supported_ports, tracking_url_template, notes, is_active
        )
        VALUES (
          'default', ${line.code}, ${line.name_ar}, ${line.name_en}, 'shipping_line',
          ${line.country_name || null}, ${line.country_code || null}, ${line.city_name || null},
          ${line.contact_person || null}, ${line.email || null}, ${line.rfq_email || null},
          ${line.booking_email || null}, ${line.phone || null}, ${line.whatsapp || null},
          ${line.wechat || null}, ${line.trade_lanes || null}, ${line.services_offered || null},
          ${line.supported_ports || null}, ${line.tracking_url_template || null}, ${line.notes || null}, true
        )
        ON CONFLICT (tenant_id, code) DO NOTHING;
      `.execute(db);
    }

    // 3. Seed 27 Top Overseas Forwarders for 'default' tenant
    for (const agent of DEFAULT_OVERSEAS_AGENTS) {
      await sql`
        INSERT INTO shipping_lines (
          tenant_id, code, name_ar, name_en, carrier_type, country_name, country_code,
          city_name, contact_person, email, rfq_email, booking_email, phone, whatsapp,
          wechat, trade_lanes, services_offered, supported_ports, tracking_url_template, notes, is_active
        )
        VALUES (
          'default', ${agent.code}, ${agent.name_ar}, ${agent.name_en}, 'overseas_agent',
          ${agent.country_name || null}, ${agent.country_code || null}, ${agent.city_name || null},
          ${agent.contact_person || null}, ${agent.email || null}, ${agent.rfq_email || null},
          ${agent.booking_email || null}, ${agent.phone || null}, ${agent.whatsapp || null},
          ${agent.wechat || null}, ${agent.trade_lanes || null}, ${agent.services_offered || null},
          ${agent.supported_ports || null}, ${agent.tracking_url_template || null}, ${agent.notes || null}, true
        )
        ON CONFLICT (tenant_id, code) DO NOTHING;
      `.execute(db);
    }
  },

  async down(db: Kysely<unknown>): Promise<void> {
    // Non-destructive down migration to preserve customer modifications
  }
};
