import { sql, type Kysely } from 'kysely';

export const migration = {
  async up(db: Kysely<unknown>): Promise<void> {
    // =========================================================================
    // One-time reconciliation of the denormalised global stock counter.
    //
    // Why this is needed: several flows (van sales, the purchase-order receive path) used to write
    // product_location_stock directly without touching products.stock_qty. Every such operation
    // widened the gap between the per-location ledger and the global counter. Those flows are now
    // routed through applyStockDelta, so NEW movements stay consistent — but the historical drift
    // they left behind does not heal on its own, and any report reading products.stock_qty keeps
    // showing phantom quantities until it is corrected.
    //
    // Source of truth: SUM(product_location_stock.qty) per (tenant, account, product), including
    // rows whose location_id IS NULL (the "unassigned" balance). This is exactly the definition
    // applyStockDelta itself uses (`trueGlobalQty`), so after this runs the two agree by
    // construction.
    //
    // Safety: every correction is recorded in stock_reconciliation_log before being applied, so the
    // change is auditable and reversible. The migration is idempotent — re-running it corrects
    // nothing further once balances agree.
    // =========================================================================

    await sql`
      CREATE TABLE IF NOT EXISTS stock_reconciliation_log (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL,
        account_id TEXT NOT NULL,
        product_id BIGINT NOT NULL,
        previous_global_qty NUMERIC(15, 3) NOT NULL,
        corrected_global_qty NUMERIC(15, 3) NOT NULL,
        drift_qty NUMERIC(15, 3) NOT NULL,
        reconciled_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        reason TEXT NOT NULL DEFAULT 'global_counter_drift_repair'
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_stock_reconciliation_log_tenant
        ON stock_reconciliation_log (tenant_id, product_id, reconciled_at);
    `.execute(db);

    // 1. FIRST: products carrying a non-zero global counter but no location rows at all.
    //    The counter is the only surviving record of that stock, so it is parked on the unassigned
    //    balance rather than being zeroed — deleting stock because its location row is missing would
    //    be destructive. Doing this before the drift log keeps the log honest: otherwise these rows
    //    would be recorded as "correct to 0" while step 3 actually preserves them.
    await sql`
      INSERT INTO product_location_stock (tenant_id, account_id, product_id, branch_id, location_id, qty)
      SELECT p.tenant_id, p.account_id, p.id, NULL, NULL, p.stock_qty
      FROM products p
      WHERE COALESCE(p.item_type, 'product') <> 'service'
        AND COALESCE(p.stock_qty, 0) <> 0
        AND NOT EXISTS (
          SELECT 1 FROM product_location_stock pls
          WHERE pls.product_id = p.id
            AND pls.tenant_id = p.tenant_id
            AND pls.account_id = p.account_id
        );
    `.execute(db);

    // 2. Record every product whose global counter disagrees with the sum of its location balances.
    await sql`
      INSERT INTO stock_reconciliation_log
        (tenant_id, account_id, product_id, previous_global_qty, corrected_global_qty, drift_qty, reason)
      SELECT
        p.tenant_id,
        p.account_id,
        p.id,
        COALESCE(p.stock_qty, 0),
        COALESCE(pls.total_qty, 0),
        COALESCE(pls.total_qty, 0) - COALESCE(p.stock_qty, 0),
        'global_counter_drift_repair'
      FROM products p
      LEFT JOIN (
        SELECT tenant_id, account_id, product_id, SUM(qty) AS total_qty
        FROM product_location_stock
        GROUP BY tenant_id, account_id, product_id
      ) pls
        ON pls.product_id = p.id
       AND pls.tenant_id = p.tenant_id
       AND pls.account_id = p.account_id
      WHERE COALESCE(p.item_type, 'product') <> 'service'
        AND ABS(COALESCE(pls.total_qty, 0) - COALESCE(p.stock_qty, 0)) > 0.0005;
    `.execute(db);

    // 3. Apply the correction.
    await sql`
      UPDATE products p
      SET stock_qty = COALESCE(pls.total_qty, 0),
          updated_at = NOW()
      FROM (
        SELECT tenant_id, account_id, product_id, SUM(qty) AS total_qty
        FROM product_location_stock
        GROUP BY tenant_id, account_id, product_id
      ) pls
      WHERE pls.product_id = p.id
        AND pls.tenant_id = p.tenant_id
        AND pls.account_id = p.account_id
        AND COALESCE(p.item_type, 'product') <> 'service'
        AND ABS(COALESCE(pls.total_qty, 0) - COALESCE(p.stock_qty, 0)) > 0.0005;
    `.execute(db);

    // 4. Post-assertion: after the repair no tracked product may still disagree.
    const remaining = await sql<{ cnt: string }>`
      SELECT COUNT(*)::text AS cnt
      FROM products p
      LEFT JOIN (
        SELECT tenant_id, account_id, product_id, SUM(qty) AS total_qty
        FROM product_location_stock
        GROUP BY tenant_id, account_id, product_id
      ) pls
        ON pls.product_id = p.id
       AND pls.tenant_id = p.tenant_id
       AND pls.account_id = p.account_id
      WHERE COALESCE(p.item_type, 'product') <> 'service'
        AND ABS(COALESCE(pls.total_qty, 0) - COALESCE(p.stock_qty, 0)) > 0.0005;
    `.execute(db);

    const stillDrifting = Number(remaining.rows?.[0]?.cnt || 0);
    if (stillDrifting > 0) {
      throw new Error(
        `Stock reconciliation failed: ${stillDrifting} product(s) still disagree between products.stock_qty and SUM(product_location_stock.qty).`,
      );
    }
  },

  async down(db: Kysely<unknown>): Promise<void> {
    // Restore the pre-reconciliation counters from the log, newest entry per product first.
    await sql`
      UPDATE products p
      SET stock_qty = l.previous_global_qty,
          updated_at = NOW()
      FROM (
        SELECT DISTINCT ON (tenant_id, account_id, product_id)
          tenant_id, account_id, product_id, previous_global_qty
        FROM stock_reconciliation_log
        WHERE reason = 'global_counter_drift_repair'
        ORDER BY tenant_id, account_id, product_id, reconciled_at DESC
      ) l
      WHERE l.product_id = p.id
        AND l.tenant_id = p.tenant_id
        AND l.account_id = p.account_id;
    `.execute(db);

    await sql`DROP TABLE IF EXISTS stock_reconciliation_log CASCADE;`.execute(db);
  },
};
