import { Kysely, sql } from 'kysely';

export const migration = {
  async up(db: Kysely<unknown>): Promise<void> {
    await sql`CREATE TABLE IF NOT EXISTS pos_audit_events (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      tenant_id TEXT NOT NULL,
      account_id TEXT NOT NULL,
      event_type TEXT NOT NULL,
      user_id BIGINT NULL,
      sale_id BIGINT NULL,
      product_id BIGINT NULL,
      amount NUMERIC(14,2) NOT NULL DEFAULT 0,
      reason TEXT NOT NULL DEFAULT '',
      metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )`.execute(db);
    await sql`CREATE INDEX IF NOT EXISTS idx_pos_audit_events_tenant_created
      ON pos_audit_events (tenant_id, created_at DESC)`.execute(db);
  },

  async down(db: Kysely<unknown>): Promise<void> {
    await sql`DROP INDEX IF EXISTS idx_pos_audit_events_tenant_created`.execute(db);
    await sql`DROP TABLE IF EXISTS pos_audit_events`.execute(db);
  },
};
