import { Kysely, sql } from 'kysely';

/**
 * Migration 2040000000203: Van Distribution Complete Enhancements
 *
 * Adds core enterprise distribution capabilities for FMCG and wholesale:
 * 1. `van_trip_expenses`: Trip operational expenses (fuel, tolls, maintenance, tips, etc.)
 *    deducted from driver cash in hand during daily settlement.
 * 2. `van_trip_packaging_movements`: Returnable packaging & empties ledger (crates, bottles, pallets, cylinders).
 * 3. Supervisor credit limit override audit columns on `sales`.
 * 4. Multi-UOM and Free Goods / Bonus item columns on `sale_items`.
 */
export async function up(db: Kysely<any>): Promise<void> {
  // 1. Create van_trip_expenses table
  await sql`
    CREATE TABLE IF NOT EXISTS van_trip_expenses (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      tenant_id VARCHAR(50) NOT NULL,
      account_id VARCHAR(50) NOT NULL DEFAULT 'main',
      trip_id INTEGER NOT NULL REFERENCES van_sales_trips(id) ON DELETE CASCADE,
      expense_type VARCHAR(50) NOT NULL, -- 'fuel', 'toll', 'maintenance', 'tips', 'meals', 'other'
      amount NUMERIC(14, 2) NOT NULL CHECK (amount > 0),
      notes TEXT,
      receipt_photo_url TEXT,
      created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
  `.execute(db);

  await sql`
    CREATE INDEX IF NOT EXISTS idx_van_trip_expenses_tenant_trip
    ON van_trip_expenses (tenant_id, trip_id);
  `.execute(db);

  // 2. Create van_trip_packaging_movements (Returnable Packaging & Empties Ledger)
  await sql`
    CREATE TABLE IF NOT EXISTS van_trip_packaging_movements (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      tenant_id VARCHAR(50) NOT NULL,
      account_id VARCHAR(50) NOT NULL DEFAULT 'main',
      trip_id INTEGER NOT NULL REFERENCES van_sales_trips(id) ON DELETE CASCADE,
      customer_id BIGINT REFERENCES customers(id) ON DELETE SET NULL,
      package_type VARCHAR(50) NOT NULL, -- 'crate_plastic', 'box_wooden', 'bottle_glass', 'cylinder_gas', 'pallet'
      delivered_qty INTEGER NOT NULL DEFAULT 0,
      returned_qty INTEGER NOT NULL DEFAULT 0,
      notes TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
  `.execute(db);

  await sql`
    CREATE INDEX IF NOT EXISTS idx_van_packaging_tenant_trip
    ON van_trip_packaging_movements (tenant_id, trip_id);

    CREATE INDEX IF NOT EXISTS idx_van_packaging_tenant_customer
    ON van_trip_packaging_movements (tenant_id, customer_id);
  `.execute(db);

  // 3. Extend sales with Supervisor Credit Limit Override
  await sql`
    ALTER TABLE sales
    ADD COLUMN IF NOT EXISTS is_credit_overridden BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS credit_override_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS credit_override_reason TEXT;
  `.execute(db);

  // 4. Extend sale_items with Free Goods / Bonus and Multi-Unit tracking
  await sql`
    ALTER TABLE sale_items
    ADD COLUMN IF NOT EXISTS is_bonus BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS bonus_reason TEXT,
    ADD COLUMN IF NOT EXISTS unit_name VARCHAR(50),
    ADD COLUMN IF NOT EXISTS unit_multiplier NUMERIC(14, 4) DEFAULT 1;
  `.execute(db);

  // 5. Extend users with Supervisor Authorization PIN
  await sql`
    ALTER TABLE users
    ADD COLUMN IF NOT EXISTS pin VARCHAR(10) NULL,
    ADD COLUMN IF NOT EXISTS pin_hash TEXT NULL;
  `.execute(db);
}

export async function down(db: Kysely<any>): Promise<void> {
  await sql`
    ALTER TABLE users
    DROP COLUMN IF EXISTS pin_hash,
    DROP COLUMN IF EXISTS pin;
  `.execute(db);

  await sql`
    ALTER TABLE sale_items
    DROP COLUMN IF EXISTS unit_multiplier,
    DROP COLUMN IF EXISTS unit_name,
    DROP COLUMN IF EXISTS bonus_reason,
    DROP COLUMN IF EXISTS is_bonus;
  `.execute(db);

  await sql`
    ALTER TABLE sales
    DROP COLUMN IF EXISTS credit_override_reason,
    DROP COLUMN IF EXISTS credit_override_by_user_id,
    DROP COLUMN IF EXISTS is_credit_overridden;
  `.execute(db);

  await sql`DROP TABLE IF EXISTS van_trip_packaging_movements;`.execute(db);
  await sql`DROP TABLE IF EXISTS van_trip_expenses;`.execute(db);
}

export const migration = { up, down };
