import { sql, type Kysely } from 'kysely';

/**
 * Migration 2040000000200: Complete Enterprise Expansion for Maritime Freight & Logistics Suite.
 *
 * Implements the 9 strategic pillars:
 * 1. Multi-Currency Split Pricing & ROE (Foreign vs Local Currency + Rate of Exchange Lock + Realized Forex Gain/Loss)
 * 2. Itemized Line-Item Freight Charges & Tax Grid (maritime_quotation_charges & maritime_job_charges)
 * 3. Egyptian Customs ACI & ACID Data Integration (19-digit ACID, issue/expiry dates, exporter ID, tax ID)
 * 4. Consolidation & LCL Operations (Parent/Child Master-House Jobs link, sub_job_count)
 * 5. Overseas Agents Reciprocal Accounting & Profit Sharing (maritime_agent_settlements: DN/CN, SOA, 50/50 profit share)
 * 6. Digital Shipment e-Folder / Document Binder (maritime_job_documents)
 * 7. Export Critical Cut-off Deadlines (SI, VGM, Gate-in / Port Cut-off timestamps)
 * 8. Inland Haulage & Container Dispatch (maritime_inland_trucking_trips)
 * 9. Carrier Live Tracking Hub & API Events (maritime_carrier_api_events)
 */
export const migration = {
  async up(db: Kysely<unknown>): Promise<void> {
    // 1. Expand maritime_jobs with Consolidation, Egyptian ACI, ROE, and Cut-off milestones
    await sql`
      ALTER TABLE maritime_jobs 
      ADD COLUMN IF NOT EXISTS parent_job_id BIGINT NULL REFERENCES maritime_jobs(id) ON DELETE SET NULL,
      ADD COLUMN IF NOT EXISTS is_consolidation_master BOOLEAN NOT NULL DEFAULT FALSE,
      ADD COLUMN IF NOT EXISTS sub_job_count INTEGER NOT NULL DEFAULT 0,
      ADD COLUMN IF NOT EXISTS acid_number TEXT NULL,
      ADD COLUMN IF NOT EXISTS acid_issue_date DATE NULL,
      ADD COLUMN IF NOT EXISTS acid_expiry_date DATE NULL,
      ADD COLUMN IF NOT EXISTS foreign_exporter_id TEXT NULL,
      ADD COLUMN IF NOT EXISTS importer_tax_id TEXT NULL,
      ADD COLUMN IF NOT EXISTS quote_roe NUMERIC(12, 4) NULL,
      ADD COLUMN IF NOT EXISTS actual_roe NUMERIC(12, 4) NULL,
      ADD COLUMN IF NOT EXISTS forex_gain_loss NUMERIC(15, 3) NOT NULL DEFAULT 0,
      ADD COLUMN IF NOT EXISTS roe_clause_agreed BOOLEAN NOT NULL DEFAULT TRUE,
      ADD COLUMN IF NOT EXISTS si_cutoff_date TIMESTAMPTZ NULL,
      ADD COLUMN IF NOT EXISTS vgm_cutoff_date TIMESTAMPTZ NULL,
      ADD COLUMN IF NOT EXISTS port_cutoff_date TIMESTAMPTZ NULL;
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_maritime_jobs_parent 
      ON maritime_jobs (tenant_id, parent_job_id);
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_maritime_jobs_acid 
      ON maritime_jobs (tenant_id, acid_number);
    `.execute(db);

    // 2. Expand maritime_quotations with Multi-Currency, Split Pricing, ACI, and ROE
    await sql`
      ALTER TABLE maritime_quotations
      ADD COLUMN IF NOT EXISTS quote_roe NUMERIC(12, 4) NULL,
      ADD COLUMN IF NOT EXISTS roe_clause_text TEXT NULL,
      ADD COLUMN IF NOT EXISTS is_split_currency BOOLEAN NOT NULL DEFAULT FALSE,
      ADD COLUMN IF NOT EXISTS foreign_currency TEXT NOT NULL DEFAULT 'USD',
      ADD COLUMN IF NOT EXISTS foreign_currency_amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
      ADD COLUMN IF NOT EXISTS local_currency_amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
      ADD COLUMN IF NOT EXISTS acid_number TEXT NULL;
    `.execute(db);

    // 3. Itemized Quotation Charges Table
    await sql`
      CREATE TABLE IF NOT EXISTS maritime_quotation_charges (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        quotation_id BIGINT NOT NULL REFERENCES maritime_quotations(id) ON DELETE CASCADE,
        charge_code TEXT NOT NULL,
        charge_name_ar TEXT NOT NULL,
        charge_name_en TEXT NOT NULL,
        currency TEXT NOT NULL DEFAULT 'USD',
        unit_rate NUMERIC(15, 3) NOT NULL DEFAULT 0,
        quantity NUMERIC(12, 3) NOT NULL DEFAULT 1,
        total_amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        is_local_charge BOOLEAN NOT NULL DEFAULT FALSE,
        tax_rate_percent NUMERIC(5, 2) NOT NULL DEFAULT 0,
        tax_amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_quotation_charges_tenant_quote 
      ON maritime_quotation_charges (tenant_id, quotation_id);
    `.execute(db);

    // 4. Itemized Job Charges Table
    await sql`
      CREATE TABLE IF NOT EXISTS maritime_job_charges (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        job_id BIGINT NOT NULL REFERENCES maritime_jobs(id) ON DELETE CASCADE,
        charge_code TEXT NOT NULL,
        charge_name_ar TEXT NOT NULL,
        charge_name_en TEXT NOT NULL,
        currency TEXT NOT NULL DEFAULT 'USD',
        cost_amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        sell_amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        profit_amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        is_local_charge BOOLEAN NOT NULL DEFAULT FALSE,
        tax_rate_percent NUMERIC(5, 2) NOT NULL DEFAULT 0,
        tax_amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        is_invoiced BOOLEAN NOT NULL DEFAULT FALSE,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_job_charges_tenant_job 
      ON maritime_job_charges (tenant_id, job_id);
    `.execute(db);

    // 5. Digital Shipment e-Folder / Document Binder
    await sql`
      CREATE TABLE IF NOT EXISTS maritime_job_documents (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        job_id BIGINT NOT NULL REFERENCES maritime_jobs(id) ON DELETE CASCADE,
        doc_type TEXT NOT NULL DEFAULT 'other',
        title TEXT NOT NULL,
        file_name TEXT NOT NULL,
        file_url TEXT NOT NULL,
        file_size_bytes INTEGER NOT NULL DEFAULT 0,
        mime_type TEXT NOT NULL DEFAULT 'application/pdf',
        notes TEXT NULL,
        uploaded_by TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT chk_job_doc_type CHECK (doc_type IN (
          'commercial_invoice', 'packing_list', 'certificate_of_origin', 
          'form4_bank_swift', 'ocean_bl_copy', 'air_waybill_copy', 
          'telex_release', 'delivery_order', 'customs_declaration', 
          'inspection_cert', 'insurance_cert', 'other'
        ))
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_job_documents_tenant_job 
      ON maritime_job_documents (tenant_id, job_id);
    `.execute(db);

    // 6. Overseas Agent Settlements & Profit Sharing (SOA)
    await sql`
      CREATE TABLE IF NOT EXISTS maritime_agent_settlements (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        agent_id BIGINT NULL REFERENCES shipping_lines(id) ON DELETE SET NULL,
        agent_name TEXT NOT NULL DEFAULT '',
        job_id BIGINT NULL REFERENCES maritime_jobs(id) ON DELETE SET NULL,
        job_number TEXT NULL,
        settlement_type TEXT NOT NULL DEFAULT 'profit_share',
        currency TEXT NOT NULL DEFAULT 'USD',
        amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        profit_share_percent NUMERIC(5, 2) NOT NULL DEFAULT 50.00,
        local_equivalent_amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        exchange_rate NUMERIC(12, 4) NOT NULL DEFAULT 1.0,
        reference_number TEXT NULL,
        status TEXT NOT NULL DEFAULT 'pending',
        notes TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT chk_agent_settlement_type CHECK (settlement_type IN ('debit_note', 'credit_note', 'profit_share', 'offset_clearing')),
        CONSTRAINT chk_agent_settlement_status CHECK (status IN ('pending', 'approved', 'cleared', 'disputed'))
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_agent_settlements_tenant 
      ON maritime_agent_settlements (tenant_id, agent_id);
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_agent_settlements_status 
      ON maritime_agent_settlements (tenant_id, status);
    `.execute(db);

    // 7. Inland Trucking Trips & Container Dispatch
    await sql`
      CREATE TABLE IF NOT EXISTS maritime_inland_trucking_trips (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        job_id BIGINT NOT NULL REFERENCES maritime_jobs(id) ON DELETE CASCADE,
        trip_number TEXT NOT NULL,
        container_number TEXT NULL,
        trucking_company TEXT NOT NULL DEFAULT '',
        driver_name TEXT NOT NULL,
        driver_phone TEXT NULL,
        truck_plate TEXT NOT NULL,
        trailer_plate TEXT NULL,
        origin_port_terminal TEXT NOT NULL,
        delivery_destination TEXT NOT NULL,
        dispatch_date TIMESTAMPTZ NULL,
        delivery_date TIMESTAMPTZ NULL,
        trip_status TEXT NOT NULL DEFAULT 'assigned',
        cost_amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        sell_amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        currency TEXT NOT NULL DEFAULT 'EGP',
        notes TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT chk_trucking_trip_status CHECK (trip_status IN ('assigned', 'loading', 'in_transit', 'delivered', 'empty_returned'))
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_trucking_trips_tenant_job 
      ON maritime_inland_trucking_trips (tenant_id, job_id);
    `.execute(db);

    // 8. Carrier Live Tracking Hub & API Events
    await sql`
      CREATE TABLE IF NOT EXISTS maritime_carrier_api_events (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        carrier_code TEXT NOT NULL,
        tracking_number TEXT NOT NULL,
        event_type TEXT NOT NULL,
        event_location TEXT NULL,
        event_time TIMESTAMPTZ NOT NULL,
        raw_payload JSONB NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_carrier_api_events_lookup 
      ON maritime_carrier_api_events (tenant_id, tracking_number);
    `.execute(db);
  },

  async down(db: Kysely<unknown>): Promise<void> {
    await sql`DROP TABLE IF EXISTS maritime_carrier_api_events;`.execute(db);
    await sql`DROP TABLE IF EXISTS maritime_inland_trucking_trips;`.execute(db);
    await sql`DROP TABLE IF EXISTS maritime_agent_settlements;`.execute(db);
    await sql`DROP TABLE IF EXISTS maritime_job_documents;`.execute(db);
    await sql`DROP TABLE IF EXISTS maritime_job_charges;`.execute(db);
    await sql`DROP TABLE IF EXISTS maritime_quotation_charges;`.execute(db);
    await sql`
      ALTER TABLE maritime_quotations
      DROP COLUMN IF EXISTS quote_roe,
      DROP COLUMN IF EXISTS roe_clause_text,
      DROP COLUMN IF EXISTS is_split_currency,
      DROP COLUMN IF EXISTS foreign_currency,
      DROP COLUMN IF EXISTS foreign_currency_amount,
      DROP COLUMN IF EXISTS local_currency_amount,
      DROP COLUMN IF EXISTS acid_number;
    `.execute(db);
    await sql`
      ALTER TABLE maritime_jobs
      DROP COLUMN IF EXISTS parent_job_id,
      DROP COLUMN IF EXISTS is_consolidation_master,
      DROP COLUMN IF EXISTS sub_job_count,
      DROP COLUMN IF EXISTS acid_number,
      DROP COLUMN IF EXISTS acid_issue_date,
      DROP COLUMN IF EXISTS acid_expiry_date,
      DROP COLUMN IF EXISTS foreign_exporter_id,
      DROP COLUMN IF EXISTS importer_tax_id,
      DROP COLUMN IF EXISTS quote_roe,
      DROP COLUMN IF EXISTS actual_roe,
      DROP COLUMN IF EXISTS forex_gain_loss,
      DROP COLUMN IF EXISTS roe_clause_agreed,
      DROP COLUMN IF EXISTS si_cutoff_date,
      DROP COLUMN IF EXISTS vgm_cutoff_date,
      DROP COLUMN IF EXISTS port_cutoff_date;
    `.execute(db);
  },
};
