import { sql, type Kysely } from 'kysely';

export const migration = {
  async up(db: Kysely<unknown>): Promise<void> {
    // 1. Work Inspection Requests (طلبات فحص واستلام الأعمال الهندسية بالموقع WIR)
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_inspection_requests (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        project_id BIGINT NOT NULL REFERENCES contracting_projects(id) ON DELETE CASCADE,
        wir_number TEXT NOT NULL,
        boq_item_id BIGINT NULL REFERENCES contracting_boq_items(id) ON DELETE SET NULL,
        subcontract_id BIGINT NULL REFERENCES contracting_subcontracts(id) ON DELETE SET NULL,
        location_grid TEXT NOT NULL DEFAULT '',
        trade_category TEXT NOT NULL DEFAULT 'civil_concrete',
        inspection_type TEXT NOT NULL DEFAULT 'work_inspection',
        scheduled_date DATE NOT NULL DEFAULT CURRENT_DATE,
        status TEXT NOT NULL DEFAULT 'submitted',
        consultant_name TEXT NULL,
        consultant_notes TEXT NULL,
        inspected_at TIMESTAMPTZ NULL,
        attachments TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_contracting_wir_tenant_num UNIQUE (tenant_id, wir_number)
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_wir_proj_status 
      ON contracting_inspection_requests (tenant_id, project_id, status);
    `.execute(db);

    // 2. Snag Items & Punch List (قائمة الملاحظات وعيوب المصنعية والتسليم)
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_snag_items (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        project_id BIGINT NOT NULL REFERENCES contracting_projects(id) ON DELETE CASCADE,
        boq_item_id BIGINT NULL REFERENCES contracting_boq_items(id) ON DELETE SET NULL,
        item_title TEXT NOT NULL,
        location_desc TEXT NOT NULL DEFAULT '',
        severity TEXT NOT NULL DEFAULT 'minor',
        responsible_party TEXT NOT NULL DEFAULT 'subcontractor',
        subcontractor_id BIGINT NULL REFERENCES suppliers(id) ON DELETE SET NULL,
        subcontract_id BIGINT NULL REFERENCES contracting_subcontracts(id) ON DELETE SET NULL,
        assigned_to TEXT NULL,
        due_date DATE NULL,
        status TEXT NOT NULL DEFAULT 'open',
        rectified_date DATE NULL,
        verified_by TEXT NULL,
        notes TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_snag_proj_status 
      ON contracting_snag_items (tenant_id, project_id, status);
    `.execute(db);

    // 3. Project Handovers & Guarantee Releases (محاضر التسليم الابتدائي والنهائي وفك الضمان)
    await sql`
      CREATE TABLE IF NOT EXISTS contracting_project_handovers (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tenant_id TEXT NOT NULL DEFAULT '',
        project_id BIGINT NOT NULL REFERENCES contracting_projects(id) ON DELETE CASCADE,
        handover_type TEXT NOT NULL DEFAULT 'preliminary',
        handover_date DATE NOT NULL DEFAULT CURRENT_DATE,
        committee_members TEXT NOT NULL DEFAULT '',
        warranty_start_date DATE NULL,
        warranty_end_date DATE NULL,
        retention_release_amount NUMERIC(15, 3) NOT NULL DEFAULT 0,
        status TEXT NOT NULL DEFAULT 'draft',
        certificate_ref TEXT NULL,
        notes TEXT NULL,
        approved_by TEXT NULL,
        approved_at TIMESTAMPTZ NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `.execute(db);

    await sql`
      CREATE INDEX IF NOT EXISTS idx_contracting_handovers_proj 
      ON contracting_project_handovers (tenant_id, project_id, handover_type);
    `.execute(db);

    // 4. Add subcontract_id to contracting_invoices if not present
    await sql`
      ALTER TABLE contracting_invoices 
      ADD COLUMN IF NOT EXISTS subcontract_id BIGINT NULL REFERENCES contracting_subcontracts(id) ON DELETE SET NULL;
    `.execute(db);
  },

  async down(db: Kysely<unknown>): Promise<void> {
    await sql`DROP TABLE IF EXISTS contracting_project_handovers CASCADE;`.execute(db);
    await sql`DROP TABLE IF EXISTS contracting_snag_items CASCADE;`.execute(db);
    await sql`DROP TABLE IF EXISTS contracting_inspection_requests CASCADE;`.execute(db);
  },
};
